import { TTable } from "../../types";

export const produto_controle: TTable = {
  database: "plano",
  table: "Lotes",
  fields: [
    {
      field: "CdLote",
      label: "CdLote",
      name: "controle",
      typeField: "string",
      size: 18,
      allowNull: false,
      primaryKey: true,
    },
    {
      field: "CdProduto",
      label: "CdProduto",
      name: "produto_plano_id",
      typeField: "string",
      size: 15,
      allowNull: false,
      primaryKey: true,
    },
    {
      field: "CdFornecedor",
      label: "CdFornecedor",
      name: "fornecedor_id",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
      primaryKey: true,
    },
    {
      field: "CdNRA",
      label: "CdNRA",
      name: "nra_id",
      typeField: "string",
      size: 6,
    },
    {
      field: "DtFabricacao",
      label: "DtFabricacao",
      name: "data_fabricacao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DtValidade",
      label: "DtValidade",
      name: "data_validade",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DtAnalise",
      label: "DtAnalise",
      name: "data_analise",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "Aspecto",
      label: "Aspecto",
      name: "aspecto",
      typeField: "string",
      size: 40,
    },
    {
      field: "FatorCorrecao",
      label: "FatorCorrecao",
      name: "fator_correcao",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Densidade",
      label: "Densidade",
      name: "densidade",
      typeField: "float",
      size: 4,
    },
    {
      field: "PercentualDiluicao",
      label: "PercentualDiluicao",
      name: "percentual_diluicao",
      typeField: "float",
      size: 4,
    },
    {
      field: "SituacaoLote",
      label: "SituacaoLote",
      name: "situacao_lote",
      typeField: "string",
      size: 1,
    },
    {
      field: "SerieNfEntrada",
      label: "SerieNfEntrada",
      name: "serie_id",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "QtdeAdquirida",
      label: "QtdeAdquirida",
      name: "quantidade_adquirida",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "NumNfEntrada",
      label: "NumNfEntrada",
      name: "nota_id",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "SaldoPeso",
      label: "SaldoPeso",
      name: "saldo_peso",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "DtEntrada",
      label: "DtEntrada",
      name: "data_entrada",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DtLimiteUso",
      label: "DtLimiteUso",
      name: "data_limite_uso",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "TipoLote",
      label: "TipoLote",
      name: "tipo_lote",
      typeField: "string",
      size: 1,
    },
    {
      field: "IdReduzido",
      label: "IdReduzido",
      name: "IdReduzido",
      typeField: "float",
      size: 8,
    },
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "filial_id",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "modelo_id",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    // {
    //   field: "NumLote",
    //   label: "NumLote",
    //   name: "controle",
    //   typeField: "string",
    //   size: 18,
    // },
  ],
};
