import { TTable } from "../../types";

export const nf_saida: TTable = {
  database: "plano",
  table: "MestreNota",
  fields: [
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "filial_id",
      primaryKey: true,
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumNota",
      label: "NumNota",
      name: "nota_id",
      primaryKey: true,
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "Serie",
      label: "Serie",
      name: "serie_id",
      primaryKey: true,
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "modelo_id",
      primaryKey: true,
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "DtEmissao",
      label: "DtEmissao",
      name: "data_emissao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "Tipo",
      label: "Tipo",
      name: "tipo",
      typeField: "string",
      size: 1,
    },
    {
      field: "CdCliente",
      label: "CdCliente",
      name: "cliente_id",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "CdVendedor",
      label: "CdVendedor",
      name: "vendedor_id",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "FgEstatistica",
      label: "FgEstatistica",
      name: "eh_estatistica",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgEstoque",
      label: "FgEstoque",
      name: "eh_estoque",
      typeField: "string",
      size: 1,
    },
    {
      field: "VlTotal",
      label: "VlTotal",
      name: "valor_total",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlBaseCalculo",
      label: "VlBaseCalculo",
      name: "valor_base_calculo",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "BaseSubstituicao",
      label: "BaseSubstituicao",
      name: "BaseSubstituicao",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "IcmsSubstituicao",
      label: "IcmsSubstituicao",
      name: "IcmsSubstituicao",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlIcms",
      label: "VlIcms",
      name: "valor_icms",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlIRRF",
      label: "VlIRRF",
      name: "VlIRRF",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlISS",
      label: "VlISS",
      name: "VlISS",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlProdutos",
      label: "VlProdutos",
      name: "valor_produto",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlFrete",
      label: "VlFrete",
      name: "valor_frete",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlSeguro",
      label: "VlSeguro",
      name: "valor_seguro",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlAcessorias",
      label: "VlAcessorias",
      name: "VlAcessorias",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlIPI",
      label: "VlIPI",
      name: "VlIPI",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Servico",
      label: "Servico",
      name: "Servico",
      typeField: "string",
      size: 1024,
    },
    {
      field: "VlServico",
      label: "VlServico",
      name: "VlServico",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "NumPedido",
      label: "NumPedido",
      name: "pedido_id",
      typeField: "int",
      size: 4,
    },
    {
      field: "OrdemCompra",
      label: "OrdemCompra",
      name: "compra_id",
      typeField: "string",
      size: 20,
    },
    {
      field: "NumNotaOrigem",
      label: "NumNotaOrigem",
      name: "NumNotaOrigem",
      typeField: "int",
      size: 4,
    },
    {
      field: "DtUltAlteracao",
      label: "DtUltAlteracao",
      name: "DtUltAlteracao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "Horario",
      label: "Horario",
      name: "horario",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "FgRatearDescontoAcrescimo",
      label: "FgRatearDescontoAcrescimo",
      name: "FgRatearDescontoAcrescimo",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgDesconto",
      label: "FgDesconto",
      name: "eh_desconto",
      typeField: "string",
      size: 1,
    },
    {
      field: "VlDesconto",
      label: "VlDesconto",
      name: "valor_desconto",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "NumCupomFiscalOrigem",
      label: "NumCupomFiscalOrigem",
      name: "NumCupomFiscalOrigem",
      typeField: "int",
      size: 4,
    },
    {
      field: "NumPDVOrigem",
      label: "NumPDVOrigem",
      name: "NumPDVOrigem",
      typeField: "int",
      size: 4,
    },
    {
      field: "CdFilialAssociada",
      label: "CdFilialAssociada",
      name: "CdFilialAssociada",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "CdVendedorExtra",
      label: "CdVendedorExtra",
      name: "CdVendedorExtra",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "NotadeComplemento",
      label: "NotadeComplemento",
      name: "nota_complemento",
      typeField: "string",
      size: 1,
    },
    {
      field: "VlTroco",
      label: "VlTroco",
      name: "valor_troco",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlBaseCalculoIRRF",
      label: "VlBaseCalculoIRRF",
      name: "VlBaseCalculoIRRF",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "PercAliqIRRF",
      label: "PercAliqIRRF",
      name: "PercAliqIRRF",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlBaseCalculoIN381",
      label: "VlBaseCalculoIN381",
      name: "VlBaseCalculoIN381",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "PercAliqIN381",
      label: "PercAliqIN381",
      name: "PercAliqIN381",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlIN381",
      label: "VlIN381",
      name: "VlIN381",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "PercParticipPrazo",
      label: "PercParticipPrazo",
      name: "PercParticipPrazo",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "PercParticipVista",
      label: "PercParticipVista",
      name: "PercParticipVista",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "RedutorComissao",
      label: "RedutorComissao",
      name: "RedutorComissao",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "GrupoFiscal",
      label: "GrupoFiscal",
      name: "GrupoFiscal",
      typeField: "int",
      size: 2,
    },
    {
      field: "CdTipoVenda",
      label: "CdTipoVenda",
      name: "tipo_venda_id",
      typeField: "int",
      size: 2,
    },
    {
      field: "CdFuncionario",
      label: "CdFuncionario",
      name: "funcionario_id",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "CdUsuario",
      label: "CdUsuario",
      name: "usuario_id",
      typeField: "string",
      size: 10,
    },
    {
      field: "Nop",
      label: "Nop",
      name: "cfop",
      typeField: "int",
      size: 4,
    },
    {
      field: "NopFiscal",
      label: "NopFiscal",
      name: "cfop_fiscal",
      typeField: "int",
      size: 4,
    },
    {
      field: "VlImpostoDiferido",
      label: "VlImpostoDiferido",
      name: "VlImpostoDiferido",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "CdLocalEstoque",
      label: "CdLocalEstoque",
      name: "CdLocalEstoque",
      typeField: "float",
      size: 8,
      scale: 4,
    },

    {
      field: "VlIPIFrete",
      label: "VlIPIFrete",
      name: "VlIPIFrete",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlBaseCalculoII",
      label: "VlBaseCalculoII",
      name: "VlBaseCalculoII",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlII",
      label: "VlII",
      name: "VlII",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "DtSaida",
      label: "DtSaida",
      name: "DtSaida",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "VlBaseCalculoIPI",
      label: "VlBaseCalculoIPI",
      name: "VlBaseCalculoIPI",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlPISSubstituido",
      label: "VlPISSubstituido",
      name: "VlPISSubstituido",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlCofinsSubstituido",
      label: "VlCofinsSubstituido",
      name: "VlCofinsSubstituido",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlBaseCalculoPIS",
      label: "VlBaseCalculoPIS",
      name: "VlBaseCalculoPIS",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlPIS",
      label: "VlPIS",
      name: "VlPIS",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlBaseCalculoCOFINS",
      label: "VlBaseCalculoCOFINS",
      name: "VlBaseCalculoCOFINS",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlCofins",
      label: "VlCofins",
      name: "VlCofins",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlAproximadoImpostoNota",
      label: "VlAproximadoImpostoNota",
      name: "VlAproximadoImpostoNota",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "CdSituacaoDocumento",
      label: "CdSituacaoDocumento",
      name: "CdSituacaoDocumento",
      typeField: "string",
      size: 2,
    },
    {
      field: "SerieNotaOrigem",
      label: "SerieNotaOrigem",
      name: "SerieNotaOrigem",
      typeField: "string",
      size: 3,
    },
    {
      field: "ModeloNotaOrigem",
      label: "ModeloNotaOrigem",
      name: "ModeloNotaOrigem",
      typeField: "string",
      size: 3,
    },
    {
      field: "VlDeducaoFiscal",
      label: "VlDeducaoFiscal",
      name: "VlDeducaoFiscal",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "DescricaoNop",
      label: "DescricaoNop",
      name: "DescricaoNop",
      typeField: "string",
      size: 32,
    },
    {
      field: "TipoNota",
      label: "TipoNota",
      name: "tipoNota",
      typeField: "string",
      size: 1,
    },
    {
      field: "IndicadorFormaPgto",
      label: "IndicadorFormaPgto",
      name: "IndicadorFormaPgto",
      typeField: "int",
      size: 2,
    },
    {
      field: "FinalidadeNf",
      label: "FinalidadeNf",
      name: "FinalidadeNf",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgVendaConsumidor",
      label: "FgVendaConsumidor",
      name: "eh_venda_consumidor",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgDiferencialAliquota",
      label: "FgDiferencialAliquota",
      name: "eh_diferencial_aliquota",
      typeField: "string",
      size: 1,
    },
    {
      field: "SituacaoNfe",
      label: "SituacaoNfe",
      name: "SituacaoNfe",
      typeField: "string",
      size: 16,
      allowNull: false,
    },
    {
      field: "AmbienteNfe",
      label: "AmbienteNfe",
      name: "AmbienteNfe",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumOrdemFaturamento",
      label: "NumOrdemFaturamento",
      name: "NumOrdemFaturamento",
      typeField: "int",
      size: 5,
    },
    {
      field: "FgImportacao",
      label: "FgImportacao",
      name: "eh_importacao",
      typeField: "string",
      size: 1,
    },
    {
      field: "IndicadorPresenca",
      label: "IndicadorPresenca",
      name: "IndicadorPresenca",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgNfTerceiros",
      label: "FgNfTerceiros",
      name: "eh_nf_terceiro",
      typeField: "string",
      size: 1,
    },
    {
      field: "VlAproximadoImpostoFederal",
      label: "VlAproximadoImpostoFederal",
      name: "VlAproximadoImpostoFederal",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlAproximadoImpostoEstadual",
      label: "VlAproximadoImpostoEstadual",
      name: "VlAproximadoImpostoEstadual",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlAproximadoImpostoMunicipal",
      label: "VlAproximadoImpostoMunicipal",
      name: "VlAproximadoImpostoMunicipal",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlFCP",
      label: "VlFCP",
      name: "VlFCP",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlFCPST",
      label: "VlFCPST",
      name: "VlFCPST",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "NomeAdquirente",
      label: "NomeAdquirente",
      name: "NomeAdquirente",
      typeField: "string",
      size: 256,
    },
    {
      field: "CPFCNPJAdquirente",
      label: "CPFCNPJAdquirente",
      name: "CPFCNPJAdquirente",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "percComissao",
      label: "percComissao",
      name: "percComissao",
      typeField: "float",
      size: 8,
    },
  ],
};
