### Index
GET http://localhost:3000/api/rpc?rpc={"jsonrpc":"2.0","id":"2","method":"index","params":"nfSaida"}

### Transferencia Diario
GET http://localhost:3000/api/rpc?rpc={"jsonrpc":"2.0","id":"1","method":"nfSaidaTransferenciaDiario","params":{"inicio":"2022-10-01", "fim":"2022-10-20"}}

### Transferencia Mensal
GET http://localhost:3000/api/rpc?rpc={"jsonrpc":"2.0","id":"1","method":"nfSaidaTransferenciaMensal","params":{"mes":"2022-10"}}

### Transferencia Modelo
GET http://localhost:3000/api/rpc?rpc={"jsonrpc":"2.0","id":"1","method":"nfSaidaTransferenciaModelo","params":{"data":"2022-10-10"}}

### VendaMensalCliente
GET http://localhost:3000/api/rpc?rpc={"jsonrpc":"2.0","id":"1","method":"nfSaidaVendaMensalCliente","params":{"inicio":"2022-01-01", "fim":"2022-10-20","cliente":"189"}}

### VendaDiario
GET http://localhost:3000/api/rpc?rpc={"jsonrpc":"2.0","id":"1","method":"nfSaidaVendaDiario","params":{"inicio":"2022-01-01", "fim":"2022-10-20","uf":["MG"]}}

### Venda Analitico
GET http://localhost:3000/api/rpc?rpc={"jsonrpc":"2.0","id":"2","method":"nfSaidaVendaAnalitico","params":{"inicio":"2021-12-10","fim":"2021-12-20"}}

### Venda Mensal
GET http://localhost:3000/api/rpc?rpc={"jsonrpc":"2.0","id":"2","method":"nfSaidaVendaAnalitico","params":{"inicio":"2021-12-10","fim":"2021-12-20"}}
