### Index
GET http://localhost:3333/api/rpc?rpc={"jsonrpc":"2.0","id":"1","method":"index"}

### Index
GET http://localhost:3333/api/rpc?rpc={"jsonrpc":"2.0","id":"1","method":"esterilizacaoExternaSchemaDiario","params":{"table":"group"}}

### Index
GET http://localhost:3000/api/rpc
?rpc={"jsonrpc":"2.0","id":"1","method":"groupSubjectRead","params":{"id":{"group_id":"dev","subject_id":"/sistema/usuario"}}}

### Index
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"crudRead",
  "params":{"table":"cliente","id":{"cliente_id":1}}
}

### Index
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"vendaMensal",
  "params":{"cliente":189, "inicio":"2021-11-01", "fim":"2022-10-31"}
}

### Index
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"189",
  "method":"vendaDiario",
  "params":{"uf":["MG"], "inicio":"2021-11-01", "fim":"2022-10-31"}
}

### Login
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"189",
  "method":"login",
  "params":{"user":"elias", "password":"jkl"}
}

### Index
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"189",
  "method":"transferenciaMensal",
  "params":{"mes":"2022-06"}
}
