@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}

### Index
GET {{host}}/api/rpc
?rpc={"jsonrpc":"2.0","id":"1","method":"help"}

### Index
GET {{host}}/api/rpc
?rpc={"jsonrpc":"2.0","id":"1","method":"help", "params":"esterilizacaoInterna"}

### Echo
POST {{host}}/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"echoRequest",
  "params":{
    "inicio":"2020-01-01",
    "fim":"2020-01-31",
    "operacao": "1010"
  }
}

### Echo
GET {{host}}/api/rpc
?rpc={  "jsonrpc":"2.0","id":"1","method":"echoRequest","params":{"inicio":"2020-01-01","fim":"2020-01-31","operacao": "1020"}}

### agendaTelefoneSchema
GET {{host}}/api/rpc
?rpc={"jsonrpc":"2.0","id":"1","method":"esterilizacaoInternaSchema"}