### agendaTelefoneSchema
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"crudSchema",
  "params":{"table":"agenda_telefone"}
}

### agendaTelefoneRead
POST http://localhost:3000/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "crudRead",
  "params": {"table":"agenda_telefone","id": {"agenda_telefone_id":"171"}}
}

### agendaTelefoneList
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "crudList",
  "params": {
    "table":"agenda_telefone",
    "where": [["agenda_telefone_id","<=","171"]],
    "order":[["agenda_telefone_id","desc"]]
  }
}

### agendaTelefoneCreate
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "agendaTelefoneCreate",
  "params":  {"data":{
      "agenda_telefone_id": 99,
      "nome": "vago78",
      "setor": "qualidade",
      "email": " vago"
    }}
}

### agendaTelefoneUpdate
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "agendaTelefoneUpdate",
  "params": {"pk": {"agenda_telefone_id":"99"}, "data":{"nome":"Fulano"}}
}

### agendaTelefoneDelete
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "agendaTelefoneDel",
  "params": {"pk": {"agenda_telefone_id":"99"}}
}
