### Schema
POST http://localhost:3000/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"crudSchema",
  "params":{"table":"cliente"}
}

### List
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"clienteList",
  "params":{
    "limit":3,
    "where":[["CdCliente","<=","10"]],
    "orderBy":[["CdCliente","desc"]]
  }
}

### Read
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"clienteRead",
  "params":{
    "id":["10"]
  }
}
