### List
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"groupSubjectList",
  "params":{
  }
}

### Read
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":1,
  "method":"groupSubjectRead",
  "params":{
    "id":["dev", "/sistema/permissao"]
  }
}
