import { TTable } from "../../types";

export const nf_entrada_item: TTable = {
  database: "plano",
  table: "NFItem",
  fields: [
    {
      field: "CdEmpresa",
      label: "Filial",
      name: "filial_id",
      primaryKey: true,
      typeField: "int",
    },
    {
      field: "NroNF",
      label: "Nota",
      name: "nota_id",
      primaryKey: true,
      typeField: "int",
    },
    {
      field: "Serie",
      label: "Serie",
      name: "serie_id",
      primaryKey: true,
      typeField: "string",
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "modelo_id",
      primaryKey: true,
      typeField: "string",
    },
    //------
    {
      field: "CdFornecedor",
      label: "Cód Fornecedor",
      name: "fornecedor_id",
      typeField: "int",
    },
    {
      field: "CdProduto",
      label: "Cód Produto",
      name: "produto_plano_id",
      typeField: "string",
    },
    {
      field: "FgCusto",
      label: "Custo",
      name: "is_custo",
      typeField: "string",
    },
    {
      field: "FgEtiqueta",
      label: "Etiqueta",
      name: "is_etiqueta",
      typeField: "string",
    },
    {
      field: "PercIcms",
      label: "ICMS %",
      name: "percentual_icms",
      typeField: "float",
    },
    {
      field: "PercIpi",
      label: "IPI %",
      name: "percentual_ipi",
      typeField: "float",
    },
    {
      field: "Quantidade",
      label: "Quantidade",
      name: "quantidade",
      typeField: "int",
    },
    {
      field: "TipoMovimentacao",
      label: "Movimentação",
      name: "movimentacao",
      typeField: "string",
    },
    {
      field: "VlAcrescItem",
      label: "Vlr Acréscimo",
      name: "valor_acrescimo",
      typeField: "float",
    },
    {
      field: "VlDescItem",
      label: "Vlr Desconto",
      name: "valor_desconto",
      typeField: "float",
    },
    {
      field: "VlrIcms",
      label: "Vlr ICMS",
      name: "valor_icms",
      typeField: "float",
    },
    {
      field: "VlrIpi",
      label: "Vlr IPI",
      name: "valor_ipi",
      typeField: "float",
    },
    {
      field: "VlTotItem",
      label: "Total Total",
      name: "valor_total",
      typeField: "float",
    },
    {
      field: "TipoTributacao",
      label: "Tributação",
      name: "tipo_tributacao",
      typeField: "string",
    },
    {
      field: "VlBaseSub",
      label: "Vlr Base Substituição",
      name: "valor_base_substituicao",
      typeField: "float",
    },
    {
      field: "VlIcmsSub",
      label: "Vlr ICMS Substituição",
      name: "valor_icms_substituicao",
      typeField: "float",
    },
    {
      field: "DtEntr",
      label: "Data Entrada",
      name: "data_entrada",
      typeField: "string",
    },
    {
      field: "FgEstoque",
      label: "Estoque",
      name: "is_estoque",
      typeField: "string",
    },
    {
      field: "VlRepasseICMSItem",
      label: "Vlr Repasse ICMS",
      name: "valor_repasse_icms",
      typeField: "float",
    },
    {
      field: "FgICMSJaRecolhido",
      label: "ICMS Recolhido",
      name: "is_icms_recolhido",
      typeField: "string",
    },
    {
      field: "PrecPMC",
      label: "Grupo",
      name: "preco_pmc",
      typeField: "float",
    },
    {
      field: "VlRelacionado",
      label: "Recurso",
      name: "valor_relacionado",
      typeField: "float",
    },
    {
      field: "FgCompoeBaseSub",
      label: "Compoe base substituicao",
      name: "is_compoe_base_substituicao",
      typeField: "string",
    },
    {
      field: "Nop",
      label: "CFOP",
      name: "cfop",
      typeField: "int",
    },
    {
      field: "NopFiscalItem",
      label: "Grupo",
      name: "cfop_fiscal_item",
      typeField: "int",
    },
    {
      field: "VlBaseCalculoICMS",
      label: "Recurso",
      name: "valor_base_calculo_icms",
      typeField: "float",
    },
    {
      field: "VlBrutoUnitario",
      label: "Grupo",
      name: "valor_bruto_unitario",
      typeField: "float",
    },
    {
      field: "VlLiquidoUnitario",
      label: "Recurso",
      name: "valor_liquido_unitario",
      typeField: "float",
    },
    {
      field: "CdBaseCalculoCreditoPISCOFINS",
      label: "Grupo",
      name: "base_calculo_credito_pis_cofins",
      typeField: "int",
      allowNull: false,
    },
    {
      field: "CdTipoCreditoPISCOFINS",
      label: "Recurso",
      name: "tipo_credito_pis_cofins",
      typeField: "int",
      allowNull: false,
    },
    {
      field: "CdContribuicaoApuradaPISCOFINS",
      label: "Grupo",
      name: "contribuicao_apurada_pis_cofins",
      typeField: "int",
      allowNull: false,
    },
    {
      field: "Sequencia",
      label: "Sequência",
      name: "sequencia",
      typeField: "int",
      allowNull: false,
    },
    {
      field: "VlBaseCalculoIPI",
      label: "Base Calculo IPI",
      name: "valor_base_calculo_ipi",
      typeField: "float",
    },
    {
      field: "FgConferido",
      label: "Conferido",
      name: "is_conferido",
      typeField: "string",
    },
  ],
};
