import { Schema } from "../schemas.type";

export const LancDiversosClasse: Schema =
  {
  "database": "plano",
  "table": "LancDiversosClasse",
  "primary": [],
  "fields": {
    "CdEmpresa": {
      "table": "LancDiversosClasse",
      "name": "CdEmpresa",
      "data_type": "numeric",
      "max_length": 9,
      "numeric_precision": 14,
      "numeric_scale": null,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "CdBanco": {
      "table": "LancDiversosClasse",
      "name": "CdBanco",
      "data_type": "numeric",
      "max_length": 5,
      "numeric_precision": 4,
      "numeric_scale": null,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "CdAgencia": {
      "table": "LancDiversosClasse",
      "name": "CdAgencia",
      "data_type": "varchar",
      "max_length": 12,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "NumConta": {
      "table": "LancDiversosClasse",
      "name": "NumConta",
      "data_type": "varchar",
      "max_length": 12,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "DtBase": {
      "table": "LancDiversosClasse",
      "name": "DtBase",
      "data_type": "datetime",
      "max_length": 8,
      "numeric_precision": 23,
      "numeric_scale": 3,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "NumLcto": {
      "table": "LancDiversosClasse",
      "name": "NumLcto",
      "data_type": "numeric",
      "max_length": 5,
      "numeric_precision": 5,
      "numeric_scale": null,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "NumContaClasse": {
      "table": "LancDiversosClasse",
      "name": "NumContaClasse",
      "data_type": "numeric",
      "max_length": 9,
      "numeric_precision": 17,
      "numeric_scale": null,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "Percentual": {
      "table": "LancDiversosClasse",
      "name": "Percentual",
      "data_type": "numeric",
      "max_length": 5,
      "numeric_precision": 5,
      "numeric_scale": 2,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    }
  }
}
