import { Schema } from "../schemas.type";

export const ProdutoLenteContato: Schema =
  {
  "database": "plano",
  "table": "ProdutoLenteContato",
  "primary": [
    "CdProduto"
  ],
  "fields": {
    "CdProduto": {
      "table": "ProdutoLenteContato",
      "name": "CdProduto",
      "data_type": "varchar",
      "max_length": 16,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": true,
      "is_unique": true,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "Dioptria": {
      "table": "ProdutoLenteContato",
      "name": "Dioptria",
      "data_type": "numeric",
      "max_length": 5,
      "numeric_precision": 7,
      "numeric_scale": 2,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "Raio1": {
      "table": "ProdutoLenteContato",
      "name": "Raio1",
      "data_type": "numeric",
      "max_length": 5,
      "numeric_precision": 7,
      "numeric_scale": 2,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "Raio2": {
      "table": "ProdutoLenteContato",
      "name": "Raio2",
      "data_type": "numeric",
      "max_length": 5,
      "numeric_precision": 7,
      "numeric_scale": 2,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "Espessura": {
      "table": "ProdutoLenteContato",
      "name": "Espessura",
      "data_type": "numeric",
      "max_length": 5,
      "numeric_precision": 7,
      "numeric_scale": 2,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "EspessuraMinima": {
      "table": "ProdutoLenteContato",
      "name": "EspessuraMinima",
      "data_type": "numeric",
      "max_length": 5,
      "numeric_precision": 7,
      "numeric_scale": 2,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "EspessuraMaxima": {
      "table": "ProdutoLenteContato",
      "name": "EspessuraMaxima",
      "data_type": "numeric",
      "max_length": 5,
      "numeric_precision": 7,
      "numeric_scale": 2,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "BLFNominal": {
      "table": "ProdutoLenteContato",
      "name": "BLFNominal",
      "data_type": "numeric",
      "max_length": 5,
      "numeric_precision": 7,
      "numeric_scale": 2,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "BLFMinimo": {
      "table": "ProdutoLenteContato",
      "name": "BLFMinimo",
      "data_type": "numeric",
      "max_length": 5,
      "numeric_precision": 7,
      "numeric_scale": 2,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "BLFMaximo": {
      "table": "ProdutoLenteContato",
      "name": "BLFMaximo",
      "data_type": "numeric",
      "max_length": 5,
      "numeric_precision": 7,
      "numeric_scale": 2,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    }
  }
}
