### Index
GET http://localhost:3000/api/rpc?rpc={"jsonrpc":"2.0","id":"2","method":"index","params":"log"}


### Login
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"login",
  "params":{
    "user":"elias",
    "password":"jkl"
  }
}

### Logout
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"logout",
  "params":{}
}

### Me
GET http://localhost:3000/api/rpc?rpc={"jsonrpc":"2.0","id":"2","method":"me"}
