@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}

### Index
GET {{host}}/api/rpc?rpc={"jsonrpc":"2.0","id":"2","method":"index","params":"usuario"}

### Me
GET {{host}}/api/rpc?rpc={"jsonrpc":"2.0","id":"2","method":"usuarioMe"}

### Login
POST {{host}}/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"usuarioLogin",
  "params":{
    "user":"user",
    "password":"123"
  }
}

### Logout
POST {{host}}/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"usuarioLogout",
  "params":{}
}

### Me
GET http://localhost:3000/api/rpc?rpc={"jsonrpc":"2.0","id":"2","method":"me"}
