###
POST http://localhost:3000/api/rpc2
Content-Type: application/json

{
  "jsonrpc": "2.0",
	"method": "sys_list",
	"id": "1"
}

###
GET http://localhost:3000/api/system

###
POST http://localhost:3000/api/rpc2
Content-Type: application/json

{
  "jsonrpc": "2.0",
	"method": "usuario_list",
  "params": {},
	"id": "1"
}
