### Where
POST http://localhost:3000/api/knex/sql/oftalmo
Content-Type: application/json

{
  "from":[["table"]],
  "where":[["id",">=",2]],
  "whereNot":[["id","=",2]],
  "whereIn":[["id",[1,2]]],
  "whereNotIn":[["id",[1,2]]],
  "whereNull":[["id"]],
  "whereNotNull":[["id"]],
  "whereBetween":[["id",[1,2]]],
  "whereNotBetween":[["id",[1,2]]],
  "whereRaw":[["id = ?", [1]]],
  "whereLike":[["id", "%mail%"]]
}

### Join
POST http://localhost:3000/api/knex/sql/oftalmo
Content-Type: application/json

{
  "from":[["table1"]],
  "join":[
    ["table2", "table1.id","=", "table2.id"],
    ["table3", "table1.id","=", "table3.id"]
  ]
}

###
join('contacts', 'users.id', '=', 'contacts.user_id') => {join:[['contacts', 'users.id', '=', 'contacts.user_id']]}
joinRaw('id = ?', [1]) => {joinRaw:[['id = ?', [1]]]}

## Having

having(column, operator, value) => {having:[[column, operator, value]]
