### Index
GET http://localhost:3000/api/rpc?rpc={"jsonrpc":"2.0","id":"2","method":"index","params":"ordemProducao"}


### list()
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"list()",
  "params":{
    "limit":20,
    "orderBy":[["kOp","desc"]]
  }
}

### read()
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"read()",
  "params":{
    "id":["18525300"]
  }
}

### ProdutoItem
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"ordemProducaoProdutoItem",
  "params":{
    "id":["18525300"]
  }
}

### ProdutoItem
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"ordemProducaoProdutoItem",
  "params":{
    "id":["18525300"]
  }
}

### Produto
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"ordemProducaoProduto",
  "params":{
    "id":["18525300"]
  }
}

### ProdutoPlano
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"ordemProducaoProdutoPlano",
  "params":{
    "id":["18525300"]
  }
}

### ProducaoDataFabricao
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"ordemProducaoDataFabricacao",
  "params":{
    "id":["18523400"]
  }
}
### ProducaoDataValidade
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"ordemProducaoDataValidade",
  "params":{
    "id":["18523400"]
  }
}

### ProducaoDataFabricao
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"ordemProducaoControle",
  "params":{
    "serie":1,
    "id":["17681000"]
  }
}
