@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}



### usuario_login
# @name login
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id": "1",
  "method": "usuario_login",
  "params":{"user":"elias","password":"jkl"}
}

### usuario_me
POST {{host}}/api/rpc2
Content-Type: application/json
Authorization: Bearer {{login.response.body.result.token}}

{
  "jsonrpc":"2.0",
  "method": "usuario_me",
  "id": "1"
}

### usuario_list
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "method": "usuario_list",
  "id": "1"
}
