### clienteClear
GET http://localhost:3000/api/rpc
?rpc={"jsonrpc":"2.0","id":"1","method":"clienteClear"}

### clienteSchema
GET http://localhost:3000/api/rpc
?rpc={"jsonrpc":"2.0","id":"1","method":"clienteSchema"}

### read()
GET http://localhost:3000/api/rpc
?rpc={"jsonrpc":"2.0","id":"1","method":"read()","params": {"id": {"agenda_telefone_id":"171"}}}



### list()
GET http://localhost:3000/api/rpc
?rpc={"jsonrpc":"2.0","id":"1","method":"list()","params":{"where": [["agenda_telefone_id","<=","171"]],"order":[["agenda_telefone_id","desc"]]}}

### clienteCreate
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "clienteCreate",
  "params":  {"data":{
      "agenda_telefone_id": 99,
      "nome": "vago78",
      "setor": "qualidade",
      "email": " vago"
    }}
}

### clienteUpdate
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "clienteUpdate",
  "params": {"id": {"agenda_telefone_id":"99"}, "data":{"nome":"Fulano"}}
}

### clienteDelete
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "clienteDel",
  "params": {"id": {"agenda_telefone_id":"99"}}
}

### read()
GET http://localhost:3000/api/rpc
?rpc={"jsonrpc":"2.0","id":"1","method":"read()","params": {"id": {"agenda_telefone_id":"99"}}}
