@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}


### LIST
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "method": "agendaTelefone_list",
  "params": {"where":[["id","<",102]]},
  "id": "1",
  "jsonrpc":"2.0"
}

### CREATE RETURNING
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "method": "agendaTelefone_create",
  "params": {"data": {"id":99,"nome":"fulano","setor":"dev","email":"fulano@mail.com"},"returning":["id","nome"]},
  "id": "1",
  "jsonrpc":"2.0"
}


### READ
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "method": "agendaTelefone_read",
  "params": {"where":[["id",99]]},
  "id": "1",
  "jsonrpc":"2.0"
}

### UPDATE
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "method": "agendaTelefone_update",
  "params": {"where": [["id",99]],"data": {"nome":"cicrano"},"returning":["nome"]},
  "id": "1",
  "jsonrpc":"2.0"
}

### DELETE
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "method": "agendaTelefone_del",
  "params": {"where": [["id",99]]},
  "id": "1",
  "jsonrpc":"2.0"
}

### CREATE
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "method": "agendaTelefone_create",
  "params": {"data": {"id":99,"nome":"fulano","setor":"dev","email":"fulano@mail.com"}},
  "id": "1",
  "jsonrpc":"2.0"
}
