@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}

### LIST
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "method": "agendaTelefone_list",
  "params": {"where":[["id",182]]},
  "id": "1",
  "jsonrpc":"2.0"
}

### READ
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "method": "agendaTelefone_read",
  "params": {"where":[["id",182]]},
  "id": "1",
  "jsonrpc":"2.0"
}
