@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}


### ordemProducaoOperacao/produto
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "method": "cliente_list",
  "params": {"where":[["id",3331]]},
  "id": "1",
  "jsonrpc":"2.0"
}

### ordemProducaoOperacao/produto
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "method": "cliente_vendaMensalQuantidade",
  "params": {
      "inicio": "2021-01-01",
      "fim": "2021-01-31",
      "cliente": 3331
    },
  "id": "3331",
  "jsonrpc":"2.0"
}
