@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}
@resource = agendaTelefone


###
POST {{host}}/api/rpc
Content-Type: application/json

{
  "method": "nfSaida/list",
  "args": [
    {
      "select":["CdFilial","NumNota", "CdCliente","CdVendedor"],
      "orderBy":[["DtEmissao","desc"]],
      "limit":5,
      "include":{
        "cliente":["*"],
        "itens":["VlTotal","Quantidade"],
        "itens.produto":["Descricao"]
      }
    }
  ],
  "id": "1"
}

###
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "method": "nfSaida_vendaDiario",
  "params": {
      "inicio": "2024-01-01",
      "fim": "2024-02-05",
      "uf": []
    },
  "id": "1"
}

###
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "method": "nfSaida_transferenciaDiario",
  "params": {
      "inicio": "2022-01-01",
      "fim": "2022-02-05"
    },
  "id": "1"
}

###
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "method": "nfSaida_vendaMensalCliente",
  "params": {
      "inicio": "2024-01-01",
      "fim": "2024-02-05",
      "cliente":
    },
  "id": "1"
}
