@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}
@resource = nfSaidaLote


###
POST {{host}}/api/rpc
Content-Type: application/json

{
  "method": "{{resource}}/list",
  "args": [
    {
      "limit":10,
      "orderBy":[["NumLote","desc"]],
      "select":["CdFilial","NumNota","DtEmissao","CdProduto","NumLote"],
      "include":{
        "produto":["Descricao","CdFabricante"],
        "nfSaida":["CdCliente"],
        "nfSaida.cliente":["RzSocial","Uf"]
      }
    }
  ],
  "id": "1"
}

###
POST {{host}}/api/rpc
Content-Type: application/json

{
  "method": "{{resource}}/list",
  "args": [
  {
    "include": {
      "nfSaida": [
        "CdCliente",
        "Tipo"
      ],
      "nfSaida.cliente": [
        "RzSocial",
        "Uf"
      ],
      "produto": [
        "Descricao"
      ]
    },
    "orderBy": [
      [
        "NumLote",
        "desc"
      ]
    ],
    "select": [
      "CdFilial",
      "NumNota",
      "DtEmissao",
      "CdProduto",
      "NumLote",
      "Sequencia"
    ],
    "where": [
      [
        "NumLote",
        "like",
        "1999%"
      ]
    ]
  }
],
  "id": "1"
}
