import { Schema } from "../schemas.type";

export const tbl_Seguranca_Permissao_Usuario: Schema =
  {
  "database": "oftalmo",
  "table": "tbl_Seguranca_Permissao_Usuario",
  "primary": [],
  "fields": {
    "kPermissao": {
      "table": "tbl_Seguranca_Permissao_Usuario",
      "name": "kPermissao",
      "data_type": "int",
      "max_length": 4,
      "numeric_precision": 10,
      "numeric_scale": null,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": true,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "fkObjeto": {
      "table": "tbl_Seguranca_Permissao_Usuario",
      "name": "fkObjeto",
      "data_type": "char",
      "max_length": 4,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": "tbl_Sistema_Objeto",
      "foreign_key_column": "kObjeto",
      "is_generated": false,
      "generation_expression": null
    },
    "fkUsuario": {
      "table": "tbl_Seguranca_Permissao_Usuario",
      "name": "fkUsuario",
      "data_type": "int",
      "max_length": 4,
      "numeric_precision": 10,
      "numeric_scale": null,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": "tbl_Seguranca_Usuario",
      "foreign_key_column": "kUsuario",
      "is_generated": false,
      "generation_expression": null
    },
    "Permissao": {
      "table": "tbl_Seguranca_Permissao_Usuario",
      "name": "Permissao",
      "data_type": "tinyint",
      "max_length": 1,
      "numeric_precision": 3,
      "numeric_scale": null,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "actions": {
      "table": "tbl_Seguranca_Permissao_Usuario",
      "name": "actions",
      "data_type": "varchar",
      "max_length": 200,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_nullable": true,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    }
  }
}
