### ([fld1] = 2 and [fld2] = 3)
GET http://localhost:3000/where?q={"fld1":2, "fld2":3}



### ([fld1] = 2 and [fld2] = 3)
GET http://localhost:3000/where?q={"fld1":[2],"fld2":[3]}

### ([fld1] = 2 and [fld2] = 3)
GET http://localhost:3000/where?q={"fld1":["=",2],"fld2":["=",3]}

### (([fld1] = 2) and ([fld2] = 3))
GET http://localhost:3000/where?q={"fld1":[["=",2]], "fld2":[["=",3]]}



### (([fld1] >= 2 and [fld1] <= 3))
GET http://localhost:3000/where?q={"fld1":[[">=",2],["<=",3]]}


### (([fld1] = 2) or ([fld2] = 3))
GET http://localhost:3000/where?q=[{"fld1":2},{"fld2":3}]