@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}

### Contas a Receber 2023 cobradas através de boleto
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id": "1",
  "method": "receber_list",
  "params":{
    "sum":["VlAmortizado as ttl"],
    "where":[
      ["SiglaDoc","BOL"],
      ["DaLiqCanc","between",["2023-01-01","2023-12-31"]]
    ]
  }
}
