### Diario
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"esterilizacaoExternaDiario",
  "params":{
    "inicio":"2020-01-01",
    "fim":"2020-01-31"
  }
}

### Mensal
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"esterilizacaoExternaMensal",
  "params":{
    "mes":"2021-06"
  }
}

### Produto
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"esterilizacaoExternaProduto",
  "params":{
    "data":"2020-01-10"
  }
}

### Modelo
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"esterilizacaoExternaModelo",
  "params":{
    "data":"2020-01-10",
    "produto":"LiteFit"
  }
}
