
### Cria Transferencia Matriz -> Filial
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"transferenciaCreate",
  "params":{
    "controles":["176810000016", "176810000024"]
  }
}

### Exclui Transferencia Matriz -> Filial
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"transferenciaDel",
  "params":{
    "controles":["176810000016", "176810000024"]
  }
}

### Verificar transferencia
POST http://localhost:3000/api/rpc
Content-Type: application/json

[
{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"nfEntradaList",
  "params":{
    "where":[["NroNf","=","17919800"]]
  }
},
{
  "jsonrpc":"2.0",
  "id":"2",
  "method":"nfEntradaItemList",
  "params":{
    "where":[["NroNf","=","17919800"]]
  }
},
{
  "jsonrpc":"2.0",
  "id":"3",
  "method":"produtoControleList",
  "params":{
    "where":[["NumNfEntrada","=","17919800"]]
  }
}
]

### Diario
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"transferenciaDiario",
  "params":{
    "inicio":"2020-01-01",
    "fim":"2020-01-31",
    "transferencia": "1010"
  }
}

### Schema Diario
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"transferenciaSchemaDiario",
  "params":{}
}

### Mensal
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"transferenciaMensal",
  "params":{
    "mes":"2021-04",
    "transferencia": "1010"
  }
}

### Schema Mensal
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"transferenciaSchemaMensal",
  "params":{}
}

### Modelo
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"transferenciaModelo",
  "params":{
    "data":"2020-01-10"
  }
}

### Schema Modelo
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"transferenciaSchemaModelo",
  "params":{}
}



### Transferencia Matriz -< Filial
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"ordemProducaoProdutoItem",
  "params":{
    "id":["185240000"]
  }
}


### Transferencia Matriz -< Filial
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"ordemProducaoDataFabricacao",
  "params":{
    "id":["18523400"]
  }
}


### Transferencia Matriz -< Filial
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"nfEntradaItemList",
  "params":{
    "where":[["NroNf", "=", "18524000"]]
  }
}

### Transferencia Matriz -< Filial
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"nfEntradaDel",
  "params":{
    "id":["1","18524000","XX ","1  "]
  }
}

### Transferencia Matriz -< Filial
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"nfEntradaLogDel",
  "params":{
    "id":["1","18524000","XX ","1  "]
  }
}

### Transferencia Matriz -> Filial
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"nfEntradaItemDel",
  "params":{
    "id":["1","18524000","XX ","1  ","1"]
  }
}
