### Diario
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"transferenciaDiario",
  "params":{
    "inicio":"2020-01-01",
    "fim":"2020-01-31",
    "transferencia": "1010"
  }
}

### Mensal
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"transferenciaMensal",
  "params":{
    "mes":"2021-04",
    "transferencia": "1010"
  }
}

### Modelo
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"transferenciaModelo",
  "params":{
    "data":"2020-01-10"
  }
}
