@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}

### LIST
GET {{host}}/api/trpc/sysResource.list
?input={"sort":{"resource_id":"asc"}}

### READ
GET {{host}}/api/trpc/sysResource.read
?input={"id":{"resource_id":"1"}}

### CREATE
POST {{host}}/api/trpc/sysResource.create
Content-Type: application/json

{"data":{"resource_id":"1", "description":"Teste"}}
