@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}


###
POST {{host}}/api/rpc2
Content-Type: application/json

{
"method": "esterilizacaoExterna_mensal",
  "params": {
      "mes": "2024-01"
    },
  "id": "1",
  "jsonrpc": "2.0"
}

###
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "method": "esterilizacaoExterna_diario",
  "params":     {
      "inicio": "2024-01-23",
      "fim": "2024-01-23"
    },
  "id": "1",
  "jsonrpc": "2.0"
}

###
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "method": "esterilizacaoExterna_produto",
  "params": {"data": "2024-01-23"},
  "id": "1",
  "jsonrpc": "2.0"
}
