@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}

POST {{host}}/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"echo",
  "params":[1,2]
}


### Echo
GET {{host}}/api/rpc?rpc={"jsonrpc":"2.0","id":"2","method":"echo","params":{"inicio":"2020-02-01"}}
