@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}
@resource = agendaTelefone

### List
GET {{host}}/api/trpc/{{resource}}.list?input={"where":[["agenda_telefone_id",">",1]]}

### Read
GET {{host}}/api/trpc/{{resource}}.read?input={"id":{"agenda_telefone_id":"1"}}

### Create
POST {{host}}/api/trpc/{{resource}}Create
Content-Type: application/json

{ "data":{
  "agenda_telefone_id":"77",
  "nome":"fulano"
}}

### update
POST {{host}}/api/trpc/{{resource}}Update
Content-Type: application/json

{ "id":{
    "agenda_telefone_id":77
  },
  "data":{
    "nome":"cicrano"
  }
}

### del
POST {{host}}/api/trpc/{{resource}}Del
Content-Type: application/json

{ "id":{
    "agenda_telefone_id":"77"
  }
}
