@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}
@resource = agendaTelefone


### ordemProducaoOperacao/produto
POST {{host}}/api/rpc
Content-Type: application/json

{
  "method": "sys/list",
  "args": [
    {
      "operacao": "3058",
      "data": "2020-01-01"
    }
  ],
  "id": "1"
}
