@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}
@resource = agendaTelefone


###
POST {{host}}/api/rpc
Content-Type: application/json

{
  "method": "nfSaida/list",
  "args": [
    {
      "select":["CdFilial","NumNota", "CdCliente","CdVendedor"],
      "orderBy":[["DtEmissao","desc"]],
      "limit":5,
      "include":{
        "cliente":["*"],
        "itens":["VlTotal","Quantidade"],
        "itens.produto":["Descricao"]
      }
    }
  ],
  "id": "1"
}

###
POST {{host}}/api/rpc
Content-Type: application/json

{
  "method": "nfSaida/vendaDiario",
  "args": [
    {
      "inicio": "2020-01-16",
      "fim": "2023-10-14",
      "uf": [
        "AC",
        "AL",
        "AM",
        "AP",
        "BA",
        "CE",
        "DF",
        "ES",
        "GO",
        "MA",
        "MG",
        "MS",
        "MT",
        "PA",
        "PB",
        "PE",
        "PI",
        "PR",
        "RJ",
        "RN",
        "RO",
        "RR",
        "RS",
        "SC",
        "SE",
        "SP1",
        "SP2",
        "TO",
        "EX",
        "FV"
      ]
    }
  ],
  "id": "1"
}
