@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}
@resource = agendaTelefone


### ordemProducaoOperacao/produto
POST {{host}}/api/rpc
Content-Type: application/json

{
  "method": "ordemProducaoOperacao/produto",
  "args": [
    {
      "operacao": "3058",
      "data": "2020-01-01"
    }
  ],
  "id": "1"
}

### ordemProducaoOperacao/turno
POST {{host}}/api/rpc
Content-Type: application/json

{
  "method": "ordemProducaoOperacao/turno",
  "args": [
    {
      "operacao": "3058",
      "data": "2020-01-01"
    }
  ],
  "id": "3pv908DvrBhQeI6qCXpt7"
}
