@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}

###
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "method": "nfEntrada_read",
  "params": {
      "where": [
        ["CdEmpresa", 2],
        ["NroNf", "20042017"],
        ["Serie", "XX"],
        ["Modelo", "1"]
      ],
      "select": ["NroNf"]
    },
  "id": "1"
}
