@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}
@resource = agendaTelefone


###
POST {{host}}/api/rpc
Content-Type: application/json

{
  "method": "nfSaida/list",
  "args": [
    {
      "select":["CdFilial","NumNota", "CdCliente","CdVendedor"],
      "orderBy":[["DtEmissao","desc"]],
      "limit":5,
      "include":{
        "cliente":["*"],
        "itens":["VlTotal","Quantidade"],
        "itens.produto":["Descricao"]
      }
    }
  ],
  "id": "1"
}

###
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "method": "nfSaida_vendaDiario",
  "params": {
      "inicio": "2023-10-24",
      "fim": "2024-01-22",
      "uf": []
    },
  "id": "1"
}
