import { TTableDef } from "../../types";

export const pagar: TTableDef = {
  database: "plano",
  table: "ArqDup",
  fields: [
    {
      field: "CdEmpresa",
      label: "CdEmpresa",
      name: "filial_id",
      primaryKey: true,
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumDoc",
      label: "NumDoc",
      name: "doc_id",
      primaryKey: true,
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "CodFor",
      label: "CodFor",
      name: "fornecedor_id",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "SeqDoc",
      label: "SeqDoc",
      name: "item_doc",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "Serie",
      label: "Serie",
      name: "serie",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "DatEmi",
      label: "DatEmi",
      name: "data_emissao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DatVen",
      label: "DatVen",
      name: "data_venda",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DatPag",
      label: "DatPag",
      name: "data_pagamento",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "TipInd",
      label: "TipInd",
      name: "TipInd",
      typeField: "string",
      size: 1,
    },
    {
      field: "Aceite",
      label: "Aceite",
      name: "aceite",
      typeField: "string",
      size: 1,
    },
    {
      field: "NumFat",
      label: "NumFat",
      name: "NumFat",
      typeField: "int",
      size: 4,
    },
    {
      field: "CdBanco",
      label: "CdBanco",
      name: "CdBanco",
      typeField: "int",
      size: 4,
    },
    {
      field: "CdAgencia",
      label: "CdAgencia",
      name: "CdAgencia",
      typeField: "int",
      size: 4,
    },
    {
      field: "NumConta",
      label: "NumConta",
      name: "NumConta",
      typeField: "string",
      size: 12,
    },
    {
      field: "NumCheque",
      label: "NumCheque",
      name: "NumCheque",
      typeField: "int",
      size: 4,
    },
    {
      field: "FgSituacao",
      label: "FgSituacao",
      name: "FgSituacao",
      typeField: "string",
      size: 1,
    },
    {
      field: "DtUltAlteracao",
      label: "DtUltAlteracao",
      name: "DtUltAlteracao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "TpMovimentoBanco",
      label: "TpMovimentoBanco",
      name: "TpMovimentoBanco",
      typeField: "string",
      size: 1,
    },
    {
      field: "NumLancamento",
      label: "NumLancamento",
      name: "NumLancamento",
      typeField: "int",
      size: 4,
    },
    {
      field: "NumNota",
      label: "NumNota",
      name: "NumNota",
      typeField: "int",
      size: 4,
    },
    {
      field: "CdTipoPagamento",
      label: "CdTipoPagamento",
      name: "CdTipoPagamento",
      typeField: "int",
      size: 2,
    },
    {
      field: "CdFontePagamento",
      label: "CdFontePagamento",
      name: "CdFontePagamento",
      typeField: "int",
      size: 2,
    },
    {
      field: "DtLancamento",
      label: "DtLancamento",
      name: "DtLancamento",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "Modelo",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "NumAuxiliar",
      label: "NumAuxiliar",
      name: "NumAuxiliar",
      typeField: "string",
      size: 32,
    },
    {
      field: "VlAmortizado",
      label: "VlAmortizado",
      name: "VlAmortizado",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "PercJuroDiario",
      label: "PercJuroDiario",
      name: "PercJuroDiario",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlMultaAtraso",
      label: "VlMultaAtraso",
      name: "VlMultaAtraso",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlDocumento",
      label: "VlDocumento",
      name: "VlDocumento",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlDeducao",
      label: "VlDeducao",
      name: "VlDeducao",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlAcrescimo",
      label: "VlAcrescimo",
      name: "VlAcrescimo",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlJurosPago",
      label: "VlJurosPago",
      name: "VlJurosPago",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "ObsDocumento",
      label: "ObsDocumento",
      name: "ObsDocumento",
      typeField: "string",
      size: 1024,
    },
    {
      field: "FgTipoCustoDRE",
      label: "FgTipoCustoDRE",
      name: "FgTipoCustoDRE",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
  ],
};
