export type TNfLogConferencia = keyof typeof NfLogConferencia.fields

export const NfLogConferencia = {
  database: 'plano',
  table: 'NfLogConferencia',
  primary: ['NumNota', 'Serie', 'Modelo'],
  fields: {
    CdFilial: {
      table: 'NfLogConferencia',
      name: 'CdFilial',
      data_type: 'money',
      max_length: 8,
      numeric_precision: 19,
      numeric_scale: 4,
      is_nullable: false,
      default_value: null,
      is_primary_key: false,
      is_unique: false,
      has_auto_increment: false,
      foreign_key_table: null,
      foreign_key_column: null,
      is_generated: false,
      generation_expression: null,
    },
    NumNota: {
      table: 'NfLogConferencia',
      name: 'NumNota',
      data_type: 'money',
      max_length: 8,
      numeric_precision: 19,
      numeric_scale: 4,
      is_nullable: false,
      default_value: null,
      is_primary_key: false,
      is_unique: false,
      has_auto_increment: false,
      foreign_key_table: null,
      foreign_key_column: null,
      is_generated: false,
      generation_expression: null,
    },
    Serie: {
      table: 'NfLogConferencia',
      name: 'Serie',
      data_type: 'char',
      max_length: 3,
      numeric_precision: null,
      numeric_scale: null,
      is_nullable: false,
      default_value: null,
      is_primary_key: false,
      is_unique: false,
      has_auto_increment: false,
      foreign_key_table: null,
      foreign_key_column: null,
      is_generated: false,
      generation_expression: null,
    },
    CdFornecedor: {
      table: 'NfLogConferencia',
      name: 'CdFornecedor',
      data_type: 'money',
      max_length: 8,
      numeric_precision: 19,
      numeric_scale: 4,
      is_nullable: false,
      default_value: null,
      is_primary_key: false,
      is_unique: false,
      has_auto_increment: false,
      foreign_key_table: null,
      foreign_key_column: null,
      is_generated: false,
      generation_expression: null,
    },
    Data: {
      table: 'NfLogConferencia',
      name: 'Data',
      data_type: 'datetime',
      max_length: 8,
      numeric_precision: 23,
      numeric_scale: 3,
      is_nullable: false,
      default_value: null,
      is_primary_key: false,
      is_unique: false,
      has_auto_increment: false,
      foreign_key_table: null,
      foreign_key_column: null,
      is_generated: false,
      generation_expression: null,
    },
    Usuario: {
      table: 'NfLogConferencia',
      name: 'Usuario',
      data_type: 'varchar',
      max_length: 32,
      numeric_precision: null,
      numeric_scale: null,
      is_nullable: false,
      default_value: null,
      is_primary_key: false,
      is_unique: false,
      has_auto_increment: false,
      foreign_key_table: null,
      foreign_key_column: null,
      is_generated: false,
      generation_expression: null,
    },
    Operacao: {
      table: 'NfLogConferencia',
      name: 'Operacao',
      data_type: 'varchar',
      max_length: 1024,
      numeric_precision: null,
      numeric_scale: null,
      is_nullable: false,
      default_value: null,
      is_primary_key: false,
      is_unique: false,
      has_auto_increment: false,
      foreign_key_table: null,
      foreign_key_column: null,
      is_generated: false,
      generation_expression: null,
    },
    Modelo: {
      table: 'NfLogConferencia',
      name: 'Modelo',
      data_type: 'char',
      max_length: 3,
      numeric_precision: null,
      numeric_scale: null,
      is_nullable: false,
      default_value: null,
      is_primary_key: false,
      is_unique: false,
      has_auto_increment: false,
      foreign_key_table: null,
      foreign_key_column: null,
      is_generated: false,
      generation_expression: null,
    },
  },
}
