### Index
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"index",
  "params":{}
}

### Echo
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"echo",
  "params":{
    "inicio":"2020-01-01",
    "fim":"2020-01-31",
    "operacao": "1010"
  }
}

### Echo
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"operacaoMensal",
  "params":{
    "mes":"2020-01",
    "operacao": "1010"
  }
}
