@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}
@resource = agendaTelefone


GET {{host}}/api/system

###
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "jsonrpc": "2.0",
	"method": "sys_list",
	"id": "1"
}

### Login
# @name login
POST {{host}}/api/rpc2
Content-Type: application/json

{
  "jsonrpc": "2.0",
	"method": "usuario_login",
  "params": {"user":"elias","password":"jkl"},
	"id": "1"
}

### Me
POST {{host}}/api/rpc2
Content-Type: application/json
Authorization: Bearer {{login.response.body.result.token}}

{
  "jsonrpc": "2.0",
	"method": "usuario_me",
	"id": "1"
}

### Me
POST {{host}}/api/rpc2
Content-Type: application/json
Authorization: Bearer {{login.response.body.result.token}}

{"jsonrpc":"2.0","id":1,"method":"group_list","params":{"orderBy":[["NomeGrupo","asc"]]}}
