@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}

### INDEX
GET {{host}}/api/trpc/usuario.list?input={}

###
# @name LOGIN
POST {{host}}/api/trpc/usuario.login
Content-Type: application/json

{"user":"user","password":"123"}

### ME
GET {{host}}/api/trpc/usuario.me

### LOGOUT
POST {{host}}/api/trpc/usuario.logout

### READ
GET {{host}}/api/trpc/usuario.read?input={"id":{"usuario_id":2}}

### TESTE
GET {{host}}/api/teste
