import { TTable } from "../../types";

export const usuario: TTable = {
  database: "oftalmo",
  table: "tbl_Seguranca_Usuario",
  fields: [
    {
      field: "kUsuario",
      label: "Usuario",
      name: "usuario_id",
      type: "int",
      size: 4,
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      readOnly: true,
    },
    {
      field: "NomeUsuario",
      label: "Login",
      name: "nome_login",
      type: "string",
      size: 50,
      allowNull: false,
    },
    {
      field: "email",
      label: "Email",
      name: "email",
      type: "string",
      size: 50,
    },
    {
      field: "fkFuncionario",
      label: "fkFuncionario",
      name: "empregado_id",
      type: "int",
      size: 4,
      visible: false,
    },
    {
      field: "Ativo",
      label: "Ativo",
      name: "is_ativo",
      type: "int",
      size: 1,
      defaultValue: "1",
    },
    {
      field: "hash",
      label: "Hash",
      name: "hash",
      type: "string",
      size: 255,
      visible: false,
    },
    {
      field: "nome",
      label: "Nome",
      name: "nome",
      type: "string",
      size: 200,
    },
    {
      field: "setor",
      label: "setor",
      name: "setor",
      type: "string",
      size: 50,
      visible: false,
    },
    {
      field: "nivel",
      label: "nivel",
      name: "nivel",
      type: "int",
      size: 4,
      visible: false,
    },
    {
      field: "idGroup",
      label: "Grupo",
      name: "group_id",
      type: "string",
      size: 50,
    },
  ],
};
