### Index
GET http://localhost:3000/api/rpc
?rpc={"jsonrpc":"2.0","id":"1","method":"index","params":"ordemProducao"}

### OP Item
GET http://localhost:3000/api/rpc
?rpc={"jsonrpc":"2.0","id":"1","method":"ordemProducaoEtiquetaExterna","params":{"id":{"kOp":"18818400"}}}
