### Index
GET http://localhost:3000/api/rpc?rpc={"jsonrpc":"2.0","id":"2","method":"index","params":"nfSaida"}

### Venda Analitico
GET http://localhost:3000/api/rpc?rpc={"jsonrpc":"2.0","id":"2","method":"nfSaidaVendaAnalitico","params":{"inicio":"2021-12-10","fim":"2021-12-20"}}

### Venda Mensal
GET http://localhost:3000/api/rpc?rpc={"jsonrpc":"2.0","id":"2","method":"nfSaidaVendaAnalitico","params":{"inicio":"2021-12-10","fim":"2021-12-20"}}


### Diario
POST http://localhost:3000/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"transferenciaDiario",
  "params":{"inicio":"2022-10-01", "fim":"2022-10-20"}
}

### VendaMensal
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"vendaMensal",
  "params":{"inicio":"2022-01-01", "fim":"2022-10-20","cliente":"189"}
}
