@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}

### INDEX
GET {{host}}/api/rpc
?rpc={"jsonrpc":"2.0","id":"2","method":"index","params":"groupSubject"}

### LIST
GET {{host}}/api/trpc/groupSubject.list
?input={"filter":{"group_id":"28"}}

### LISTSubject
GET {{host}}/api/trpc/groupSubject.listPermissions
?input={"group_id":"28","subject_ids":["prm1", "prm2", "prm3", "prm4"]}


### CAN
GET {{host}}/api/trpc/groupSubject.can
?input={"usuario_id":1,"subject_id":"cliente_read"}
