import { TTableDef } from "@mono/types/model";

export const AgendaInteracao: TTableDef = {
  database: "plano",
  table: "AgendaInteracao",
  fields: [
    {
      field: "IdCompromisso",
      label: "IdCompromisso",
      name: "IdCompromisso",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Sequencia",
      label: "Sequencia",
      name: "Sequencia",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "DtInteracaoPrevista",
      label: "DtInteracaoPrevista",
      name: "DtInteracaoPrevista",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "DescricaoInteracaoPrevista",
      label: "DescricaoInteracaoPrevista",
      name: "DescricaoInteracaoPrevista",
      typeField: "string",
      size: 512,
      allowNull: false,
    },
    {
      field: "UsuarioInteracaoPrevista",
      label: "UsuarioInteracaoPrevista",
      name: "UsuarioInteracaoPrevista",
      typeField: "string",
      size: 32,
      allowNull: false,
    },
    {
      field: "TipoInteracaoPrevista",
      label: "TipoInteracaoPrevista",
      name: "TipoInteracaoPrevista",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "DtInteracaoRealizada",
      label: "DtInteracaoRealizada",
      name: "DtInteracaoRealizada",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "DescricaoInteracaoRealizada",
      label: "DescricaoInteracaoRealizada",
      name: "DescricaoInteracaoRealizada",
      typeField: "string",
      size: 512,
      allowNull: false,
    },
    {
      field: "UsuarioInteracaoRealizada",
      label: "UsuarioInteracaoRealizada",
      name: "UsuarioInteracaoRealizada",
      typeField: "string",
      size: 32,
      allowNull: false,
    },
    {
      field: "TipoInteracaoRealizada",
      label: "TipoInteracaoRealizada",
      name: "TipoInteracaoRealizada",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
  ],
};
