import { TTable } from "../../../../types/model";

export const Agenda: TTable = {
  database: "plano",
  table: "Agenda",
  fields: [
    {
      field: "CdUsuario",
      label: "CdUsuario",
      name: "CdUsuario",
      typeField: "string",
      size: 10,
    },
    {
      field: "IdCompromisso",
      label: "IdCompromisso",
      name: "Agenda_id",
      typeField: "int",
      size: 4,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "CdCliente",
      label: "CdCliente",
      name: "CdCliente",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "DtAgendamento",
      label: "DtAgendamento",
      name: "DtAgendamento",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "HrAgendamento",
      label: "HrAgendamento",
      name: "HrAgendamento",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DtAgendada",
      label: "DtAgendada",
      name: "DtAgendada",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "HrAgendado",
      label: "HrAgendado",
      name: "HrAgendado",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DsCompromisso",
      label: "DsCompromisso",
      name: "DsCompromisso",
      typeField: "string",
      size: 1024,
    },
    {
      field: "NmContato",
      label: "NmContato",
      name: "NmContato",
      typeField: "string",
      size: 40,
    },
    {
      field: "FgStatusCompromisso",
      label: "FgStatusCompromisso",
      name: "FgStatusCompromisso",
      typeField: "string",
      size: 1,
    },
    {
      field: "NumPedido",
      label: "NumPedido",
      name: "NumPedido",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "CdRespAgendamento",
      label: "CdRespAgendamento",
      name: "CdRespAgendamento",
      typeField: "string",
      size: 10,
    },
  ],
};
