import { TTable } from "../../../../types/model";

export const AssocFornecedor: TTable = {
  database: "plano",
  table: "AssocFornecedor",
  fields: [
    {
      field: "CdProduto",
      label: "CdProduto",
      name: "CdProduto",
      typeField: "string",
      size: 15,
      allowNull: false,
    },
    {
      field: "CdFornecedor",
      label: "CdFornecedor",
      name: "CdFornecedor",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "CdReferencia",
      label: "CdReferencia",
      name: "CdReferencia",
      typeField: "string",
      size: 32,
    },
    {
      field: "QtdEmbalagem",
      label: "QtdEmbalagem",
      name: "QtdEmbalagem",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "DtPriCompra",
      label: "DtPriCompra",
      name: "DtPriCompra",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DtUltCompra",
      label: "DtUltCompra",
      name: "DtUltCompra",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DtUltAlteracao",
      label: "DtUltAlteracao",
      name: "DtUltAlteracao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "NroNf",
      label: "NroNf",
      name: "NroNf",
      typeField: "int",
      size: 4,
    },
    {
      field: "Serie",
      label: "Serie",
      name: "Serie",
      typeField: "string",
      size: 3,
    },
  ],
};
