import { TTableDef } from "@/types/model";

export const BancoContaCorrenteCedente: TTableDef = {
  database: "plano",
  table: "BancoContaCorrenteCedente",
  fields: [
    {
      field: "NumBanco",
      label: "NumBanco",
      name: "NumBanco",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "NumAgencia",
      label: "NumAgencia",
      name: "NumAgencia",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "NumContaCorrente",
      label: "NumContaCorrente",
      name: "NumContaCorrente",
      typeField: "string",
      size: 16,
      allowNull: false,
    },
    {
      field: "AgCodCedente",
      label: "AgCodCedente",
      name: "AgCodCedente",
      typeField: "string",
      size: 32,
      allowNull: false,
    },
    {
      field: "NmCedente",
      label: "NmCedente",
      name: "NmCedente",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "CNPJ",
      label: "CNPJ",
      name: "CNPJ",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "Endereco",
      label: "Endereco",
      name: "Endereco",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "Numero",
      label: "Numero",
      name: "Numero",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Complemento",
      label: "Complemento",
      name: "Complemento",
      typeField: "string",
      size: 32,
      allowNull: false,
    },
    {
      field: "Bairro",
      label: "Bairro",
      name: "Bairro",
      typeField: "string",
      size: 32,
      allowNull: false,
    },
    {
      field: "Cidade",
      label: "Cidade",
      name: "Cidade",
      typeField: "string",
      size: 32,
      allowNull: false,
    },
    {
      field: "UF",
      label: "UF",
      name: "UF",
      typeField: "string",
      size: 2,
      allowNull: false,
    },
    {
      field: "CEP",
      label: "CEP",
      name: "CEP",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Telefone",
      label: "Telefone",
      name: "Telefone",
      typeField: "string",
      size: 32,
      allowNull: false,
    },
    {
      field: "Fax",
      label: "Fax",
      name: "Fax",
      typeField: "string",
      size: 32,
      allowNull: false,
    },
  ],
};
