import { TTableDef } from "@/types/model";

export const CartaoFidelidadeDebito: TTableDef = {
  database: "plano",
  table: "CartaoFidelidadeDebito",
  fields: [
    {
      field: "CdCliente",
      label: "CdCliente",
      name: "CdCliente",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "Sequencia",
      label: "Sequencia",
      name: "Sequencia",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "CdProduto",
      label: "CdProduto",
      name: "CdProduto",
      typeField: "string",
      size: 15,
      allowNull: false,
    },
    {
      field: "DtMovimentacao",
      label: "DtMovimentacao",
      name: "DtMovimentacao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "Quantidade",
      label: "Quantidade",
      name: "Quantidade",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "PontosMilhagem",
      label: "PontosMilhagem",
      name: "PontosMilhagem",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "Comentarios",
      label: "Comentarios",
      name: "Comentarios",
      typeField: "string",
      size: 80,
      allowNull: false,
    },
  ],
};
