import { TTable } from "../../../../types/model";

export const CondPagto: TTable = {
  database: "plano",
  table: "CondPagto",
  fields: [
    {
      field: "Codigo",
      label: "Codigo",
      name: "CondPagto_id",
      typeField: "int",
      size: 4,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "Descricao",
      label: "Descricao",
      name: "Descricao",
      typeField: "string",
      size: 40,
    },
    {
      field: "Prazo1",
      label: "Prazo1",
      name: "Prazo1",
      typeField: "int",
      size: 4,
    },
    {
      field: "Prazo2",
      label: "Prazo2",
      name: "Prazo2",
      typeField: "int",
      size: 4,
    },
    {
      field: "Prazo3",
      label: "Prazo3",
      name: "Prazo3",
      typeField: "int",
      size: 4,
    },
    {
      field: "Prazo4",
      label: "Prazo4",
      name: "Prazo4",
      typeField: "int",
      size: 4,
    },
    {
      field: "Prazo5",
      label: "Prazo5",
      name: "Prazo5",
      typeField: "int",
      size: 4,
    },
    {
      field: "Prazo6",
      label: "Prazo6",
      name: "Prazo6",
      typeField: "int",
      size: 4,
    },
    {
      field: "AcresFinanceiro",
      label: "AcresFinanceiro",
      name: "AcresFinanceiro",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "FgVista",
      label: "FgVista",
      name: "FgVista",
      typeField: "string",
      size: 1,
    },
    {
      field: "Tipo",
      label: "Tipo",
      name: "Tipo",
      typeField: "string",
      size: 1,
    },
    {
      field: "VlMinimo",
      label: "VlMinimo",
      name: "VlMinimo",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Participacao1",
      label: "Participacao1",
      name: "Participacao1",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Participacao2",
      label: "Participacao2",
      name: "Participacao2",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Participacao3",
      label: "Participacao3",
      name: "Participacao3",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Participacao4",
      label: "Participacao4",
      name: "Participacao4",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Participacao5",
      label: "Participacao5",
      name: "Participacao5",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Participacao6",
      label: "Participacao6",
      name: "Participacao6",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Prazo7",
      label: "Prazo7",
      name: "Prazo7",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Prazo8",
      label: "Prazo8",
      name: "Prazo8",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Prazo9",
      label: "Prazo9",
      name: "Prazo9",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Prazo10",
      label: "Prazo10",
      name: "Prazo10",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Prazo11",
      label: "Prazo11",
      name: "Prazo11",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Prazo12",
      label: "Prazo12",
      name: "Prazo12",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Participacao7",
      label: "Participacao7",
      name: "Participacao7",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Participacao8",
      label: "Participacao8",
      name: "Participacao8",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Participacao9",
      label: "Participacao9",
      name: "Participacao9",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Participacao10",
      label: "Participacao10",
      name: "Participacao10",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Participacao11",
      label: "Participacao11",
      name: "Participacao11",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Participacao12",
      label: "Participacao12",
      name: "Participacao12",
      typeField: "float",
      size: 8,
      scale: 4,
    },
  ],
};
