import { TTableDef } from "@/types/model";

export const ConfiguracaoNFeSe: TTableDef = {
  database: "plano",
  table: "ConfiguracaoNFeSe",
  fields: [
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "ConfiguracaoNFeSe_id",
      typeField: "float",
      size: 8,
      scale: 4,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "VersaoXML",
      label: "VersaoXML",
      name: "VersaoXML",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "Ambiente",
      label: "Ambiente",
      name: "Ambiente",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "CaminhoNfeSe",
      label: "CaminhoNfeSe",
      name: "CaminhoNfeSe",
      typeField: "string",
      size: 512,
      allowNull: false,
    },
    {
      field: "CertificadoNfeSe",
      label: "CertificadoNfeSe",
      name: "CertificadoNfeSe",
      typeField: "string",
      size: 512,
      allowNull: false,
    },
    {
      field: "UsuarioNfeSe",
      label: "UsuarioNfeSe",
      name: "UsuarioNfeSe",
      typeField: "string",
      size: 512,
      allowNull: false,
    },
    {
      field: "SenhaNfeSe",
      label: "SenhaNfeSe",
      name: "SenhaNfeSe",
      typeField: "string",
      size: 512,
      allowNull: false,
    },
    {
      field: "ProxyNfeSe",
      label: "ProxyNfeSe",
      name: "ProxyNfeSe",
      typeField: "string",
      size: 512,
      allowNull: false,
    },
    {
      field: "LicencaNfeSe",
      label: "LicencaNfeSe",
      name: "LicencaNfeSe",
      typeField: "string",
      size: 512,
      allowNull: false,
    },
  ],
};
