import { TTableDef } from "@/types/model";

export const ConfigEtiqRemessaNota: TTableDef = {
  database: "plano",
  table: "ConfigEtiqRemessaNota",
  fields: [
    {
      field: "Impressora",
      label: "Impressora",
      name: "ConfigEtiqRemessaNota_id",
      typeField: "string",

      primaryKey: true,
      allowNull: false,
    },
    {
      field: "CaminhoLogo",
      label: "CaminhoLogo",
      name: "CaminhoLogo",
      typeField: "string",
    },
    {
      field: "Obs",
      label: "Obs",
      name: "Obs",
      typeField: "string",
    },
    {
      field: "LinLogo",
      label: "LinLogo",
      name: "LinLogo",
      typeField: "float",
    },
    {
      field: "ColLogo",
      label: "ColLogo",
      name: "ColLogo",
      typeField: "float",
    },
    {
      field: "LinLbDestinatario",
      label: "LinLbDestinatario",
      name: "LinLbDestinatario",
      typeField: "float",
    },
    {
      field: "ColLbDestinatario",
      label: "ColLbDestinatario",
      name: "ColLbDestinatario",
      typeField: "float",
    },
    {
      field: "LinDestinatario1",
      label: "LinDestinatario1",
      name: "LinDestinatario1",
      typeField: "float",
    },
    {
      field: "ColDestinatario1",
      label: "ColDestinatario1",
      name: "ColDestinatario1",
      typeField: "float",
    },
    {
      field: "LinDestinatario2",
      label: "LinDestinatario2",
      name: "LinDestinatario2",
      typeField: "float",
    },
    {
      field: "ColDestinatario2",
      label: "ColDestinatario2",
      name: "ColDestinatario2",
      typeField: "float",
    },
    {
      field: "LinLbEndereco",
      label: "LinLbEndereco",
      name: "LinLbEndereco",
      typeField: "float",
    },
    {
      field: "ColLbEndereco",
      label: "ColLbEndereco",
      name: "ColLbEndereco",
      typeField: "float",
    },
    {
      field: "LinEndereco1",
      label: "LinEndereco1",
      name: "LinEndereco1",
      typeField: "float",
    },
    {
      field: "ColEndereco1",
      label: "ColEndereco1",
      name: "ColEndereco1",
      typeField: "float",
    },
    {
      field: "LinEndereco2",
      label: "LinEndereco2",
      name: "LinEndereco2",
      typeField: "float",
    },
    {
      field: "ColEndereco2",
      label: "ColEndereco2",
      name: "ColEndereco2",
      typeField: "float",
    },
    {
      field: "LinLbBairro",
      label: "LinLbBairro",
      name: "LinLbBairro",
      typeField: "float",
    },
    {
      field: "ColLbBairro",
      label: "ColLbBairro",
      name: "ColLbBairro",
      typeField: "float",
    },
    {
      field: "LinBairro",
      label: "LinBairro",
      name: "LinBairro",
      typeField: "float",
    },
    {
      field: "ColBairro",
      label: "ColBairro",
      name: "ColBairro",
      typeField: "float",
    },
    {
      field: "LinLbCEP",
      label: "LinLbCEP",
      name: "LinLbCEP",
      typeField: "float",
    },
    {
      field: "ColLbCEP",
      label: "ColLbCEP",
      name: "ColLbCEP",
      typeField: "float",
    },
    {
      field: "LinCEP",
      label: "LinCEP",
      name: "LinCEP",
      typeField: "float",
    },
    {
      field: "ColCEP",
      label: "ColCEP",
      name: "ColCEP",
      typeField: "float",
    },
    {
      field: "LinLbCidade",
      label: "LinLbCidade",
      name: "LinLbCidade",
      typeField: "float",
    },
    {
      field: "ColLbCidade",
      label: "ColLbCidade",
      name: "ColLbCidade",
      typeField: "float",
    },
    {
      field: "LinCidade",
      label: "LinCidade",
      name: "LinCidade",
      typeField: "float",
    },
    {
      field: "ColCidade",
      label: "ColCidade",
      name: "ColCidade",
      typeField: "float",
    },
    {
      field: "LinLbUF",
      label: "LinLbUF",
      name: "LinLbUF",
      typeField: "float",
    },
    {
      field: "ColLbUF",
      label: "ColLbUF",
      name: "ColLbUF",
      typeField: "float",
    },
    {
      field: "LinUF",
      label: "LinUF",
      name: "LinUF",
      typeField: "float",
    },
    {
      field: "ColUF",
      label: "ColUF",
      name: "ColUF",
      typeField: "float",
    },
    {
      field: "LinLbNumNota",
      label: "LinLbNumNota",
      name: "LinLbNumNota",
      typeField: "float",
    },
    {
      field: "ColLbNumNota",
      label: "ColLbNumNota",
      name: "ColLbNumNota",
      typeField: "float",
    },
    {
      field: "LinNumNota",
      label: "LinNumNota",
      name: "LinNumNota",
      typeField: "float",
    },
    {
      field: "ColNumNota",
      label: "ColNumNota",
      name: "ColNumNota",
      typeField: "float",
    },
    {
      field: "LinLbNumVolume",
      label: "LinLbNumVolume",
      name: "LinLbNumVolume",
      typeField: "float",
    },
    {
      field: "ColLbNumVolume",
      label: "ColLbNumVolume",
      name: "ColLbNumVolume",
      typeField: "float",
    },
    {
      field: "LinNumVolume",
      label: "LinNumVolume",
      name: "LinNumVolume",
      typeField: "float",
    },
    {
      field: "ColNumVolume",
      label: "ColNumVolume",
      name: "ColNumVolume",
      typeField: "float",
    },
    {
      field: "LinLbEmitente",
      label: "LinLbEmitente",
      name: "LinLbEmitente",
      typeField: "float",
    },
    {
      field: "ColLbEmitente",
      label: "ColLbEmitente",
      name: "ColLbEmitente",
      typeField: "float",
    },
    {
      field: "LinEmitente1",
      label: "LinEmitente1",
      name: "LinEmitente1",
      typeField: "float",
    },
    {
      field: "ColEmitente1",
      label: "ColEmitente1",
      name: "ColEmitente1",
      typeField: "float",
    },
    {
      field: "LinEmitente2",
      label: "LinEmitente2",
      name: "LinEmitente2",
      typeField: "float",
    },
    {
      field: "ColEmitente2",
      label: "ColEmitente2",
      name: "ColEmitente2",
      typeField: "float",
    },
    {
      field: "LinObs",
      label: "LinObs",
      name: "LinObs",
      typeField: "float",
    },
    {
      field: "ColObs",
      label: "ColObs",
      name: "ColObs",
      typeField: "float",
    },
    {
      field: "QtdColunas",
      label: "QtdColunas",
      name: "QtdColunas",
      typeField: "float",
    },
    {
      field: "QtdLinhas",
      label: "QtdLinhas",
      name: "QtdLinhas",
      typeField: "float",
    },
    {
      field: "EspacoColunas",
      label: "EspacoColunas",
      name: "EspacoColunas",
      typeField: "float",
    },
    {
      field: "EspacoLinhas",
      label: "EspacoLinhas",
      name: "EspacoLinhas",
      typeField: "float",
    },
    {
      field: "ColunaInicial",
      label: "ColunaInicial",
      name: "ColunaInicial",
      typeField: "float",
    },
    {
      field: "LinhaInicial",
      label: "LinhaInicial",
      name: "LinhaInicial",
      typeField: "float",
    },
    {
      field: "FonteCorpoEtiqueta",
      label: "FonteCorpoEtiqueta",
      name: "FonteCorpoEtiqueta",
      typeField: "string",
    },
    {
      field: "FonteEmitente",
      label: "FonteEmitente",
      name: "FonteEmitente",
      typeField: "string",
    },
    {
      field: "FgNegritoCorpo",
      label: "FgNegritoCorpo",
      name: "FgNegritoCorpo",
      typeField: "string",
    },
    {
      field: "FgNegritoEmitente",
      label: "FgNegritoEmitente",
      name: "FgNegritoEmitente",
      typeField: "string",
    },
    {
      field: "FgNegritoObs",
      label: "FgNegritoObs",
      name: "FgNegritoObs",
      typeField: "string",
    },
    {
      field: "FonteObs",
      label: "FonteObs",
      name: "FonteObs",
      typeField: "string",
    },
  ],
};
