import { TTableDef } from "@/types/model";

export const ConfiguracaoNFCeDesconectada: TTableDef = {
  database: "plano",
  table: "ConfiguracaoNFCeDesconectada",
  fields: [
    {
      field: "CdEmpresa",
      label: "CdEmpresa",
      name: "CdEmpresa",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "Estacao",
      label: "Estacao",
      name: "Estacao",
      typeField: "string",
      size: 128,
      allowNull: false,
    },
    {
      field: "DiretorioMovimento",
      label: "DiretorioMovimento",
      name: "DiretorioMovimento",
      typeField: "string",
      size: 128,
      allowNull: false,
    },
    {
      field: "DiretorioResultado",
      label: "DiretorioResultado",
      name: "DiretorioResultado",
      typeField: "string",
      size: 128,
      allowNull: false,
    },
    {
      field: "DiretorioProcNFe",
      label: "DiretorioProcNFe",
      name: "DiretorioProcNFe",
      typeField: "string",
      size: 128,
      allowNull: false,
    },
    {
      field: "RetaguardaServidor",
      label: "RetaguardaServidor",
      name: "RetaguardaServidor",
      typeField: "string",
      size: 128,
      allowNull: false,
    },
    {
      field: "RetaguardaUsuario",
      label: "RetaguardaUsuario",
      name: "RetaguardaUsuario",
      typeField: "string",
      size: 128,
      allowNull: false,
    },
    {
      field: "RetaguardaSenha",
      label: "RetaguardaSenha",
      name: "RetaguardaSenha",
      typeField: "string",
      size: 128,
      allowNull: false,
    },
    {
      field: "RetaguardaBancoDados",
      label: "RetaguardaBancoDados",
      name: "RetaguardaBancoDados",
      typeField: "string",
      size: 128,
      allowNull: false,
    },
    {
      field: "IntervaloSincronizacao",
      label: "IntervaloSincronizacao",
      name: "IntervaloSincronizacao",
      typeField: "string",
      size: 128,
      allowNull: false,
    },
    {
      field: "FgTabelasNotas",
      label: "FgTabelasNotas",
      name: "FgTabelasNotas",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgTabelasCaixa",
      label: "FgTabelasCaixa",
      name: "FgTabelasCaixa",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgTabelaPedidos",
      label: "FgTabelaPedidos",
      name: "FgTabelaPedidos",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgTabelasContasReceber",
      label: "FgTabelasContasReceber",
      name: "FgTabelasContasReceber",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
  ],
};
