import { TTableDef } from "@/types/model";

export const ConfiguracaoEtiquetas: TTableDef = {
  database: "plano",
  table: "ConfiguracaoEtiquetas",
  fields: [
    {
      field: "ModeloEtiqueta",
      label: "ModeloEtiqueta",
      name: "ModeloEtiqueta",
      typeField: "string",

      allowNull: false,
    },
    {
      field: "Impressora",
      label: "Impressora",
      name: "Impressora",
      typeField: "string",

      allowNull: false,
    },
    {
      field: "FgImprimeVlAtacado",
      label: "FgImprimeVlAtacado",
      name: "FgImprimeVlAtacado",
      typeField: "string",
    },
    {
      field: "FgImprimeVlVarejo",
      label: "FgImprimeVlVarejo",
      name: "FgImprimeVlVarejo",
      typeField: "string",
    },
    {
      field: "TipoCodigo",
      label: "TipoCodigo",
      name: "TipoCodigo",
      typeField: "string",
    },
    {
      field: "LinhasPorFolha",
      label: "LinhasPorFolha",
      name: "LinhasPorFolha",
      typeField: "int",
    },
    {
      field: "ColunasPorLinha",
      label: "ColunasPorLinha",
      name: "ColunasPorLinha",
      typeField: "int",
    },
    {
      field: "AlturaEtiqueta",
      label: "AlturaEtiqueta",
      name: "AlturaEtiqueta",
      typeField: "float",
    },
    {
      field: "LarguraEtiqueta",
      label: "LarguraEtiqueta",
      name: "LarguraEtiqueta",
      typeField: "float",
    },
    {
      field: "AlturaCodigoBarras",
      label: "AlturaCodigoBarras",
      name: "AlturaCodigoBarras",
      typeField: "float",
    },
    {
      field: "FatorDeCorrecao",
      label: "FatorDeCorrecao",
      name: "FatorDeCorrecao",
      typeField: "float",
    },
    {
      field: "EspacoSuperior",
      label: "EspacoSuperior",
      name: "EspacoSuperior",
      typeField: "float",
    },
    {
      field: "EspacoLateral",
      label: "EspacoLateral",
      name: "EspacoLateral",
      typeField: "float",
    },
    {
      field: "EspacoAntesDoCodigo",
      label: "EspacoAntesDoCodigo",
      name: "EspacoAntesDoCodigo",
      typeField: "float",
    },
    {
      field: "EspacoEntreColunas",
      label: "EspacoEntreColunas",
      name: "EspacoEntreColunas",
      typeField: "float",
    },
    {
      field: "DeslocamentoCodigo",
      label: "DeslocamentoCodigo",
      name: "DeslocamentoCodigo",
      typeField: "int",
    },
    {
      field: "FonteCodigo",
      label: "FonteCodigo",
      name: "FonteCodigo",
      typeField: "string",
    },
    {
      field: "PosicaoCodigo",
      label: "PosicaoCodigo",
      name: "PosicaoCodigo",
      typeField: "float",
    },
    {
      field: "PosicaoCodigoAdicional",
      label: "PosicaoCodigoAdicional",
      name: "PosicaoCodigoAdicional",
      typeField: "float",
    },
    {
      field: "CaracteresDescricao",
      label: "CaracteresDescricao",
      name: "CaracteresDescricao",
      typeField: "int",
    },
    {
      field: "FonteDescricao",
      label: "FonteDescricao",
      name: "FonteDescricao",
      typeField: "string",
    },
    {
      field: "LinhasDescricao",
      label: "LinhasDescricao",
      name: "LinhasDescricao",
      typeField: "int",
    },
    {
      field: "PosicaoDescricao",
      label: "PosicaoDescricao",
      name: "PosicaoDescricao",
      typeField: "float",
    },
    {
      field: "PosicaoDescricaoAdicional",
      label: "PosicaoDescricaoAdicional",
      name: "PosicaoDescricaoAdicional",
      typeField: "float",
    },
    {
      field: "CorrecaoDescricao",
      label: "CorrecaoDescricao",
      name: "CorrecaoDescricao",
      typeField: "float",
    },
    {
      field: "DeslocamentoPreco",
      label: "DeslocamentoPreco",
      name: "DeslocamentoPreco",
      typeField: "int",
    },
    {
      field: "FontePreco",
      label: "FontePreco",
      name: "FontePreco",
      typeField: "string",
    },
    {
      field: "PosicaoPreco",
      label: "PosicaoPreco",
      name: "PosicaoPreco",
      typeField: "float",
    },
    {
      field: "FgDuasLinhas",
      label: "FgDuasLinhas",
      name: "FgDuasLinhas",
      typeField: "string",
    },
    {
      field: "CaracteresDuasLinhas",
      label: "CaracteresDuasLinhas",
      name: "CaracteresDuasLinhas",
      typeField: "int",
    },
    {
      field: "FonteDuasLinhas",
      label: "FonteDuasLinhas",
      name: "FonteDuasLinhas",
      typeField: "string",
    },
    {
      field: "PosicaoDuasLinhas",
      label: "PosicaoDuasLinhas",
      name: "PosicaoDuasLinhas",
      typeField: "float",
    },
    {
      field: "CorrecaoDuasLinhas",
      label: "CorrecaoDuasLinhas",
      name: "CorrecaoDuasLinhas",
      typeField: "float",
    },
    {
      field: "Mensagem",
      label: "Mensagem",
      name: "Mensagem",
      typeField: "string",
    },
    {
      field: "FonteMensagem",
      label: "FonteMensagem",
      name: "FonteMensagem",
      typeField: "string",
    },
    {
      field: "PosicaoMensagem",
      label: "PosicaoMensagem",
      name: "PosicaoMensagem",
      typeField: "float",
    },
    {
      field: "IdentificacaoEmpresa",
      label: "IdentificacaoEmpresa",
      name: "IdentificacaoEmpresa",
      typeField: "string",
    },
    {
      field: "FonteIdentificacao",
      label: "FonteIdentificacao",
      name: "FonteIdentificacao",
      typeField: "string",
    },
    {
      field: "PosicaoIdentificacao",
      label: "PosicaoIdentificacao",
      name: "PosicaoIdentificacao",
      typeField: "float",
    },
    {
      field: "AlturaPapel",
      label: "AlturaPapel",
      name: "AlturaPapel",
      typeField: "float",
    },
    {
      field: "DeslocamentoDtCadastro",
      label: "DeslocamentoDtCadastro",
      name: "DeslocamentoDtCadastro",
      typeField: "int",
    },
    {
      field: "FonteDtCadastro",
      label: "FonteDtCadastro",
      name: "FonteDtCadastro",
      typeField: "string",
    },
    {
      field: "PosicaoDtCadastro",
      label: "PosicaoDtCadastro",
      name: "PosicaoDtCadastro",
      typeField: "float",

      scale: 4,
    },
    {
      field: "DeslocamentoPromocao",
      label: "DeslocamentoPromocao",
      name: "DeslocamentoPromocao",
      typeField: "float",

      scale: 4,
    },
    {
      field: "PosicaoPromocao",
      label: "PosicaoPromocao",
      name: "PosicaoPromocao",
      typeField: "float",

      scale: 4,
    },
    {
      field: "FontePromocao",
      label: "FontePromocao",
      name: "FontePromocao",
      typeField: "string",
    },
    {
      field: "DeslocamentoBarra",
      label: "DeslocamentoBarra",
      name: "DeslocamentoBarra",
      typeField: "float",

      scale: 4,
    },
    {
      field: "PosicaoBarra",
      label: "PosicaoBarra",
      name: "PosicaoBarra",
      typeField: "float",

      scale: 4,
    },
    {
      field: "DeslocamentoDescricao",
      label: "DeslocamentoDescricao",
      name: "DeslocamentoDescricao",
      typeField: "float",

      scale: 4,
    },
    {
      field: "InicioImpCodBarras",
      label: "InicioImpCodBarras",
      name: "InicioImpCodBarras",
      typeField: "float",

      scale: 4,
    },
    {
      field: "VlPixel",
      label: "VlPixel",
      name: "VlPixel",
      typeField: "float",

      scale: 4,
    },
    {
      field: "DeslocamentoIdentificacao",
      label: "DeslocamentoIdentificacao",
      name: "DeslocamentoIdentificacao",
      typeField: "int",
    },
    {
      field: "FonteDtFabricacao",
      label: "FonteDtFabricacao",
      name: "FonteDtFabricacao",
      typeField: "string",
    },
    {
      field: "DeslocamentoDtFabricacao",
      label: "DeslocamentoDtFabricacao",
      name: "DeslocamentoDtFabricacao",
      typeField: "int",
    },
    {
      field: "PosicaoDtFabricacao",
      label: "PosicaoDtFabricacao",
      name: "PosicaoDtFabricacao",
      typeField: "float",
    },
  ],
};
