import { TTable } from "../../../../types/model";

export const ConfiguracaoImpKits: TTable = {
  database: "plano",
  table: "ConfiguracaoImpKits",
  fields: [
    {
      field: "CdKit",
      label: "CdKit",
      name: "ConfiguracaoImpKits_id",
      typeField: "string",
      size: 15,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "NumOP",
      label: "NumOP",
      name: "NumOP",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "ProdutoProduzido",
      label: "ProdutoProduzido",
      name: "ProdutoProduzido",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "LoteProdutoProduzido",
      label: "LoteProdutoProduzido",
      name: "LoteProdutoProduzido",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "QtdeProdutoProduzido",
      label: "QtdeProdutoProduzido",
      name: "QtdeProdutoProduzido",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "LoteGrelhaProduzida",
      label: "LoteGrelhaProduzida",
      name: "LoteGrelhaProduzida",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "QtdeGrelhaProduzida",
      label: "QtdeGrelhaProduzida",
      name: "QtdeGrelhaProduzida",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "Largura",
      label: "Largura",
      name: "Largura",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "Espessura",
      label: "Espessura",
      name: "Espessura",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "DescMateriaPrima",
      label: "DescMateriaPrima",
      name: "DescMateriaPrima",
      typeField: "string",
      size: 128,
      allowNull: false,
    },
    {
      field: "QtdeMateriaPrima",
      label: "QtdeMateriaPrima",
      name: "QtdeMateriaPrima",
      typeField: "string",
      size: 128,
      allowNull: false,
    },
    {
      field: "LoteMateriaPrima",
      label: "LoteMateriaPrima",
      name: "LoteMateriaPrima",
      typeField: "string",
      size: 128,
      allowNull: false,
    },
    {
      field: "MaquinaProducao",
      label: "MaquinaProducao",
      name: "MaquinaProducao",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "DtFabricacao",
      label: "DtFabricacao",
      name: "DtFabricacao",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "OperadorMaquina",
      label: "OperadorMaquina",
      name: "OperadorMaquina",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "TipoCaixa",
      label: "TipoCaixa",
      name: "TipoCaixa",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "PecaCaixa",
      label: "PecaCaixa",
      name: "PecaCaixa",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "LoteCaixa",
      label: "LoteCaixa",
      name: "LoteCaixa",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "DtExtrusao",
      label: "DtExtrusao",
      name: "DtExtrusao",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "CdProdutoProduzido",
      label: "CdProdutoProduzido",
      name: "CdProdutoProduzido",
      typeField: "string",
      size: 64,
    },
    {
      field: "CdMateriaPrima",
      label: "CdMateriaPrima",
      name: "CdMateriaPrima",
      typeField: "string",
      size: 64,
    },
    {
      field: "Cliente",
      label: "Cliente",
      name: "Cliente",
      typeField: "string",
      size: 64,
    },
    {
      field: "PostoProdutivo1",
      label: "PostoProdutivo1",
      name: "PostoProdutivo1",
      typeField: "string",
      size: 64,
    },
    {
      field: "PostoProdutivo2",
      label: "PostoProdutivo2",
      name: "PostoProdutivo2",
      typeField: "string",
      size: 64,
    },
    {
      field: "PostoProdutivo3",
      label: "PostoProdutivo3",
      name: "PostoProdutivo3",
      typeField: "string",
      size: 64,
    },
    {
      field: "PostoProdutivo4",
      label: "PostoProdutivo4",
      name: "PostoProdutivo4",
      typeField: "string",
      size: 64,
    },
    {
      field: "PostoProdutivo5",
      label: "PostoProdutivo5",
      name: "PostoProdutivo5",
      typeField: "string",
      size: 64,
    },
    {
      field: "PostoProdutivo6",
      label: "PostoProdutivo6",
      name: "PostoProdutivo6",
      typeField: "string",
      size: 64,
    },
    {
      field: "DescOperacao1",
      label: "DescOperacao1",
      name: "DescOperacao1",
      typeField: "string",
      size: 64,
    },
    {
      field: "DescOperacao2",
      label: "DescOperacao2",
      name: "DescOperacao2",
      typeField: "string",
      size: 64,
    },
    {
      field: "DescOperacao3",
      label: "DescOperacao3",
      name: "DescOperacao3",
      typeField: "string",
      size: 64,
    },
    {
      field: "DescOperacao4",
      label: "DescOperacao4",
      name: "DescOperacao4",
      typeField: "string",
      size: 64,
    },
    {
      field: "DescOperacao5",
      label: "DescOperacao5",
      name: "DescOperacao5",
      typeField: "string",
      size: 64,
    },
    {
      field: "DescOperacao6",
      label: "DescOperacao6",
      name: "DescOperacao6",
      typeField: "string",
      size: 64,
    },
    {
      field: "DtEmissao",
      label: "DtEmissao",
      name: "DtEmissao",
      typeField: "string",
      size: 64,
    },
    {
      field: "Obs",
      label: "Obs",
      name: "Obs",
      typeField: "string",
      size: 64,
    },
  ],
};
