import { TTableDef } from "../../../../types/model";

export const ConfigNop: TTableDef = {
  database: "plano",
  table: "ConfigNop",
  fields: [
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "UF",
      label: "UF",
      name: "UF",
      typeField: "string",
      size: 2,
      allowNull: false,
    },
    {
      field: "TipoOperacao",
      label: "TipoOperacao",
      name: "TipoOperacao",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "TipoNota",
      label: "TipoNota",
      name: "TipoNota",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "TipoCliente",
      label: "TipoCliente",
      name: "TipoCliente",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "OrigemMercadoria",
      label: "OrigemMercadoria",
      name: "OrigemMercadoria",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TipoTributacaoICMS",
      label: "TipoTributacaoICMS",
      name: "TipoTributacaoICMS",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TipoTributacaoIPI",
      label: "TipoTributacaoIPI",
      name: "TipoTributacaoIPI",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TipoTributacaoPIS",
      label: "TipoTributacaoPIS",
      name: "TipoTributacaoPIS",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TipoTributacaoCOFINS",
      label: "TipoTributacaoCOFINS",
      name: "TipoTributacaoCOFINS",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "Nop",
      label: "Nop",
      name: "Nop",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "DtUltAlteracao",
      label: "DtUltAlteracao",
      name: "DtUltAlteracao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "FinalidadeNota",
      label: "FinalidadeNota",
      name: "FinalidadeNota",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
  ],
};
