import { TTable } from "../../../../types/model";

export const ConfiguracaoImpPreco: TTable = {
  database: "plano",
  table: "ConfiguracaoImpPreco",
  fields: [
    {
      field: "IdModeloArquivo",
      label: "IdModeloArquivo",
      name: "ConfiguracaoImpPreco_id",
      typeField: "string",
      size: 20,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "PosicaoProduto",
      label: "PosicaoProduto",
      name: "PosicaoProduto",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TamanhoProduto",
      label: "TamanhoProduto",
      name: "TamanhoProduto",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "PosicaoTabela",
      label: "PosicaoTabela",
      name: "PosicaoTabela",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TamanhoTabela",
      label: "TamanhoTabela",
      name: "TamanhoTabela",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "DecimaisTabela",
      label: "DecimaisTabela",
      name: "DecimaisTabela",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "PosicaoVenda",
      label: "PosicaoVenda",
      name: "PosicaoVenda",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TamanhoVenda",
      label: "TamanhoVenda",
      name: "TamanhoVenda",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "DecimaisVenda",
      label: "DecimaisVenda",
      name: "DecimaisVenda",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
  ],
};
