import { TTable } from "../../../../types/model";

export const ConfiguracaoAtualizacao: TTable = {
  database: "plano",
  table: "ConfiguracaoAtualizacao",
  fields: [
    {
      field: "NumECF",
      label: "NumECF",
      name: "ConfiguracaoAtualizacao_id",
      typeField: "int",
      size: 2,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "Caminho",
      label: "Caminho",
      name: "Caminho",
      typeField: "string",
      size: 1024,
      allowNull: false,
    },
    {
      field: "DtUltAtualizacao",
      label: "DtUltAtualizacao",
      name: "DtUltAtualizacao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "NumUltLinhaMestre",
      label: "NumUltLinhaMestre",
      name: "NumUltLinhaMestre",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumUltLinhaItem",
      label: "NumUltLinhaItem",
      name: "NumUltLinhaItem",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumUltLinhaCaixa",
      label: "NumUltLinhaCaixa",
      name: "NumUltLinhaCaixa",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumUltLinhaFinanceiro",
      label: "NumUltLinhaFinanceiro",
      name: "NumUltLinhaFinanceiro",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumUltLinhaRecebimento",
      label: "NumUltLinhaRecebimento",
      name: "NumUltLinhaRecebimento",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumUltLinhaDocumentoNaoFiscal",
      label: "NumUltLinhaDocumentoNaoFiscal",
      name: "NumUltLinhaDocumentoNaoFiscal",
      typeField: "int",
      size: 2,
    },
    {
      field: "NumUltLinhaMeiosPagamento",
      label: "NumUltLinhaMeiosPagamento",
      name: "NumUltLinhaMeiosPagamento",
      typeField: "int",
      size: 2,
    },
  ],
};
