import { TEntity } from "../../../../types";

export const ConfigNota: TEntity = {
  database: "plano",
  table: "ConfigNota",
  fields: [
    {
      field: "Serie",
      label: "Serie",
      name: "Serie",
      type: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "AlturaFormulario",
      label: "AlturaFormulario",
      name: "AlturaFormulario",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "AliqICMSColuna",
      label: "AliqICMSColuna",
      name: "AliqICMSColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "AliqICMSTamanho",
      label: "AliqICMSTamanho",
      name: "AliqICMSTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "BairroColuna",
      label: "BairroColuna",
      name: "BairroColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "BairroTamanho",
      label: "BairroTamanho",
      name: "BairroTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "BaseCalcICMSColuna",
      label: "BaseCalcICMSColuna",
      name: "BaseCalcICMSColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "BaseCalcICMSLinha",
      label: "BaseCalcICMSLinha",
      name: "BaseCalcICMSLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "BaseCalcICMSTamanho",
      label: "BaseCalcICMSTamanho",
      name: "BaseCalcICMSTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "BaseSubColuna",
      label: "BaseSubColuna",
      name: "BaseSubColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "BaseSubTamanho",
      label: "BaseSubTamanho",
      name: "BaseSubTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "CdProdutoColuna",
      label: "CdProdutoColuna",
      name: "CdProdutoColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "CdProdutoLinha",
      label: "CdProdutoLinha",
      name: "CdProdutoLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "CdProdutoTamanho",
      label: "CdProdutoTamanho",
      name: "CdProdutoTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "CepColuna",
      label: "CepColuna",
      name: "CepColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "CFOPColuna",
      label: "CFOPColuna",
      name: "CFOPColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "CFOPLinha",
      label: "CFOPLinha",
      name: "CFOPLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "ClasFiscalColuna",
      label: "ClasFiscalColuna",
      name: "ClasFiscalColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "ClasFiscalTamanho",
      label: "ClasFiscalTamanho",
      name: "ClasFiscalTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "CNPJColuna",
      label: "CNPJColuna",
      name: "CNPJColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "CNPJTransportadorColuna",
      label: "CNPJTransportadorColuna",
      name: "CNPJTransportadorColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "DescNopColuna",
      label: "DescNopColuna",
      name: "DescNopColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "DescNopTamanho",
      label: "DescNopTamanho",
      name: "DescNopTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "DescricaoColuna",
      label: "DescricaoColuna",
      name: "DescricaoColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "DescricaoTamanho",
      label: "DescricaoTamanho",
      name: "DescricaoTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "DtEmissaoColuna",
      label: "DtEmissaoColuna",
      name: "DtEmissaoColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "DtSaidaColuna",
      label: "DtSaidaColuna",
      name: "DtSaidaColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "EnderecoColuna",
      label: "EnderecoColuna",
      name: "EnderecoColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "EnderecoLinha",
      label: "EnderecoLinha",
      name: "EnderecoLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "EnderecoTamanho",
      label: "EnderecoTamanho",
      name: "EnderecoTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "EndTransportadorColuna",
      label: "EndTransportadorColuna",
      name: "EndTransportadorColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "EndTransportadorLinha",
      label: "EndTransportadorLinha",
      name: "EndTransportadorLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "EndTransportadorTamanho",
      label: "EndTransportadorTamanho",
      name: "EndTransportadorTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "EntradaColuna",
      label: "EntradaColuna",
      name: "EntradaColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "EspecieColuna",
      label: "EspecieColuna",
      name: "EspecieColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "EspecieTamanho",
      label: "EspecieTamanho",
      name: "EspecieTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FaturaColuna",
      label: "FaturaColuna",
      name: "FaturaColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FaturaLinha",
      label: "FaturaLinha",
      name: "FaturaLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "FaturaNumLinhas",
      label: "FaturaNumLinhas",
      name: "FaturaNumLinhas",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FaturaNumParcelas",
      label: "FaturaNumParcelas",
      name: "FaturaNumParcelas",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FaturaEspacos",
      label: "FaturaEspacos",
      name: "FaturaEspacos",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FaturaTamanho",
      label: "FaturaTamanho",
      name: "FaturaTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FaturaValorColuna",
      label: "FaturaValorColuna",
      name: "FaturaValorColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FaturaValorTamanho",
      label: "FaturaValorTamanho",
      name: "FaturaValorTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FaturaVctoColuna",
      label: "FaturaVctoColuna",
      name: "FaturaVctoColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FaturaVctoTamanho",
      label: "FaturaVctoTamanho",
      name: "FaturaVctoTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "HorarioColuna",
      label: "HorarioColuna",
      name: "HorarioColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "InfAdicionaisColuna",
      label: "InfAdicionaisColuna",
      name: "InfAdicionaisColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "InfAdicionaisLinha",
      label: "InfAdicionaisLinha",
      name: "InfAdicionaisLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "InfAdicionaisTamanho",
      label: "InfAdicionaisTamanho",
      name: "InfAdicionaisTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "InscEstColuna",
      label: "InscEstColuna",
      name: "InscEstColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "InscEstTransportadorColuna",
      label: "InscEstTransportadorColuna",
      name: "InscEstTransportadorColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "MarcaColuna",
      label: "MarcaColuna",
      name: "MarcaColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "MarcaTamanho",
      label: "MarcaTamanho",
      name: "MarcaTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "MunicipioColuna",
      label: "MunicipioColuna",
      name: "MunicipioColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "MunicipioLinha",
      label: "MunicipioLinha",
      name: "MunicipioLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "MunicipioTamanho",
      label: "MunicipioTamanho",
      name: "MunicipioTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "MunicipioTransportadorColuna",
      label: "MunicipioTransportadorColuna",
      name: "MunicipioTransportadorColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "MunicipioTransportadorTamanho",
      label: "MunicipioTransportadorTamanho",
      name: "MunicipioTransportadorTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NmTransportadorColuna",
      label: "NmTransportadorColuna",
      name: "NmTransportadorColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NmTransportadorLinha",
      label: "NmTransportadorLinha",
      name: "NmTransportadorLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "NmTransportadorTamanho",
      label: "NmTransportadorTamanho",
      name: "NmTransportadorTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumeroColuna",
      label: "NumeroColuna",
      name: "NumeroColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumeroTamanho",
      label: "NumeroTamanho",
      name: "NumeroTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumLinhasInfAdicionais",
      label: "NumLinhasInfAdicionais",
      name: "NumLinhasInfAdicionais",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumNotaCabColuna",
      label: "NumNotaCabColuna",
      name: "NumNotaCabColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumNotaCabLinha",
      label: "NumNotaCabLinha",
      name: "NumNotaCabLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "NumNotaRodapeColuna",
      label: "NumNotaRodapeColuna",
      name: "NumNotaRodapeColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumNotaRodapeLinha",
      label: "NumNotaRodapeLinha",
      name: "NumNotaRodapeLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "PesoBrutoColuna",
      label: "PesoBrutoColuna",
      name: "PesoBrutoColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "PesoBrutoTamanho",
      label: "PesoBrutoTamanho",
      name: "PesoBrutoTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "PesoLiquidoColuna",
      label: "PesoLiquidoColuna",
      name: "PesoLiquidoColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "PesoLiquidoTamanho",
      label: "PesoLiquidoTamanho",
      name: "PesoLiquidoTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "PlacaTamanho",
      label: "PlacaTamanho",
      name: "PlacaTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "PlacaColuna",
      label: "PlacaColuna",
      name: "PlacaColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "QtdeLinhasProduto",
      label: "QtdeLinhasProduto",
      name: "QtdeLinhasProduto",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "QtdeVolumeColuna",
      label: "QtdeVolumeColuna",
      name: "QtdeVolumeColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "QtdeVolumeLinha",
      label: "QtdeVolumeLinha",
      name: "QtdeVolumeLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "QtdeVolumeTamanho",
      label: "QtdeVolumeTamanho",
      name: "QtdeVolumeTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "QuantidadeColuna",
      label: "QuantidadeColuna",
      name: "QuantidadeColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "QuantidadeTamanho",
      label: "QuantidadeTamanho",
      name: "QuantidadeTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "RzSocialColuna",
      label: "RzSocialColuna",
      name: "RzSocialColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "RzSocialLinha",
      label: "RzSocialLinha",
      name: "RzSocialLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "RzSocialTamanho",
      label: "RzSocialTamanho",
      name: "RzSocialTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "SaidaColuna",
      label: "SaidaColuna",
      name: "SaidaColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "SitTributariaColuna",
      label: "SitTributariaColuna",
      name: "SitTributariaColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "SitTributariaTamanho",
      label: "SitTributariaTamanho",
      name: "SitTributariaTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TelefoneColuna",
      label: "TelefoneColuna",
      name: "TelefoneColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TelefoneTamanho",
      label: "TelefoneTamanho",
      name: "TelefoneTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TipoFreteColuna",
      label: "TipoFreteColuna",
      name: "TipoFreteColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "UFColuna",
      label: "UFColuna",
      name: "UFColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "UFPlacaColuna",
      label: "UFPlacaColuna",
      name: "UFPlacaColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "UFTransportadorColuna",
      label: "UFTransportadorColuna",
      name: "UFTransportadorColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "UnidadeColuna",
      label: "UnidadeColuna",
      name: "UnidadeColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "UnidadeTamanho",
      label: "UnidadeTamanho",
      name: "UnidadeTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlDescontoLinha",
      label: "VlDescontoLinha",
      name: "VlDescontoLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlDescontoColuna",
      label: "VlDescontoColuna",
      name: "VlDescontoColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlDescontoTamanho",
      label: "VlDescontoTamanho",
      name: "VlDescontoTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlDespesasColuna",
      label: "VlDespesasColuna",
      name: "VlDespesasColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlDespesasTamanho",
      label: "VlDespesasTamanho",
      name: "VlDespesasTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlFreteColuna",
      label: "VlFreteColuna",
      name: "VlFreteColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlFreteLinha",
      label: "VlFreteLinha",
      name: "VlFreteLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlFreteTamanho",
      label: "VlFreteTamanho",
      name: "VlFreteTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlICMSColuna",
      label: "VlICMSColuna",
      name: "VlICMSColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlICMSTamanho",
      label: "VlICMSTamanho",
      name: "VlICMSTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlICMSSubColuna",
      label: "VlICMSSubColuna",
      name: "VlICMSSubColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlICMSSubTamanho",
      label: "VlICMSSubTamanho",
      name: "VlICMSSubTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlIPIColuna",
      label: "VlIPIColuna",
      name: "VlIPIColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlIPITamanho",
      label: "VlIPITamanho",
      name: "VlIPITamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlProdutosColuna",
      label: "VlProdutosColuna",
      name: "VlProdutosColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlProdutosTamanho",
      label: "VlProdutosTamanho",
      name: "VlProdutosTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlSeguroColuna",
      label: "VlSeguroColuna",
      name: "VlSeguroColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlSeguroTamanho",
      label: "VlSeguroTamanho",
      name: "VlSeguroTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlTotalColuna",
      label: "VlTotalColuna",
      name: "VlTotalColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlTotalNotaColuna",
      label: "VlTotalNotaColuna",
      name: "VlTotalNotaColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlTotalNotaTamanho",
      label: "VlTotalNotaTamanho",
      name: "VlTotalNotaTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlTotalTamanho",
      label: "VlTotalTamanho",
      name: "VlTotalTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlUnitarioColuna",
      label: "VlUnitarioColuna",
      name: "VlUnitarioColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlUnitarioTamanho",
      label: "VlUnitarioTamanho",
      name: "VlUnitarioTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FonteCabecalho",
      label: "FonteCabecalho",
      name: "FonteCabecalho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FonteProdutos",
      label: "FonteProdutos",
      name: "FonteProdutos",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FonteTotais",
      label: "FonteTotais",
      name: "FonteTotais",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FonteTransportador",
      label: "FonteTransportador",
      name: "FonteTransportador",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FonteFaturas",
      label: "FonteFaturas",
      name: "FonteFaturas",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FonteInfAdicionais",
      label: "FonteInfAdicionais",
      name: "FonteInfAdicionais",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FonteServicos",
      label: "FonteServicos",
      name: "FonteServicos",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "CdServicoLinha",
      label: "CdServicoLinha",
      name: "CdServicoLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "QtdeLinhasServico",
      label: "QtdeLinhasServico",
      name: "QtdeLinhasServico",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "CdServicoColuna",
      label: "CdServicoColuna",
      name: "CdServicoColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "CdServicoTamanho",
      label: "CdServicoTamanho",
      name: "CdServicoTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "DescricaoServicoLinha",
      label: "DescricaoServicoLinha",
      name: "DescricaoServicoLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "DescricaoServicoColuna",
      label: "DescricaoServicoColuna",
      name: "DescricaoServicoColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "DescricaoServicoTamanho",
      label: "DescricaoServicoTamanho",
      name: "DescricaoServicoTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "QuantidadeServicoColuna",
      label: "QuantidadeServicoColuna",
      name: "QuantidadeServicoColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "QuantidadeServicoTamanho",
      label: "QuantidadeServicoTamanho",
      name: "QuantidadeServicoTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlUnitarioServicoColuna",
      label: "VlUnitarioServicoColuna",
      name: "VlUnitarioServicoColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlUnitarioServicoTamanho",
      label: "VlUnitarioServicoTamanho",
      name: "VlUnitarioServicoTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlTotalServicoColuna",
      label: "VlTotalServicoColuna",
      name: "VlTotalServicoColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlTotalServicoTamanho",
      label: "VlTotalServicoTamanho",
      name: "VlTotalServicoTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlServicoLinha",
      label: "VlServicoLinha",
      name: "VlServicoLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlServicoColuna",
      label: "VlServicoColuna",
      name: "VlServicoColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlServicoTamanho",
      label: "VlServicoTamanho",
      name: "VlServicoTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "AliquotaISSLinha",
      label: "AliquotaISSLinha",
      name: "AliquotaISSLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "AliquotaISSColuna",
      label: "AliquotaISSColuna",
      name: "AliquotaISSColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "AliquotaISSTamanho",
      label: "AliquotaISSTamanho",
      name: "AliquotaISSTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlIssLinha",
      label: "VlIssLinha",
      name: "VlIssLinha",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlISSColuna",
      label: "VlISSColuna",
      name: "VlISSColuna",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlISSTamanho",
      label: "VlISSTamanho",
      name: "VlISSTamanho",
      type: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "EmissaoRodapeColuna",
      label: "EmissaoRodapeColuna",
      name: "EmissaoRodapeColuna",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "EmissaoRodapeTamanho",
      label: "EmissaoRodapeTamanho",
      name: "EmissaoRodapeTamanho",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "FgImprimeLoteProdutos",
      label: "FgImprimeLoteProdutos",
      name: "FgImprimeLoteProdutos",
      type: "string",
      size: 1,
    },
    {
      field: "FaturaValorExtensoLinha",
      label: "FaturaValorExtensoLinha",
      name: "FaturaValorExtensoLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "FaturaValorExtensoColuna",
      label: "FaturaValorExtensoColuna",
      name: "FaturaValorExtensoColuna",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "FaturaValorExtensoTamanho",
      label: "FaturaValorExtensoTamanho",
      name: "FaturaValorExtensoTamanho",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "Modelo",
      type: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "AliqIPIColuna",
      label: "AliqIPIColuna",
      name: "AliqIPIColuna",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "AliqIPITamanho",
      label: "AliqIPITamanho",
      name: "AliqIPITamanho",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlIPIItemColuna",
      label: "VlIPIItemColuna",
      name: "VlIPIItemColuna",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlIPIItemTamanho",
      label: "VlIPIItemTamanho",
      name: "VlIPIItemTamanho",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "FaturaPracaPagamentoLinha",
      label: "FaturaPracaPagamentoLinha",
      name: "FaturaPracaPagamentoLinha",
      type: "int",
      size: 2,
    },
    {
      field: "FaturaPracaPagamentoTamanho",
      label: "FaturaPracaPagamentoTamanho",
      name: "FaturaPracaPagamentoTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "FaturaPracaPagamentoColuna",
      label: "FaturaPracaPagamentoColuna",
      name: "FaturaPracaPagamentoColuna",
      type: "int",
      size: 2,
    },
    {
      field: "BaseISSLinha",
      label: "BaseISSLinha",
      name: "BaseISSLinha",
      type: "int",
      size: 2,
    },
    {
      field: "BaseISSColuna",
      label: "BaseISSColuna",
      name: "BaseISSColuna",
      type: "int",
      size: 2,
    },
    {
      field: "BaseISSTamanho",
      label: "BaseISSTamanho",
      name: "BaseISSTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "InscMunicipalLinha",
      label: "InscMunicipalLinha",
      name: "InscMunicipalLinha",
      type: "int",
      size: 2,
    },
    {
      field: "InscMunicipalColuna",
      label: "InscMunicipalColuna",
      name: "InscMunicipalColuna",
      type: "int",
      size: 2,
    },
    {
      field: "InscMunicipalTamanho",
      label: "InscMunicipalTamanho",
      name: "InscMunicipalTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "DecimaisValorProduto",
      label: "DecimaisValorProduto",
      name: "DecimaisValorProduto",
      type: "int",
      size: 2,
    },
    {
      field: "DecimaisAliqIPI",
      label: "DecimaisAliqIPI",
      name: "DecimaisAliqIPI",
      type: "int",
      size: 2,
    },
    {
      field: "DecimaisAliqICMS",
      label: "DecimaisAliqICMS",
      name: "DecimaisAliqICMS",
      type: "int",
      size: 2,
    },
    {
      field: "RzSocialFilialLinha",
      label: "RzSocialFilialLinha",
      name: "RzSocialFilialLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "RzSocialFilialColuna",
      label: "RzSocialFilialColuna",
      name: "RzSocialFilialColuna",
      type: "int",
      size: 2,
    },
    {
      field: "RzSocialFilialTamanho",
      label: "RzSocialFilialTamanho",
      name: "RzSocialFilialTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "EnderecoFilialLinha",
      label: "EnderecoFilialLinha",
      name: "EnderecoFilialLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "EnderecoFilialColuna",
      label: "EnderecoFilialColuna",
      name: "EnderecoFilialColuna",
      type: "int",
      size: 2,
    },
    {
      field: "EnderecoFilialTamanho",
      label: "EnderecoFilialTamanho",
      name: "EnderecoFilialTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "CNPJFilialLinha",
      label: "CNPJFilialLinha",
      name: "CNPJFilialLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "CNPJFilialColuna",
      label: "CNPJFilialColuna",
      name: "CNPJFilialColuna",
      type: "int",
      size: 2,
    },
    {
      field: "CNPJFilialTamanho",
      label: "CNPJFilialTamanho",
      name: "CNPJFilialTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "TelefoneFilialLinha",
      label: "TelefoneFilialLinha",
      name: "TelefoneFilialLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "TelefoneFilialColuna",
      label: "TelefoneFilialColuna",
      name: "TelefoneFilialColuna",
      type: "int",
      size: 2,
    },
    {
      field: "TelefoneFilialTamanho",
      label: "TelefoneFilialTamanho",
      name: "TelefoneFilialTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "NumNotaCompLinha",
      label: "NumNotaCompLinha",
      name: "NumNotaCompLinha",
      type: "int",
      size: 2,
    },
    {
      field: "NumNotaCompColuna",
      label: "NumNotaCompColuna",
      name: "NumNotaCompColuna",
      type: "int",
      size: 2,
    },
    {
      field: "FgDestacaNumNotaCabecalho",
      label: "FgDestacaNumNotaCabecalho",
      name: "FgDestacaNumNotaCabecalho",
      type: "string",
      size: 1,
    },
    {
      field: "FgDestacaNumNotaRodape",
      label: "FgDestacaNumNotaRodape",
      name: "FgDestacaNumNotaRodape",
      type: "string",
      size: 1,
    },
    {
      field: "FgConfirmaSaltoPagina",
      label: "FgConfirmaSaltoPagina",
      name: "FgConfirmaSaltoPagina",
      type: "string",
      size: 1,
    },
    {
      field: "FonteNumNotaCabecalho",
      label: "FonteNumNotaCabecalho",
      name: "FonteNumNotaCabecalho",
      type: "int",
      size: 2,
    },
    {
      field: "FonteNumNotaRodape",
      label: "FonteNumNotaRodape",
      name: "FonteNumNotaRodape",
      type: "int",
      size: 2,
    },
    {
      field: "BaseCalcPISLinha",
      label: "BaseCalcPISLinha",
      name: "BaseCalcPISLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "BaseCalcPISColuna",
      label: "BaseCalcPISColuna",
      name: "BaseCalcPISColuna",
      type: "int",
      size: 2,
    },
    {
      field: "BaseCalcPISTamanho",
      label: "BaseCalcPISTamanho",
      name: "BaseCalcPISTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "AliquotaPISLinha",
      label: "AliquotaPISLinha",
      name: "AliquotaPISLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "AliquotaPISColuna",
      label: "AliquotaPISColuna",
      name: "AliquotaPISColuna",
      type: "int",
      size: 2,
    },
    {
      field: "AliquotaPISTamanho",
      label: "AliquotaPISTamanho",
      name: "AliquotaPISTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "VlPISLinha",
      label: "VlPISLinha",
      name: "VlPISLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlPISColuna",
      label: "VlPISColuna",
      name: "VlPISColuna",
      type: "int",
      size: 2,
    },
    {
      field: "VlPISTamanho",
      label: "VlPISTamanho",
      name: "VlPISTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "BaseCalcCOFINSLinha",
      label: "BaseCalcCOFINSLinha",
      name: "BaseCalcCOFINSLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "BaseCalcCOFINSColuna",
      label: "BaseCalcCOFINSColuna",
      name: "BaseCalcCOFINSColuna",
      type: "int",
      size: 2,
    },
    {
      field: "BaseCalcCOFINSTamanho",
      label: "BaseCalcCOFINSTamanho",
      name: "BaseCalcCOFINSTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "AliquotaCOFINSLinha",
      label: "AliquotaCOFINSLinha",
      name: "AliquotaCOFINSLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "AliquotaCOFINSColuna",
      label: "AliquotaCOFINSColuna",
      name: "AliquotaCOFINSColuna",
      type: "int",
      size: 2,
    },
    {
      field: "AliquotaCOFINSTamanho",
      label: "AliquotaCOFINSTamanho",
      name: "AliquotaCOFINSTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "VlCOFINSLinha",
      label: "VlCOFINSLinha",
      name: "VlCOFINSLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlCOFINSColuna",
      label: "VlCOFINSColuna",
      name: "VlCOFINSColuna",
      type: "int",
      size: 2,
    },
    {
      field: "VlCOFINSTamanho",
      label: "VlCOFINSTamanho",
      name: "VlCOFINSTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "BaseCalcIRRFLinha",
      label: "BaseCalcIRRFLinha",
      name: "BaseCalcIRRFLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "BaseCalcIRRFColuna",
      label: "BaseCalcIRRFColuna",
      name: "BaseCalcIRRFColuna",
      type: "int",
      size: 2,
    },
    {
      field: "BaseCalcIRRFTamanho",
      label: "BaseCalcIRRFTamanho",
      name: "BaseCalcIRRFTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "AliquotaIRRFLinha",
      label: "AliquotaIRRFLinha",
      name: "AliquotaIRRFLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "AliquotaIRRFColuna",
      label: "AliquotaIRRFColuna",
      name: "AliquotaIRRFColuna",
      type: "int",
      size: 2,
    },
    {
      field: "AliquotaIRRFTamanho",
      label: "AliquotaIRRFTamanho",
      name: "AliquotaIRRFTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "VlIRRFLinha",
      label: "VlIRRFLinha",
      name: "VlIRRFLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlIRRFColuna",
      label: "VlIRRFColuna",
      name: "VlIRRFColuna",
      type: "int",
      size: 2,
    },
    {
      field: "VlIRRFTamanho",
      label: "VlIRRFTamanho",
      name: "VlIRRFTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "BaseCalcCSLLLinha",
      label: "BaseCalcCSLLLinha",
      name: "BaseCalcCSLLLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "BaseCalcCSLLColuna",
      label: "BaseCalcCSLLColuna",
      name: "BaseCalcCSLLColuna",
      type: "int",
      size: 2,
    },
    {
      field: "BaseCalcCSLLTamanho",
      label: "BaseCalcCSLLTamanho",
      name: "BaseCalcCSLLTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "AliquotaCSLLLinha",
      label: "AliquotaCSLLLinha",
      name: "AliquotaCSLLLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "AliquotaCSLLColuna",
      label: "AliquotaCSLLColuna",
      name: "AliquotaCSLLColuna",
      type: "int",
      size: 2,
    },
    {
      field: "AliquotaCSLLTamanho",
      label: "AliquotaCSLLTamanho",
      name: "AliquotaCSLLTamanho",
      type: "int",
      size: 2,
    },
    {
      field: "VlCSLLLinha",
      label: "VlCSLLLinha",
      name: "VlCSLLLinha",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlCSLLColuna",
      label: "VlCSLLColuna",
      name: "VlCSLLColuna",
      type: "int",
      size: 2,
    },
    {
      field: "VlCSLLTamanho",
      label: "VlCSLLTamanho",
      name: "VlCSLLTamanho",
      type: "int",
      size: 2,
    },
  ],
};
