import { TTable } from "../../../../types/model";

export const ConfigEtiqMalaDireta: TTable = {
  database: "plano",
  table: "ConfigEtiqMalaDireta",
  fields: [
    {
      field: "Impressora",
      label: "Impressora",
      name: "ConfigEtiqMalaDireta_id",
      typeField: "string",
      size: 40,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "QtdeEtiquetasLinha",
      label: "QtdeEtiquetasLinha",
      name: "QtdeEtiquetasLinha",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "QtdeEtiquetasColunas",
      label: "QtdeEtiquetasColunas",
      name: "QtdeEtiquetasColunas",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "QtdeLinhasInicial",
      label: "QtdeLinhasInicial",
      name: "QtdeLinhasInicial",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "EspLateral",
      label: "EspLateral",
      name: "EspLateral",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "QtdeCaracteres",
      label: "QtdeCaracteres",
      name: "QtdeCaracteres",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "QtdeLinhas",
      label: "QtdeLinhas",
      name: "QtdeLinhas",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "CaracteresEntreEtiquetas",
      label: "CaracteresEntreEtiquetas",
      name: "CaracteresEntreEtiquetas",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "LinhaRzSocial",
      label: "LinhaRzSocial",
      name: "LinhaRzSocial",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "LinhaContato",
      label: "LinhaContato",
      name: "LinhaContato",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "LinhaEndereco",
      label: "LinhaEndereco",
      name: "LinhaEndereco",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "LinhaBairro",
      label: "LinhaBairro",
      name: "LinhaBairro",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "LinhaCidade",
      label: "LinhaCidade",
      name: "LinhaCidade",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "LinhaCep",
      label: "LinhaCep",
      name: "LinhaCep",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "TipoImpressao",
      label: "TipoImpressao",
      name: "TipoImpressao",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "AlturaLinha",
      label: "AlturaLinha",
      name: "AlturaLinha",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "LinhaCartaoFidelidade",
      label: "LinhaCartaoFidelidade",
      name: "LinhaCartaoFidelidade",
      typeField: "int",
      size: 2,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "Modelo",
      typeField: "string",
      size: 20,
    },
    {
      field: "LinhaCartao",
      label: "LinhaCartao",
      name: "LinhaCartao",
      typeField: "int",
      size: 2,
    },
    {
      field: "QtdeLinhasUltima",
      label: "QtdeLinhasUltima",
      name: "QtdeLinhasUltima",
      typeField: "int",
      size: 4,
    },
  ],
};
