import { TTableDef } from "../../../../types/model";

export const ConfiguracaoPrecoCompra: TTableDef = {
  database: "plano",
  table: "ConfiguracaoPrecoCompra",
  fields: [
    {
      field: "CdEmpresa",
      label: "CdEmpresa",
      name: "ConfiguracaoPrecoCompra_id",
      typeField: "int",
      size: 9,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "FgVlTabela",
      label: "FgVlTabela",
      name: "FgVlTabela",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgVlCusto",
      label: "FgVlCusto",
      name: "FgVlCusto",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgVlAtacado",
      label: "FgVlAtacado",
      name: "FgVlAtacado",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgVlVarejo",
      label: "FgVlVarejo",
      name: "FgVlVarejo",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgCalculoVlCusto",
      label: "FgCalculoVlCusto",
      name: "FgCalculoVlCusto",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgLogPreco",
      label: "FgLogPreco",
      name: "FgLogPreco",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
  ],
};
