import { TTableDef } from "../../../../types/model";

export const Configuracao: TTableDef = {
  database: "plano",
  table: "Configuracao",
  fields: [
    {
      field: "Identificacao",
      label: "Identificacao",
      name: "Configuracao_id",
      typeField: "int",
      size: 2,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "ModeloFat",
      label: "ModeloFat",
      name: "ModeloFat",
      typeField: "string",
      size: 50,
    },
    {
      field: "ModeloNf",
      label: "ModeloNf",
      name: "ModeloNf",
      typeField: "string",
      size: 50,
    },
    {
      field: "EAN",
      label: "EAN",
      name: "EAN",
      typeField: "string",
      size: 1,
    },
    {
      field: "CGCCPF",
      label: "CGCCPF",
      name: "CGCCPF",
      typeField: "string",
      size: 1,
    },
    {
      field: "TipoCliente",
      label: "TipoCliente",
      name: "TipoCliente",
      typeField: "string",
      size: 1,
    },
    {
      field: "TipoLucro",
      label: "TipoLucro",
      name: "TipoLucro",
      typeField: "string",
      size: 1,
    },
    {
      field: "VendeConvenio",
      label: "VendeConvenio",
      name: "VendeConvenio",
      typeField: "string",
      size: 1,
    },
    {
      field: "PrecoIndividualizado",
      label: "PrecoIndividualizado",
      name: "PrecoIndividualizado",
      typeField: "string",
      size: 1,
    },
    {
      field: "TaxaSelic",
      label: "TaxaSelic",
      name: "TaxaSelic",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "TextoNoCodigo",
      label: "TextoNoCodigo",
      name: "TextoNoCodigo",
      typeField: "string",
      size: 1,
    },
    {
      field: "TpVdPedido",
      label: "TpVdPedido",
      name: "TpVdPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "VendaComSerie",
      label: "VendaComSerie",
      name: "VendaComSerie",
      typeField: "string",
      size: 1,
    },
    {
      field: "EtiquetasConvenio",
      label: "EtiquetasConvenio",
      name: "EtiquetasConvenio",
      typeField: "string",
      size: 1,
    },
    {
      field: "DinheiroCR",
      label: "DinheiroCR",
      name: "DinheiroCR",
      typeField: "string",
      size: 1,
    },
    {
      field: "BuscaProdutos",
      label: "BuscaProdutos",
      name: "BuscaProdutos",
      typeField: "string",
      size: 1,
    },
    {
      field: "CasasDecimais",
      label: "CasasDecimais",
      name: "CasasDecimais",
      typeField: "int",
      size: 1,
    },
    {
      field: "ConversaoMedida",
      label: "ConversaoMedida",
      name: "ConversaoMedida",
      typeField: "string",
      size: 1,
    },
    {
      field: "Correcao",
      label: "Correcao",
      name: "Correcao",
      typeField: "string",
      size: 1,
    },
    {
      field: "Dinheiro",
      label: "Dinheiro",
      name: "Dinheiro",
      typeField: "string",
      size: 1,
    },
    {
      field: "Embalagem",
      label: "Embalagem",
      name: "Embalagem",
      typeField: "string",
      size: 1,
    },
    {
      field: "ExigeCPF",
      label: "ExigeCPF",
      name: "ExigeCPF",
      typeField: "string",
      size: 1,
    },
    {
      field: "ExtratoCliente",
      label: "ExtratoCliente",
      name: "ExtratoCliente",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgLiberaLimite",
      label: "FgLiberaLimite",
      name: "FgLiberaLimite",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPreFatura",
      label: "FgPreFatura",
      name: "FgPreFatura",
      typeField: "string",
      size: 1,
    },
    {
      field: "GravaObsNota",
      label: "GravaObsNota",
      name: "GravaObsNota",
      typeField: "string",
      size: 1,
    },
    {
      field: "LancIndividual",
      label: "LancIndividual",
      name: "LancIndividual",
      typeField: "string",
      size: 1,
    },
    {
      field: "LancVista",
      label: "LancVista",
      name: "LancVista",
      typeField: "string",
      size: 1,
    },
    {
      field: "NFMestreGrade",
      label: "NFMestreGrade",
      name: "NFMestreGrade",
      typeField: "string",
      size: 1,
    },
    {
      field: "PedidoMaximo",
      label: "PedidoMaximo",
      name: "PedidoMaximo",
      typeField: "string",
      size: 1,
    },
    {
      field: "ImpressoraDup",
      label: "ImpressoraDup",
      name: "ImpressoraDup",
      typeField: "string",
      size: 50,
    },
    {
      field: "ImpressoraFat",
      label: "ImpressoraFat",
      name: "ImpressoraFat",
      typeField: "string",
      size: 50,
    },
    {
      field: "ImpressoraRecibo",
      label: "ImpressoraRecibo",
      name: "ImpressoraRecibo",
      typeField: "string",
      size: 50,
    },
    {
      field: "PortaDup",
      label: "PortaDup",
      name: "PortaDup",
      typeField: "string",
      size: 4,
    },
    {
      field: "PortaFat",
      label: "PortaFat",
      name: "PortaFat",
      typeField: "string",
      size: 4,
    },
    {
      field: "PortaRecibo",
      label: "PortaRecibo",
      name: "PortaRecibo",
      typeField: "string",
      size: 4,
    },
    {
      field: "ImpressoraNF",
      label: "ImpressoraNF",
      name: "ImpressoraNF",
      typeField: "string",
      size: 50,
    },
    {
      field: "PortaNf",
      label: "PortaNf",
      name: "PortaNf",
      typeField: "string",
      size: 4,
    },
    {
      field: "ImpressoraBloq",
      label: "ImpressoraBloq",
      name: "ImpressoraBloq",
      typeField: "string",
      size: 50,
    },
    {
      field: "PortaBloq",
      label: "PortaBloq",
      name: "PortaBloq",
      typeField: "string",
      size: 4,
    },
    {
      field: "ImpressoraEtiq",
      label: "ImpressoraEtiq",
      name: "ImpressoraEtiq",
      typeField: "string",
      size: 50,
    },
    {
      field: "PortaEtiq",
      label: "PortaEtiq",
      name: "PortaEtiq",
      typeField: "string",
      size: 4,
    },
    {
      field: "ImpressoraConv",
      label: "ImpressoraConv",
      name: "ImpressoraConv",
      typeField: "string",
      size: 50,
    },
    {
      field: "PortaConv",
      label: "PortaConv",
      name: "PortaConv",
      typeField: "string",
      size: 4,
    },
    {
      field: "ImpressoraCont",
      label: "ImpressoraCont",
      name: "ImpressoraCont",
      typeField: "string",
      size: 50,
    },
    {
      field: "PortaCont",
      label: "PortaCont",
      name: "PortaCont",
      typeField: "string",
      size: 4,
    },
    {
      field: "ImpressoraRat",
      label: "ImpressoraRat",
      name: "ImpressoraRat",
      typeField: "string",
      size: 50,
    },
    {
      field: "PortaRat",
      label: "PortaRat",
      name: "PortaRat",
      typeField: "string",
      size: 4,
    },
    {
      field: "ImpressoraRes",
      label: "ImpressoraRes",
      name: "ImpressoraRes",
      typeField: "string",
      size: 50,
    },
    {
      field: "PortaRes",
      label: "PortaRes",
      name: "PortaRes",
      typeField: "string",
      size: 4,
    },
    {
      field: "ImpressoraPed",
      label: "ImpressoraPed",
      name: "ImpressoraPed",
      typeField: "string",
      size: 50,
    },
    {
      field: "PortaPed",
      label: "PortaPed",
      name: "PortaPed",
      typeField: "string",
      size: 4,
    },
    {
      field: "ImpressoraReq",
      label: "ImpressoraReq",
      name: "ImpressoraReq",
      typeField: "string",
      size: 50,
    },
    {
      field: "PortaReq",
      label: "PortaReq",
      name: "PortaReq",
      typeField: "string",
      size: 4,
    },
    {
      field: "Assistencia",
      label: "Assistencia",
      name: "Assistencia",
      typeField: "string",
      size: 1,
    },
    {
      field: "PortaScanner",
      label: "PortaScanner",
      name: "PortaScanner",
      typeField: "int",
      size: 1,
    },
    {
      field: "CaminhoBackup",
      label: "CaminhoBackup",
      name: "CaminhoBackup",
      typeField: "string",
      size: 50,
    },
    {
      field: "Caminho",
      label: "Caminho",
      name: "Caminho",
      typeField: "string",
      size: 50,
    },
    {
      field: "DtCompactacao",
      label: "DtCompactacao",
      name: "DtCompactacao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "TeclaAbertura",
      label: "TeclaAbertura",
      name: "TeclaAbertura",
      typeField: "int",
      size: 1,
    },
    {
      field: "RelCustoMedio",
      label: "RelCustoMedio",
      name: "RelCustoMedio",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgControlaEstoquePedido",
      label: "FgControlaEstoquePedido",
      name: "FgControlaEstoquePedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "CasasDecimaisQtde",
      label: "CasasDecimaisQtde",
      name: "CasasDecimaisQtde",
      typeField: "int",
      size: 4,
    },
    {
      field: "FgIcmsCusto",
      label: "FgIcmsCusto",
      name: "FgIcmsCusto",
      typeField: "string",
      size: 1,
    },
    {
      field: "ModalidadesPagto",
      label: "ModalidadesPagto",
      name: "ModalidadesPagto",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgFilialFinanc",
      label: "FgFilialFinanc",
      name: "FgFilialFinanc",
      typeField: "string",
      size: 1,
    },
    {
      field: "ImpressoraGarantia",
      label: "ImpressoraGarantia",
      name: "ImpressoraGarantia",
      typeField: "string",
      size: 150,
    },
    {
      field: "PortaGarantia",
      label: "PortaGarantia",
      name: "PortaGarantia",
      typeField: "string",
      size: 10,
    },
    {
      field: "DescEspecifica",
      label: "DescEspecifica",
      name: "DescEspecifica",
      typeField: "string",
      size: 1,
    },
    {
      field: "QtdeItensNF",
      label: "QtdeItensNF",
      name: "QtdeItensNF",
      typeField: "int",
      size: 4,
    },
    {
      field: "FgObrigaLctoBancarioCR",
      label: "FgObrigaLctoBancarioCR",
      name: "FgObrigaLctoBancarioCR",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgExigeComentarioCR",
      label: "FgExigeComentarioCR",
      name: "FgExigeComentarioCR",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgObrigatorioCP",
      label: "FgObrigatorioCP",
      name: "FgObrigatorioCP",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgGravaEvento",
      label: "FgGravaEvento",
      name: "FgGravaEvento",
      typeField: "string",
      size: 1,
    },
    {
      field: "MoedaEspecifica",
      label: "MoedaEspecifica",
      name: "MoedaEspecifica",
      typeField: "string",
      size: 50,
    },
    {
      field: "ModeloPedido",
      label: "ModeloPedido",
      name: "ModeloPedido",
      typeField: "string",
      size: 50,
    },
    {
      field: "AltComponentesKit",
      label: "AltComponentesKit",
      name: "AltComponentesKit",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgLancFinanceiroTransf",
      label: "FgLancFinanceiroTransf",
      name: "FgLancFinanceiroTransf",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgAutorizacaoRemota",
      label: "FgAutorizacaoRemota",
      name: "FgAutorizacaoRemota",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgVendaKit",
      label: "FgVendaKit",
      name: "FgVendaKit",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgExibeEstoqueNF",
      label: "FgExibeEstoqueNF",
      name: "FgExibeEstoqueNF",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgBloqueioEstoqueNegativo",
      label: "FgBloqueioEstoqueNegativo",
      name: "FgBloqueioEstoqueNegativo",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgSenhaMaster",
      label: "FgSenhaMaster",
      name: "FgSenhaMaster",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgAltNumNota",
      label: "FgAltNumNota",
      name: "FgAltNumNota",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPrecoNoFechamento",
      label: "FgPrecoNoFechamento",
      name: "FgPrecoNoFechamento",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgOrdenaPedido",
      label: "FgOrdenaPedido",
      name: "FgOrdenaPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgReservaPedido",
      label: "FgReservaPedido",
      name: "FgReservaPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgBloqueioEstoqueNegativoPed",
      label: "FgBloqueioEstoqueNegativoPed",
      name: "FgBloqueioEstoqueNegativoPed",
      typeField: "string",
      size: 1,
    },
    {
      field: "DtUltLimpeza",
      label: "DtUltLimpeza",
      name: "DtUltLimpeza",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DiasTitCobrDinheiro",
      label: "DiasTitCobrDinheiro",
      name: "DiasTitCobrDinheiro",
      typeField: "int",
      size: 2,
    },
    {
      field: "DiasPedidos",
      label: "DiasPedidos",
      name: "DiasPedidos",
      typeField: "int",
      size: 2,
    },
    {
      field: "DiasCaixa",
      label: "DiasCaixa",
      name: "DiasCaixa",
      typeField: "int",
      size: 2,
    },
    {
      field: "DiasLog",
      label: "DiasLog",
      name: "DiasLog",
      typeField: "int",
      size: 2,
    },
    {
      field: "TipoCusto",
      label: "TipoCusto",
      name: "TipoCusto",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgParametrosMovFiscal",
      label: "FgParametrosMovFiscal",
      name: "FgParametrosMovFiscal",
      typeField: "string",
      size: 1,
    },
    {
      field: "IniciaisCriacaoEAN",
      label: "IniciaisCriacaoEAN",
      name: "IniciaisCriacaoEAN",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "FgTrocaTipoVenda",
      label: "FgTrocaTipoVenda",
      name: "FgTrocaTipoVenda",
      typeField: "string",
      size: 1,
    },
    {
      field: "DecimaisCusto",
      label: "DecimaisCusto",
      name: "DecimaisCusto",
      typeField: "int",
      size: 2,
    },
    {
      field: "FgColetor",
      label: "FgColetor",
      name: "FgColetor",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgImpTermoResponsabilidade",
      label: "FgImpTermoResponsabilidade",
      name: "FgImpTermoResponsabilidade",
      typeField: "string",
      size: 1,
    },
    {
      field: "CRMCoringa",
      label: "CRMCoringa",
      name: "CRMCoringa",
      typeField: "string",
      size: 10,
    },
    {
      field: "FgDetalhaPagamento",
      label: "FgDetalhaPagamento",
      name: "FgDetalhaPagamento",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgAlteraPgtoPDV",
      label: "FgAlteraPgtoPDV",
      name: "FgAlteraPgtoPDV",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgCRMObrigatorio",
      label: "FgCRMObrigatorio",
      name: "FgCRMObrigatorio",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgComissaoExtra",
      label: "FgComissaoExtra",
      name: "FgComissaoExtra",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgGravaExclusaoLimpeza",
      label: "FgGravaExclusaoLimpeza",
      name: "FgGravaExclusaoLimpeza",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgAssociaFornecedor",
      label: "FgAssociaFornecedor",
      name: "FgAssociaFornecedor",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgControleLotes",
      label: "FgControleLotes",
      name: "FgControleLotes",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgCEP",
      label: "FgCEP",
      name: "FgCEP",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgDiasSemEstoque",
      label: "FgDiasSemEstoque",
      name: "FgDiasSemEstoque",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgBloqueioCreditoPedido",
      label: "FgBloqueioCreditoPedido",
      name: "FgBloqueioCreditoPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgLivredigPedido",
      label: "FgLivredigPedido",
      name: "FgLivredigPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgBloqueioEstoqueNegativoPdv",
      label: "FgBloqueioEstoqueNegativoPdv",
      name: "FgBloqueioEstoqueNegativoPdv",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgControlaCredito",
      label: "FgControlaCredito",
      name: "FgControlaCredito",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgClienteInicioPedido",
      label: "FgClienteInicioPedido",
      name: "FgClienteInicioPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgRedutorComissao",
      label: "FgRedutorComissao",
      name: "FgRedutorComissao",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgAgendamento",
      label: "FgAgendamento",
      name: "FgAgendamento",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPreVenda",
      label: "FgPreVenda",
      name: "FgPreVenda",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgObrigatorioMidia",
      label: "FgObrigatorioMidia",
      name: "FgObrigatorioMidia",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgSugereNop",
      label: "FgSugereNop",
      name: "FgSugereNop",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgSelecaoProdutoFaixaPreco",
      label: "FgSelecaoProdutoFaixaPreco",
      name: "FgSelecaoProdutoFaixaPreco",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgSelecaoProdutoFaixaEstoque",
      label: "FgSelecaoProdutoFaixaEstoque",
      name: "FgSelecaoProdutoFaixaEstoque",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPametrosCustoProduto",
      label: "FgPametrosCustoProduto",
      name: "FgPametrosCustoProduto",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgCustoAlternativoProduto",
      label: "FgCustoAlternativoProduto",
      name: "FgCustoAlternativoProduto",
      typeField: "string",
      size: 1,
    },
    {
      field: "CdDepartamentoPadrao",
      label: "CdDepartamentoPadrao",
      name: "CdDepartamentoPadrao",
      typeField: "int",
      size: 2,
    },
    {
      field: "CdCategoriaPadrao",
      label: "CdCategoriaPadrao",
      name: "CdCategoriaPadrao",
      typeField: "int",
      size: 2,
    },
    {
      field: "FgMontagemGrade",
      label: "FgMontagemGrade",
      name: "FgMontagemGrade",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgRedeAssistencia",
      label: "FgRedeAssistencia",
      name: "FgRedeAssistencia",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgProdutoSegmentoCliente",
      label: "FgProdutoSegmentoCliente",
      name: "FgProdutoSegmentoCliente",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgProdutosRelacionados",
      label: "FgProdutosRelacionados",
      name: "FgProdutosRelacionados",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgProdutosEquivalentes",
      label: "FgProdutosEquivalentes",
      name: "FgProdutosEquivalentes",
      typeField: "string",
      size: 1,
    },
    {
      field: "CaminhoExportVMS",
      label: "CaminhoExportVMS",
      name: "CaminhoExportVMS",
      typeField: "string",
      size: 128,
    },
    {
      field: "CaminhoImportVMS",
      label: "CaminhoImportVMS",
      name: "CaminhoImportVMS",
      typeField: "string",
      size: 128,
    },
    {
      field: "FgFidelidade",
      label: "FgFidelidade",
      name: "FgFidelidade",
      typeField: "string",
      size: 1,
    },
    {
      field: "CdCategPadrao",
      label: "CdCategPadrao",
      name: "CdCategPadrao",
      typeField: "string",
      size: 6,
    },
    {
      field: "FgVendaClienteInativo",
      label: "FgVendaClienteInativo",
      name: "FgVendaClienteInativo",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgTrocaPgtosCupom",
      label: "FgTrocaPgtosCupom",
      name: "FgTrocaPgtosCupom",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgImprimeLinhasAdicionais",
      label: "FgImprimeLinhasAdicionais",
      name: "FgImprimeLinhasAdicionais",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgCancelaCRECF",
      label: "FgCancelaCRECF",
      name: "FgCancelaCRECF",
      typeField: "string",
      size: 1,
    },
    {
      field: "PercVendaEspecial",
      label: "PercVendaEspecial",
      name: "PercVendaEspecial",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "FgObrigaPercLucro",
      label: "FgObrigaPercLucro",
      name: "FgObrigaPercLucro",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgDifNfEntrada",
      label: "FgDifNfEntrada",
      name: "FgDifNfEntrada",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgTrocaFilialPDV",
      label: "FgTrocaFilialPDV",
      name: "FgTrocaFilialPDV",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgExibeUltPedidos",
      label: "FgExibeUltPedidos",
      name: "FgExibeUltPedidos",
      typeField: "string",
      size: 1,
    },
    {
      field: "MesesPedido",
      label: "MesesPedido",
      name: "MesesPedido",
      typeField: "int",
      size: 2,
    },
    {
      field: "FgSenhaAbaixoCustoPed",
      label: "FgSenhaAbaixoCustoPed",
      name: "FgSenhaAbaixoCustoPed",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgControlaEnvelopes",
      label: "FgControlaEnvelopes",
      name: "FgControlaEnvelopes",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgAlertaVlTabela",
      label: "FgAlertaVlTabela",
      name: "FgAlertaVlTabela",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgImprimeItensKit",
      label: "FgImprimeItensKit",
      name: "FgImprimeItensKit",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgCarregaItemKit",
      label: "FgCarregaItemKit",
      name: "FgCarregaItemKit",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgConfereCliente",
      label: "FgConfereCliente",
      name: "FgConfereCliente",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgTeleEntrega",
      label: "FgTeleEntrega",
      name: "FgTeleEntrega",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgCancelaCRENF",
      label: "FgCancelaCRENF",
      name: "FgCancelaCRENF",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgAutorizacaoIndividual",
      label: "FgAutorizacaoIndividual",
      name: "FgAutorizacaoIndividual",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgConfereLotes",
      label: "FgConfereLotes",
      name: "FgConfereLotes",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgCNPJObrigatorio",
      label: "FgCNPJObrigatorio",
      name: "FgCNPJObrigatorio",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgInscEstObrigatorio",
      label: "FgInscEstObrigatorio",
      name: "FgInscEstObrigatorio",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgVidalink",
      label: "FgVidalink",
      name: "FgVidalink",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgObrigaRGPsico",
      label: "FgObrigaRGPsico",
      name: "FgObrigaRGPsico",
      typeField: "string",
      size: 1,
    },
    {
      field: "CaminhoVidalink",
      label: "CaminhoVidalink",
      name: "CaminhoVidalink",
      typeField: "string",
      size: 512,
    },
    {
      field: "DiasCarenciaBloqCredito",
      label: "DiasCarenciaBloqCredito",
      name: "DiasCarenciaBloqCredito",
      typeField: "int",
      size: 2,
    },
    {
      field: "DtUltBloqueio",
      label: "DtUltBloqueio",
      name: "DtUltBloqueio",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "FgDataEntregaPedido",
      label: "FgDataEntregaPedido",
      name: "FgDataEntregaPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgSeparacaoPedido",
      label: "FgSeparacaoPedido",
      name: "FgSeparacaoPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "ExibeItensSelPedido",
      label: "ExibeItensSelPedido",
      name: "ExibeItensSelPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "NumLoteOP",
      label: "NumLoteOP",
      name: "NumLoteOP",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgConferePedido",
      label: "FgConferePedido",
      name: "FgConferePedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgReabrePedido",
      label: "FgReabrePedido",
      name: "FgReabrePedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgAtualizaDataOrc",
      label: "FgAtualizaDataOrc",
      name: "FgAtualizaDataOrc",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgExibeEstPedido",
      label: "FgExibeEstPedido",
      name: "FgExibeEstPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgDuplicaItensPedido",
      label: "FgDuplicaItensPedido",
      name: "FgDuplicaItensPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPedidoAgenda",
      label: "FgPedidoAgenda",
      name: "FgPedidoAgenda",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgTrocaOperadorCaixa",
      label: "FgTrocaOperadorCaixa",
      name: "FgTrocaOperadorCaixa",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgTrocaTipoDocumentoBaixaCR",
      label: "FgTrocaTipoDocumentoBaixaCR",
      name: "FgTrocaTipoDocumentoBaixaCR",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgEfetuaBaixaExtrato",
      label: "FgEfetuaBaixaExtrato",
      name: "FgEfetuaBaixaExtrato",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgComissaoItem",
      label: "FgComissaoItem",
      name: "FgComissaoItem",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgLoteObrigatorioOP",
      label: "FgLoteObrigatorioOP",
      name: "FgLoteObrigatorioOP",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPedSaidaSugestao",
      label: "FgPedSaidaSugestao",
      name: "FgPedSaidaSugestao",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPedEntradaSugestao",
      label: "FgPedEntradaSugestao",
      name: "FgPedEntradaSugestao",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgDescontoPgto",
      label: "FgDescontoPgto",
      name: "FgDescontoPgto",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgProducaoParcial",
      label: "FgProducaoParcial",
      name: "FgProducaoParcial",
      typeField: "string",
      size: 1,
    },
    {
      field: "CaminhoePharma",
      label: "CaminhoePharma",
      name: "CaminhoePharma",
      typeField: "string",
      size: 128,
    },
    {
      field: "FgBloqueiaCliente",
      label: "FgBloqueiaCliente",
      name: "FgBloqueiaCliente",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgCalculoAutomatico",
      label: "FgCalculoAutomatico",
      name: "FgCalculoAutomatico",
      typeField: "string",
      size: 1,
    },
    {
      field: "QtdeMeses",
      label: "QtdeMeses",
      name: "QtdeMeses",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Multiplicador",
      label: "Multiplicador",
      name: "Multiplicador",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "FgMultiplasNOP",
      label: "FgMultiplasNOP",
      name: "FgMultiplasNOP",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgClienteImpressaoNF",
      label: "FgClienteImpressaoNF",
      name: "FgClienteImpressaoNF",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgObrigaDadosPedido",
      label: "FgObrigaDadosPedido",
      name: "FgObrigaDadosPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "MsgPedidoCompra",
      label: "MsgPedidoCompra",
      name: "MsgPedidoCompra",
      typeField: "string",
      size: 80,
    },
    {
      field: "FgAtendeParcialSaida",
      label: "FgAtendeParcialSaida",
      name: "FgAtendeParcialSaida",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgImprimeContatoPedidoEntrada",
      label: "FgImprimeContatoPedidoEntrada",
      name: "FgImprimeContatoPedidoEntrada",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgImprimeMsgPublicitaria",
      label: "FgImprimeMsgPublicitaria",
      name: "FgImprimeMsgPublicitaria",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgImprimeCdReferencia",
      label: "FgImprimeCdReferencia",
      name: "FgImprimeCdReferencia",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgImpCdProdPedidoModDesc",
      label: "FgImpCdProdPedidoModDesc",
      name: "FgImpCdProdPedidoModDesc",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgImprimeDescricaoCompleta",
      label: "FgImprimeDescricaoCompleta",
      name: "FgImprimeDescricaoCompleta",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgImprimeDataHoraNF",
      label: "FgImprimeDataHoraNF",
      name: "FgImprimeDataHoraNF",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgAtualizaStatusPedido",
      label: "FgAtualizaStatusPedido",
      name: "FgAtualizaStatusPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgConsideraTaxaEntregaComoFrete",
      label: "FgConsideraTaxaEntregaComoFrete",
      name: "FgConsideraTaxaEntregaComoFrete",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgImpLinhaSeparadora",
      label: "FgImpLinhaSeparadora",
      name: "FgImpLinhaSeparadora",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgDadosCadastrais",
      label: "FgDadosCadastrais",
      name: "FgDadosCadastrais",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPotencialCompra",
      label: "FgPotencialCompra",
      name: "FgPotencialCompra",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgObrigaLctoBancarioCP",
      label: "FgObrigaLctoBancarioCP",
      name: "FgObrigaLctoBancarioCP",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgNFe",
      label: "FgNFe",
      name: "FgNFe",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgSenhaGerEmiOrc",
      label: "FgSenhaGerEmiOrc",
      name: "FgSenhaGerEmiOrc",
      typeField: "string",
      size: 1,
    },
    {
      field: "DtFechamentoPeriodo",
      label: "DtFechamentoPeriodo",
      name: "DtFechamentoPeriodo",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "FgDevolucaoControlado",
      label: "FgDevolucaoControlado",
      name: "FgDevolucaoControlado",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgEmissaoChequeFornecedor",
      label: "FgEmissaoChequeFornecedor",
      name: "FgEmissaoChequeFornecedor",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgRecalculoCliente",
      label: "FgRecalculoCliente",
      name: "FgRecalculoCliente",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgRedutorComissaoItem",
      label: "FgRedutorComissaoItem",
      name: "FgRedutorComissaoItem",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPromocaoManual",
      label: "FgPromocaoManual",
      name: "FgPromocaoManual",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgVlLiquidoSelProduto",
      label: "FgVlLiquidoSelProduto",
      name: "FgVlLiquidoSelProduto",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPlanoContas",
      label: "FgPlanoContas",
      name: "FgPlanoContas",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgLiberaDescOrcamento",
      label: "FgLiberaDescOrcamento",
      name: "FgLiberaDescOrcamento",
      typeField: "string",
      size: 1,
    },
    {
      field: "ExibeEstoqueItensPedido",
      label: "ExibeEstoqueItensPedido",
      name: "ExibeEstoqueItensPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgAlteraClienteNF",
      label: "FgAlteraClienteNF",
      name: "FgAlteraClienteNF",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgDestacaFaltaEstoquePed",
      label: "FgDestacaFaltaEstoquePed",
      name: "FgDestacaFaltaEstoquePed",
      typeField: "string",
      size: 1,
    },
    {
      field: "QtdeCaracteresObsNota",
      label: "QtdeCaracteresObsNota",
      name: "QtdeCaracteresObsNota",
      typeField: "int",
      size: 2,
    },
    {
      field: "FgExibeEstoqueFiliaisSelecao",
      label: "FgExibeEstoqueFiliaisSelecao",
      name: "FgExibeEstoqueFiliaisSelecao",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgBloqueiotroco",
      label: "FgBloqueiotroco",
      name: "FgBloqueiotroco",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgFechamentoDinheiro",
      label: "FgFechamentoDinheiro",
      name: "FgFechamentoDinheiro",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPermiteInativoOrcamentos",
      label: "FgPermiteInativoOrcamentos",
      name: "FgPermiteInativoOrcamentos",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgAlteraDescricaoProduto",
      label: "FgAlteraDescricaoProduto",
      name: "FgAlteraDescricaoProduto",
      typeField: "string",
      size: 1,
    },
    {
      field: "CstIPI",
      label: "CstIPI",
      name: "CstIPI",
      typeField: "string",
      size: 2,
    },
    {
      field: "CstPIS",
      label: "CstPIS",
      name: "CstPIS",
      typeField: "string",
      size: 2,
    },
    {
      field: "CstCOFINS",
      label: "CstCOFINS",
      name: "CstCOFINS",
      typeField: "string",
      size: 2,
    },
    {
      field: "CaminhoNFe",
      label: "CaminhoNFe",
      name: "CaminhoNFe",
      typeField: "string",
      size: 300,
    },
    {
      field: "CertificadoNFe",
      label: "CertificadoNFe",
      name: "CertificadoNFe",
      typeField: "string",
      size: 600,
    },
    {
      field: "UsuarioNFe",
      label: "UsuarioNFe",
      name: "UsuarioNFe",
      typeField: "string",
      size: 300,
    },
    {
      field: "SenhaNFe",
      label: "SenhaNFe",
      name: "SenhaNFe",
      typeField: "string",
      size: 300,
    },
    {
      field: "ProxyNFe",
      label: "ProxyNFe",
      name: "ProxyNFe",
      typeField: "string",
      size: 300,
    },
    {
      field: "LicencaNFe",
      label: "LicencaNFe",
      name: "LicencaNFe",
      typeField: "string",
      size: 300,
    },
    {
      field: "Quantidade",
      label: "Quantidade",
      name: "Quantidade",
      typeField: "int",
      size: 4,
    },
    {
      field: "ConfLib",
      label: "ConfLib",
      name: "ConfLib",
      typeField: "string",
      size: 256,
    },
    {
      field: "QtdeLimite",
      label: "QtdeLimite",
      name: "QtdeLimite",
      typeField: "int",
      size: 2,
    },
    {
      field: "FgPreVendaSimplificada",
      label: "FgPreVendaSimplificada",
      name: "FgPreVendaSimplificada",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgSelecaoInformacaoAdicional",
      label: "FgSelecaoInformacaoAdicional",
      name: "FgSelecaoInformacaoAdicional",
      typeField: "string",
      size: 1,
    },
    {
      field: "FonteMediaImposto",
      label: "FonteMediaImposto",
      name: "FonteMediaImposto",
      typeField: "string",
      size: 32,
    },
    {
      field: "FgMantemDigitacaoDescricao",
      label: "FgMantemDigitacaoDescricao",
      name: "FgMantemDigitacaoDescricao",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgExibeEstOrcamento",
      label: "FgExibeEstOrcamento",
      name: "FgExibeEstOrcamento",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgConsisteInscricao",
      label: "FgConsisteInscricao",
      name: "FgConsisteInscricao",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgImprimeComprovanteMovCredito",
      label: "FgImprimeComprovanteMovCredito",
      name: "FgImprimeComprovanteMovCredito",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgConfereLoteIndividual",
      label: "FgConfereLoteIndividual",
      name: "FgConfereLoteIndividual",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPedidoOrdemFaturamento",
      label: "FgPedidoOrdemFaturamento",
      name: "FgPedidoOrdemFaturamento",
      typeField: "string",
      size: 1,
    },
    {
      field: "FonteCodigoBarraBoleto",
      label: "FonteCodigoBarraBoleto",
      name: "FonteCodigoBarraBoleto",
      typeField: "string",
      size: 32,
    },
    {
      field: "FgHistoricoSTEntrada",
      label: "FgHistoricoSTEntrada",
      name: "FgHistoricoSTEntrada",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgMostraDRE",
      label: "FgMostraDRE",
      name: "FgMostraDRE",
      typeField: "string",
      size: 1,
    },
    {
      field: "MsgCondFornecimento",
      label: "MsgCondFornecimento",
      name: "MsgCondFornecimento",
      typeField: "string",
      size: 1024,
    },
    {
      field: "FgBloqueiaCreditoCliente",
      label: "FgBloqueiaCreditoCliente",
      name: "FgBloqueiaCreditoCliente",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgDemonstraCustoPreVenda",
      label: "FgDemonstraCustoPreVenda",
      name: "FgDemonstraCustoPreVenda",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgDemonstraPedidoEntradaPreVenda",
      label: "FgDemonstraPedidoEntradaPreVenda",
      name: "FgDemonstraPedidoEntradaPreVenda",
      typeField: "string",
      size: 1,
    },
    {
      field: "CdClientePadraoVidalink",
      label: "CdClientePadraoVidalink",
      name: "CdClientePadraoVidalink",
      typeField: "int",
      size: 4,
    },
    {
      field: "CdVendedorPadraoVidalink",
      label: "CdVendedorPadraoVidalink",
      name: "CdVendedorPadraoVidalink",
      typeField: "int",
      size: 4,
    },
    {
      field: "FgRecuperacaoST",
      label: "FgRecuperacaoST",
      name: "FgRecuperacaoST",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgManutencaoGNRE",
      label: "FgManutencaoGNRE",
      name: "FgManutencaoGNRE",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgVendaConsultorio",
      label: "FgVendaConsultorio",
      name: "FgVendaConsultorio",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgAlteraCPBaixado",
      label: "FgAlteraCPBaixado",
      name: "FgAlteraCPBaixado",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgEnviarPFIMS",
      label: "FgEnviarPFIMS",
      name: "FgEnviarPFIMS",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgControlarChequesTerceiros",
      label: "FgControlarChequesTerceiros",
      name: "FgControlarChequesTerceiros",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgDuplicaBaixaCR",
      label: "FgDuplicaBaixaCR",
      name: "FgDuplicaBaixaCR",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgBalancaCaminhao",
      label: "FgBalancaCaminhao",
      name: "FgBalancaCaminhao",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgSomenteClientesVendedor",
      label: "FgSomenteClientesVendedor",
      name: "FgSomenteClientesVendedor",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgLctoFinanceiroOutrasFormas",
      label: "FgLctoFinanceiroOutrasFormas",
      name: "FgLctoFinanceiroOutrasFormas",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgDespesasPedido",
      label: "FgDespesasPedido",
      name: "FgDespesasPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPharmaLink",
      label: "FgPharmaLink",
      name: "FgPharmaLink",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgCalculoImpostoLitros",
      label: "FgCalculoImpostoLitros",
      name: "FgCalculoImpostoLitros",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgObrigaNCMProduto",
      label: "FgObrigaNCMProduto",
      name: "FgObrigaNCMProduto",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgObrigaDadosNFeCliente",
      label: "FgObrigaDadosNFeCliente",
      name: "FgObrigaDadosNFeCliente",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgDetalhaCartao",
      label: "FgDetalhaCartao",
      name: "FgDetalhaCartao",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgVencimentoTituloDiaUtil",
      label: "FgVencimentoTituloDiaUtil",
      name: "FgVencimentoTituloDiaUtil",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgBaixaAgrupadaSemJuros",
      label: "FgBaixaAgrupadaSemJuros",
      name: "FgBaixaAgrupadaSemJuros",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgImprimeEnderecoPrateleira",
      label: "FgImprimeEnderecoPrateleira",
      name: "FgImprimeEnderecoPrateleira",
      typeField: "string",
      size: 1,
    },
    {
      field: "SerieSelecaoInicial",
      label: "SerieSelecaoInicial",
      name: "SerieSelecaoInicial",
      typeField: "string",
      size: 3,
    },
    {
      field: "SerieSelecaoFinal",
      label: "SerieSelecaoFinal",
      name: "SerieSelecaoFinal",
      typeField: "string",
      size: 3,
    },
    {
      field: "FgAlertaAniversariantes",
      label: "FgAlertaAniversariantes",
      name: "FgAlertaAniversariantes",
      typeField: "string",
      size: 3,
    },
    {
      field: "FgFreteCompoeCalculoCustoMedio",
      label: "FgFreteCompoeCalculoCustoMedio",
      name: "FgFreteCompoeCalculoCustoMedio",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgImprimeObsPedidoInfComplementar",
      label: "FgImprimeObsPedidoInfComplementar",
      name: "FgImprimeObsPedidoInfComplementar",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgCancelaNotaPedido",
      label: "FgCancelaNotaPedido",
      name: "FgCancelaNotaPedido",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgGeraArquivoSerasa",
      label: "FgGeraArquivoSerasa",
      name: "FgGeraArquivoSerasa",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgEstornoDtRecebimento",
      label: "FgEstornoDtRecebimento",
      name: "FgEstornoDtRecebimento",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgBloqueioVendaInadimplentes",
      label: "FgBloqueioVendaInadimplentes",
      name: "FgBloqueioVendaInadimplentes",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgObrigaCESTProduto",
      label: "FgObrigaCESTProduto",
      name: "FgObrigaCESTProduto",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgChequeCompensarLimiteCredito",
      label: "FgChequeCompensarLimiteCredito",
      name: "FgChequeCompensarLimiteCredito",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPrecoCliente",
      label: "FgPrecoCliente",
      name: "FgPrecoCliente",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgBloqueiaCadastroClienteCpfCnpj",
      label: "FgBloqueiaCadastroClienteCpfCnpj",
      name: "FgBloqueiaCadastroClienteCpfCnpj",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgApresentaAbaMeta",
      label: "FgApresentaAbaMeta",
      name: "FgApresentaAbaMeta",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgVendaMestreGrade",
      label: "FgVendaMestreGrade",
      name: "FgVendaMestreGrade",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgBuscaCdProdutoXML",
      label: "FgBuscaCdProdutoXML",
      name: "FgBuscaCdProdutoXML",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgBloqueioVendaProdutoFilial",
      label: "FgBloqueioVendaProdutoFilial",
      name: "FgBloqueioVendaProdutoFilial",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgViaUnicaPreVendaSimplificada",
      label: "FgViaUnicaPreVendaSimplificada",
      name: "FgViaUnicaPreVendaSimplificada",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgCobBancTipoDocumento",
      label: "FgCobBancTipoDocumento",
      name: "FgCobBancTipoDocumento",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgBloqueiaLancamentoRetroativo",
      label: "FgBloqueiaLancamentoRetroativo",
      name: "FgBloqueiaLancamentoRetroativo",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgCodigoAuxiliarProduto",
      label: "FgCodigoAuxiliarProduto",
      name: "FgCodigoAuxiliarProduto",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgBuscaAssocXML",
      label: "FgBuscaAssocXML",
      name: "FgBuscaAssocXML",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgConciliaCNPJImportXML",
      label: "FgConciliaCNPJImportXML",
      name: "FgConciliaCNPJImportXML",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPrecoFabricaCompras",
      label: "FgPrecoFabricaCompras",
      name: "FgPrecoFabricaCompras",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgApresentaValorDinheiroSangria",
      label: "FgApresentaValorDinheiroSangria",
      name: "FgApresentaValorDinheiroSangria",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgApresentaPesoBruto",
      label: "FgApresentaPesoBruto",
      name: "FgApresentaPesoBruto",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgSomenteAssocForn",
      label: "FgSomenteAssocForn",
      name: "FgSomenteAssocForn",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgPraticaPrecoAtacadoQtde",
      label: "FgPraticaPrecoAtacadoQtde",
      name: "FgPraticaPrecoAtacadoQtde",
      typeField: "string",
      size: 1,
    },
    {
      field: "IdRelease",
      label: "IdRelease",
      name: "IdRelease",
      typeField: "string",
      size: 32,
    },
    {
      field: "FgConsideraCdInterno",
      label: "FgConsideraCdInterno",
      name: "FgConsideraCdInterno",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgDiferencaUTrib",
      label: "FgDiferencaUTrib",
      name: "FgDiferencaUTrib",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgComanda",
      label: "FgComanda",
      name: "FgComanda",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgMultiplosPedidosNFe",
      label: "FgMultiplosPedidosNFe",
      name: "FgMultiplosPedidosNFe",
      typeField: "string",
      size: 1,
    },
    {
      field: "DtIniCustoMedioDev",
      label: "DtIniCustoMedioDev",
      name: "DtIniCustoMedioDev",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "FgOrdemServico",
      label: "FgOrdemServico",
      name: "FgOrdemServico",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgTicketVale",
      label: "FgTicketVale",
      name: "FgTicketVale",
      typeField: "string",
      size: 1,
    },
    {
      field: "DiasContraVale",
      label: "DiasContraVale",
      name: "DiasContraVale",
      typeField: "int",
      size: 5,
    },
    {
      field: "FgDevolucaoSimplificada",
      label: "FgDevolucaoSimplificada",
      name: "FgDevolucaoSimplificada",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgImpComplemento",
      label: "FgImpComplemento",
      name: "FgImpComplemento",
      typeField: "string",
      size: 1,
    },
    {
      field: "IdCSRT",
      label: "IdCSRT",
      name: "IdCSRT",
      typeField: "string",
      size: 16,
    },
    {
      field: "CSRT",
      label: "CSRT",
      name: "CSRT",
      typeField: "string",
      size: 128,
    },
    {
      field: "MascaraPlanoContas1",
      label: "MascaraPlanoContas1",
      name: "MascaraPlanoContas1",
      typeField: "int",
      size: 5,
    },
    {
      field: "MascaraPlanoContas2",
      label: "MascaraPlanoContas2",
      name: "MascaraPlanoContas2",
      typeField: "int",
      size: 5,
    },
    {
      field: "MascaraPlanoContas3",
      label: "MascaraPlanoContas3",
      name: "MascaraPlanoContas3",
      typeField: "int",
      size: 5,
    },
    {
      field: "MascaraPlanoContas4",
      label: "MascaraPlanoContas4",
      name: "MascaraPlanoContas4",
      typeField: "int",
      size: 5,
    },
    {
      field: "MascaraPlanoContas5",
      label: "MascaraPlanoContas5",
      name: "MascaraPlanoContas5",
      typeField: "int",
      size: 5,
    },
    {
      field: "MascaraPlanoContas6",
      label: "MascaraPlanoContas6",
      name: "MascaraPlanoContas6",
      typeField: "int",
      size: 5,
    },
    {
      field: "MascaraPlanoContas7",
      label: "MascaraPlanoContas7",
      name: "MascaraPlanoContas7",
      typeField: "int",
      size: 5,
    },
    {
      field: "DtUltimoBackup",
      label: "DtUltimoBackup",
      name: "DtUltimoBackup",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DtUltimaNotificacaoBackup",
      label: "DtUltimaNotificacaoBackup",
      name: "DtUltimaNotificacaoBackup",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "NumDiasNotificacaoBackup",
      label: "NumDiasNotificacaoBackup",
      name: "NumDiasNotificacaoBackup",
      typeField: "int",
      size: 5,
    },
    {
      field: "FgDiferencaUTribSomenteUFEX",
      label: "FgDiferencaUTribSomenteUFEX",
      name: "FgDiferencaUTribSomenteUFEX",
      typeField: "string",
      size: 1,
    },
    {
      field: "DiasHistorico",
      label: "DiasHistorico",
      name: "DiasHistorico",
      typeField: "int",
      size: 4,
    },
    {
      field: "PercRecompensa",
      label: "PercRecompensa",
      name: "PercRecompensa",
      typeField: "int",
      size: 5,
      scale: 2,
    },
    {
      field: "FgClubeCompras",
      label: "FgClubeCompras",
      name: "FgClubeCompras",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgOrdemSeparacao",
      label: "FgOrdemSeparacao",
      name: "FgOrdemSeparacao",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgEnderecoEntrega",
      label: "FgEnderecoEntrega",
      name: "FgEnderecoEntrega",
      typeField: "string",
      size: 1,
    },
    {
      field: "MesesXML",
      label: "MesesXML",
      name: "MesesXML",
      typeField: "int",
      size: 5,
    },
  ],
};
