import { TTable } from "../../../../types/model";

export const ConfiguracaoSITEF: TTable = {
  database: "plano",
  table: "ConfiguracaoSITEF",
  fields: [
    {
      field: "FgAtivo",
      label: "FgAtivo",
      name: "FgAtivo",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "Host1",
      label: "Host1",
      name: "Host1",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Host2",
      label: "Host2",
      name: "Host2",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Host3",
      label: "Host3",
      name: "Host3",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Host4",
      label: "Host4",
      name: "Host4",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Loja",
      label: "Loja",
      name: "Loja",
      typeField: "string",
      size: 8,
      allowNull: false,
    },
    {
      field: "MsgPINPAD",
      label: "MsgPINPAD",
      name: "MsgPINPAD",
      typeField: "string",
      size: 512,
      allowNull: false,
    },
    {
      field: "CaminhoSITEF",
      label: "CaminhoSITEF",
      name: "CaminhoSITEF",
      typeField: "string",
      size: 512,
      allowNull: false,
    },
    {
      field: "ContraSenha",
      label: "ContraSenha",
      name: "ContraSenha",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "ConfiguracaoSITEF_id",
      typeField: "int",
      size: 9,
      primaryKey: true,
      allowNull: false,
    },
  ],
};
