import { TTableDef } from "@/types/model";

export const ControladosPedido: TTableDef = {
  database: "plano",
  table: "ControladosPedido",
  fields: [
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "NumDocumento",
      label: "NumDocumento",
      name: "NumDocumento",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "CdProduto",
      label: "CdProduto",
      name: "CdProduto",
      typeField: "string",
      size: 15,
      allowNull: false,
    },
    {
      field: "Sequencia",
      label: "Sequencia",
      name: "Sequencia",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "QtdePrescrita",
      label: "QtdePrescrita",
      name: "QtdePrescrita",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "QtdeVendida",
      label: "QtdeVendida",
      name: "QtdeVendida",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "CRM",
      label: "CRM",
      name: "CRM",
      typeField: "string",
      size: 16,
      allowNull: false,
    },
    {
      field: "DtReceita",
      label: "DtReceita",
      name: "DtReceita",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "NumReceita",
      label: "NumReceita",
      name: "NumReceita",
      typeField: "int",
      size: 4,
    },
    {
      field: "CdComprador",
      label: "CdComprador",
      name: "CdComprador",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "NomeComprador",
      label: "NomeComprador",
      name: "NomeComprador",
      typeField: "string",
      size: 70,
    },
    {
      field: "Endereco",
      label: "Endereco",
      name: "Endereco",
      typeField: "string",
      size: 70,
    },
    {
      field: "NumIdentidade",
      label: "NumIdentidade",
      name: "NumIdentidade",
      typeField: "string",
      size: 20,
    },
    {
      field: "Telefone",
      label: "Telefone",
      name: "Telefone",
      typeField: "string",
      size: 20,
    },
    {
      field: "TipoReceita",
      label: "TipoReceita",
      name: "TipoReceita",
      typeField: "string",
      size: 2,
    },
  ],
};
