import { TTable } from "../../../../types/model";

export const ControleCheque: TTable = {
  database: "plano",
  table: "ControleCheque",
  fields: [
    {
      field: "CdControleCheque",
      label: "CdControleCheque",
      name: "ControleCheque_id",
      typeField: "int",
      size: 4,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "CdCliente",
      label: "CdCliente",
      name: "CdCliente",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "CdFornecedor",
      label: "CdFornecedor",
      name: "CdFornecedor",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "CdBanco",
      label: "CdBanco",
      name: "CdBanco",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "CdAgencia",
      label: "CdAgencia",
      name: "CdAgencia",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "NrConta",
      label: "NrConta",
      name: "NrConta",
      typeField: "string",
      size: 10,
      allowNull: false,
    },
    {
      field: "NrCheque",
      label: "NrCheque",
      name: "NrCheque",
      typeField: "string",
      size: 10,
      allowNull: false,
    },
    {
      field: "NmEmitente",
      label: "NmEmitente",
      name: "NmEmitente",
      typeField: "string",
      size: 80,
      allowNull: false,
    },
    {
      field: "Valor",
      label: "Valor",
      name: "Valor",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "CdStatus",
      label: "CdStatus",
      name: "CdStatus",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "Data",
      label: "Data",
      name: "Data",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "Numdoc",
      label: "Numdoc",
      name: "Numdoc",
      typeField: "int",
      size: 4,
    },
    {
      field: "SeqDoc",
      label: "SeqDoc",
      name: "SeqDoc",
      typeField: "int",
      size: 2,
    },
  ],
};
