import { TTableDef } from "@/types/model";

export const ContasReceberChequeFornecedor: TTableDef = {
  database: "plano",
  table: "ContasReceberChequeFornecedor",
  fields: [
    {
      field: "CdEmpresa",
      label: "CdEmpresa",
      name: "CdEmpresa",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "NumDocumento",
      label: "NumDocumento",
      name: "NumDocumento",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Serie",
      label: "Serie",
      name: "Serie",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "Modelo",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "SiglaDocumento",
      label: "SiglaDocumento",
      name: "SiglaDocumento",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "ItemDocumento",
      label: "ItemDocumento",
      name: "ItemDocumento",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "CdEmpresaContasPagar",
      label: "CdEmpresaContasPagar",
      name: "CdEmpresaContasPagar",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "CdFilialContasPagar",
      label: "CdFilialContasPagar",
      name: "CdFilialContasPagar",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "CdFornecedorContasPagar",
      label: "CdFornecedorContasPagar",
      name: "CdFornecedorContasPagar",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "NumDocumentoContasPagar",
      label: "NumDocumentoContasPagar",
      name: "NumDocumentoContasPagar",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "SerieContasPagar",
      label: "SerieContasPagar",
      name: "SerieContasPagar",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "ModeloContasPagar",
      label: "ModeloContasPagar",
      name: "ModeloContasPagar",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "ItemDocumentoContasPagar",
      label: "ItemDocumentoContasPagar",
      name: "ItemDocumentoContasPagar",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "DtInclusao",
      label: "DtInclusao",
      name: "DtInclusao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "DtUltAlteracao",
      label: "DtUltAlteracao",
      name: "DtUltAlteracao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
  ],
};
