import { TTable } from "../../../../types/model";

export const ContratoAluguelContagemMestre: TTable = {
  database: "plano",
  table: "ContratoAluguelContagemMestre",
  fields: [
    {
      field: "CdCliente",
      label: "CdCliente",
      name: "CdCliente",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "DiaContr",
      label: "DiaContr",
      name: "DiaContr",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "DtContagem",
      label: "DtContagem",
      name: "DtContagem",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "UsuarioContagem",
      label: "UsuarioContagem",
      name: "UsuarioContagem",
      typeField: "string",
      size: 10,
      allowNull: false,
    },
    {
      field: "VlFranquia",
      label: "VlFranquia",
      name: "VlFranquia",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "QtdeFranquia",
      label: "QtdeFranquia",
      name: "QtdeFranquia",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "QtdeContada",
      label: "QtdeContada",
      name: "QtdeContada",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlUnitExcedente",
      label: "VlUnitExcedente",
      name: "VlUnitExcedente",
      typeField: "float",
      size: 8,
      allowNull: false,
    },
    {
      field: "NumNota",
      label: "NumNota",
      name: "NumNota",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "Serie",
      label: "Serie",
      name: "Serie",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "UsuarioNota",
      label: "UsuarioNota",
      name: "UsuarioNota",
      typeField: "string",
      size: 10,
      allowNull: false,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "Modelo",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
  ],
};
