import { TTableDef } from "../../../../types/model";

export const ContasReceberCheque: TTableDef = {
  database: "plano",
  table: "ContasReceberCheque",
  fields: [
    {
      field: "CdEmpresa",
      label: "CdEmpresa",
      name: "CdEmpresa",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "NumDocumento",
      label: "NumDocumento",
      name: "NumDocumento",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Serie",
      label: "Serie",
      name: "Serie",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "Modelo",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "SiglaDocumento",
      label: "SiglaDocumento",
      name: "SiglaDocumento",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "ItemDocumento",
      label: "ItemDocumento",
      name: "ItemDocumento",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "CdBancoCheque",
      label: "CdBancoCheque",
      name: "CdBancoCheque",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "CdAgenciaCheque",
      label: "CdAgenciaCheque",
      name: "CdAgenciaCheque",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "NumContaCheque",
      label: "NumContaCheque",
      name: "NumContaCheque",
      typeField: "string",
      size: 16,
      allowNull: false,
    },
    {
      field: "NumCheque",
      label: "NumCheque",
      name: "NumCheque",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "NmEmitenteCheque",
      label: "NmEmitenteCheque",
      name: "NmEmitenteCheque",
      typeField: "string",
      size: 80,
      allowNull: false,
    },
    {
      field: "TarjaCheque",
      label: "TarjaCheque",
      name: "TarjaCheque",
      typeField: "string",
      size: 32,
      allowNull: false,
    },
    {
      field: "FgStatusCheque",
      label: "FgStatusCheque",
      name: "FgStatusCheque",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "DtInclusao",
      label: "DtInclusao",
      name: "DtInclusao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "DtUltAlteracao",
      label: "DtUltAlteracao",
      name: "DtUltAlteracao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
  ],
};
