import { TTableDef } from "@mono/types/model";

export const CustoMedio: TTableDef = {
  database: "plano",
  table: "CustoMedio",
  fields: [
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "CdProduto",
      label: "CdProduto",
      name: "CdProduto",
      typeField: "string",
      size: 15,
      allowNull: false,
    },
    {
      field: "DtRef",
      label: "DtRef",
      name: "DtRef",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "Sequencia",
      label: "Sequencia",
      name: "Sequencia",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "QtdeAnterior",
      label: "QtdeAnterior",
      name: "QtdeAnterior",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlCustoMedioAnterior",
      label: "VlCustoMedioAnterior",
      name: "VlCustoMedioAnterior",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "NumDoc",
      label: "NumDoc",
      name: "NumDoc",
      typeField: "int",
      size: 4,
    },
    {
      field: "Serie",
      label: "Serie",
      name: "Serie",
      typeField: "string",
      size: 3,
    },
    {
      field: "CdFornecedor",
      label: "CdFornecedor",
      name: "CdFornecedor",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "QtdeEntrada",
      label: "QtdeEntrada",
      name: "QtdeEntrada",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlCustoEntrada",
      label: "VlCustoEntrada",
      name: "VlCustoEntrada",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "QtdeSaldo",
      label: "QtdeSaldo",
      name: "QtdeSaldo",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlCustoMedio",
      label: "VlCustoMedio",
      name: "VlCustoMedio",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "Modelo",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "TipoEmitente",
      label: "TipoEmitente",
      name: "TipoEmitente",
      typeField: "string",
      size: 1,
    },
  ],
};
