import { TTableDef } from "@/types/model";

export const Deposito: TTableDef = {
  database: "plano",
  table: "Deposito",
  fields: [
    {
      field: "CdBanco",
      label: "CdBanco",
      name: "CdBanco",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "CdAgencia",
      label: "CdAgencia",
      name: "CdAgencia",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "NumConta",
      label: "NumConta",
      name: "NumConta",
      typeField: "string",
      size: 12,
      allowNull: false,
    },
    {
      field: "DtDeposito",
      label: "DtDeposito",
      name: "DtDeposito",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "SeqDep",
      label: "SeqDep",
      name: "SeqDep",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "Finalidade",
      label: "Finalidade",
      name: "Finalidade",
      typeField: "string",
      size: 1024,
    },
    {
      field: "VlDinheiro",
      label: "VlDinheiro",
      name: "VlDinheiro",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlChequePraca",
      label: "VlChequePraca",
      name: "VlChequePraca",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "VlChequeOutros",
      label: "VlChequeOutros",
      name: "VlChequeOutros",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "CdFilialAssociada",
      label: "CdFilialAssociada",
      name: "CdFilialAssociada",
      typeField: "int",
      size: 4,
    },
    {
      field: "FgSituacao",
      label: "FgSituacao",
      name: "FgSituacao",
      typeField: "string",
      size: 1,
    },
  ],
};
