import { TTableDef } from "../../../../types/model";

export const ePharmaConvenios: TTableDef = {
  database: "plano",
  table: "ePharmaConvenios",
  fields: [
    {
      field: "CdConvenio",
      label: "CdConvenio",
      name: "ePharmaConvenios_id",
      typeField: "float",
      size: 8,
      scale: 4,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "Nmconvenio",
      label: "Nmconvenio",
      name: "Nmconvenio",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "Rec",
      label: "Rec",
      name: "Rec",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TipoConvenio",
      label: "TipoConvenio",
      name: "TipoConvenio",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TipoPreco",
      label: "TipoPreco",
      name: "TipoPreco",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "FgMenorPreco",
      label: "FgMenorPreco",
      name: "FgMenorPreco",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgAutorizacao",
      label: "FgAutorizacao",
      name: "FgAutorizacao",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgAtivo",
      label: "FgAtivo",
      name: "FgAtivo",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
  ],
};
