import { TTableDef } from "@mono/types/model";

export const FilialSugestaoCadProduto: TTableDef = {
  database: "plano",
  table: "FilialSugestaoCadProduto",
  fields: [
    {
      field: "CdEmpresa",
      label: "CdEmpresa",
      name: "CdEmpresa",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "TipoTributacaoICMS",
      label: "TipoTributacaoICMS",
      name: "TipoTributacaoICMS",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "AliquotaICMS",
      label: "AliquotaICMS",
      name: "AliquotaICMS",
      typeField: "string",
      size: 5,
      allowNull: false,
    },
    {
      field: "PercReducaoICMSST",
      label: "PercReducaoICMSST",
      name: "PercReducaoICMSST",
      typeField: "string",
      size: 5,
      allowNull: false,
    },
    {
      field: "FgReducaoICMSContribuinte",
      label: "FgReducaoICMSContribuinte",
      name: "FgReducaoICMSContribuinte",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgReducaoICMSNaoContribuinte",
      label: "FgReducaoICMSNaoContribuinte",
      name: "FgReducaoICMSNaoContribuinte",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgCompoeDeducaoICMS",
      label: "FgCompoeDeducaoICMS",
      name: "FgCompoeDeducaoICMS",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgIsentoICMSECF",
      label: "FgIsentoICMSECF",
      name: "FgIsentoICMSECF",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgIsentoSubstituido030",
      label: "FgIsentoSubstituido030",
      name: "FgIsentoSubstituido030",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "ModDeterminacaoBCICMS",
      label: "ModDeterminacaoBCICMS",
      name: "ModDeterminacaoBCICMS",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "ModDeterminacaoBCICMSSub",
      label: "ModDeterminacaoBCICMSSub",
      name: "ModDeterminacaoBCICMSSub",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "CSTIPIEntrada",
      label: "CSTIPIEntrada",
      name: "CSTIPIEntrada",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "AliquotaIPIEntrada",
      label: "AliquotaIPIEntrada",
      name: "AliquotaIPIEntrada",
      typeField: "string",
      size: 5,
      allowNull: false,
    },
    {
      field: "CSTIPISaida",
      label: "CSTIPISaida",
      name: "CSTIPISaida",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "AliquotaIPISaida",
      label: "AliquotaIPISaida",
      name: "AliquotaIPISaida",
      typeField: "string",
      size: 5,
      allowNull: false,
    },
    {
      field: "CdEnquadramentoIPI",
      label: "CdEnquadramentoIPI",
      name: "CdEnquadramentoIPI",
      typeField: "string",
      size: 8,
      allowNull: false,
    },
    {
      field: "ClasseEnquadramentoIPI",
      label: "ClasseEnquadramentoIPI",
      name: "ClasseEnquadramentoIPI",
      typeField: "string",
      size: 8,
      allowNull: false,
    },
    {
      field: "CdSeloIPI",
      label: "CdSeloIPI",
      name: "CdSeloIPI",
      typeField: "string",
      size: 16,
      allowNull: false,
    },
    {
      field: "CSTPISEntrada",
      label: "CSTPISEntrada",
      name: "CSTPISEntrada",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "AliquotaPISEntrada",
      label: "AliquotaPISEntrada",
      name: "AliquotaPISEntrada",
      typeField: "string",
      size: 5,
      allowNull: false,
    },
    {
      field: "CSTPISSaida",
      label: "CSTPISSaida",
      name: "CSTPISSaida",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "AliquotaPISSaida",
      label: "AliquotaPISSaida",
      name: "AliquotaPISSaida",
      typeField: "string",
      size: 5,
      allowNull: false,
    },
    {
      field: "CSTCOFINSEntrada",
      label: "CSTCOFINSEntrada",
      name: "CSTCOFINSEntrada",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "AliquotaCOFINSEntrada",
      label: "AliquotaCOFINSEntrada",
      name: "AliquotaCOFINSEntrada",
      typeField: "string",
      size: 5,
      allowNull: false,
    },
    {
      field: "CSTCOFINSSaida",
      label: "CSTCOFINSSaida",
      name: "CSTCOFINSSaida",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "AliquotaCOFINSSaida",
      label: "AliquotaCOFINSSaida",
      name: "AliquotaCOFINSSaida",
      typeField: "string",
      size: 5,
      allowNull: false,
    },
    {
      field: "FgCompoeBaseISS",
      label: "FgCompoeBaseISS",
      name: "FgCompoeBaseISS",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "AliquotaISS",
      label: "AliquotaISS",
      name: "AliquotaISS",
      typeField: "string",
      size: 5,
      allowNull: false,
    },
    {
      field: "CdServico",
      label: "CdServico",
      name: "CdServico",
      typeField: "string",
      size: 16,
      allowNull: false,
    },
    {
      field: "FgCompoeBlocoK",
      label: "FgCompoeBlocoK",
      name: "FgCompoeBlocoK",
      typeField: "string",
      size: 1,
    },
  ],
};
