import { TTableDef } from "@/types/model";

export const Funcionarios: TTableDef = {
  database: "plano",
  table: "Funcionarios",
  fields: [
    {
      field: "CdCliente",
      label: "CdCliente",
      name: "CdCliente",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "CdFuncionario",
      label: "CdFuncionario",
      name: "CdFuncionario",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "NmFuncionario",
      label: "NmFuncionario",
      name: "NmFuncionario",
      typeField: "string",
      size: 40,
    },
    {
      field: "Endereco",
      label: "Endereco",
      name: "Endereco",
      typeField: "string",
      size: 40,
    },
    {
      field: "Cidade",
      label: "Cidade",
      name: "Cidade",
      typeField: "string",
      size: 30,
    },
    {
      field: "Bairro",
      label: "Bairro",
      name: "Bairro",
      typeField: "string",
      size: 20,
    },
    {
      field: "Uf",
      label: "Uf",
      name: "Uf",
      typeField: "string",
      size: 2,
    },
    {
      field: "Cep",
      label: "Cep",
      name: "Cep",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "NumRg",
      label: "NumRg",
      name: "NumRg",
      typeField: "string",
      size: 15,
    },
    {
      field: "Telefone",
      label: "Telefone",
      name: "Telefone",
      typeField: "string",
      size: 15,
    },
    {
      field: "DtNasc",
      label: "DtNasc",
      name: "DtNasc",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "VlLimite",
      label: "VlLimite",
      name: "VlLimite",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "FgAtivo",
      label: "FgAtivo",
      name: "FgAtivo",
      typeField: "string",
      size: 1,
    },
    {
      field: "DtUltAlteracao",
      label: "DtUltAlteracao",
      name: "DtUltAlteracao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "FgExibeLimite",
      label: "FgExibeLimite",
      name: "FgExibeLimite",
      typeField: "string",
      size: 1,
    },
    {
      field: "Classificacao",
      label: "Classificacao",
      name: "Classificacao",
      typeField: "string",
      size: 30,
    },
    {
      field: "FgSubsidio",
      label: "FgSubsidio",
      name: "FgSubsidio",
      typeField: "string",
      size: 1,
    },
    {
      field: "NumAgencia",
      label: "NumAgencia",
      name: "NumAgencia",
      typeField: "string",
      size: 10,
    },
    {
      field: "NumConta",
      label: "NumConta",
      name: "NumConta",
      typeField: "string",
      size: 10,
    },
    {
      field: "NumDV",
      label: "NumDV",
      name: "NumDV",
      typeField: "string",
      size: 3,
    },
  ],
};
