import { TTableDef } from "@mono/types/model";

export const LancDiversos: TTableDef = {
  database: "plano",
  table: "LancDiversos",
  fields: [
    {
      field: "DtUltAlteracao",
      label: "DtUltAlteracao",
      name: "DtUltAlteracao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "TxFinalidade",
      label: "TxFinalidade",
      name: "TxFinalidade",
      typeField: "string",
      size: 1024,
    },
    {
      field: "CdBanco",
      label: "CdBanco",
      name: "CdBanco",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "CdAgencia",
      label: "CdAgencia",
      name: "CdAgencia",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "NumConta",
      label: "NumConta",
      name: "NumConta",
      typeField: "string",
      size: 12,
      allowNull: false,
    },
    {
      field: "DtBase",
      label: "DtBase",
      name: "DtBase",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "NumLcto",
      label: "NumLcto",
      name: "NumLcto",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "CdTpAplicacao",
      label: "CdTpAplicacao",
      name: "CdTpAplicacao",
      typeField: "int",
      size: 4,
    },
    {
      field: "VlValor",
      label: "VlValor",
      name: "VlValor",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "TxTipLcto",
      label: "TxTipLcto",
      name: "TxTipLcto",
      typeField: "string",
      size: 1,
    },
    {
      field: "CdFilialAssociada",
      label: "CdFilialAssociada",
      name: "CdFilialAssociada",
      typeField: "int",
      size: 4,
    },
    {
      field: "FgSituacao",
      label: "FgSituacao",
      name: "FgSituacao",
      typeField: "string",
      size: 1,
    },
    {
      field: "CdContabil",
      label: "CdContabil",
      name: "CdContabil",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "CdBancoDestino",
      label: "CdBancoDestino",
      name: "CdBancoDestino",
      typeField: "int",
      size: 2,
    },
    {
      field: "NumContaDestino",
      label: "NumContaDestino",
      name: "NumContaDestino",
      typeField: "string",
      size: 16,
    },
    {
      field: "NumLctoDestino",
      label: "NumLctoDestino",
      name: "NumLctoDestino",
      typeField: "int",
      size: 4,
    },
    {
      field: "CdAgenciaDestino",
      label: "CdAgenciaDestino",
      name: "CdAgenciaDestino",
      typeField: "int",
      size: 2,
    },
  ],
};
