import { TTable } from "../../../../types/model";

export const LogIntegracao: TTable = {
  database: "plano",
  table: "LogIntegracao",
  fields: [
    {
      field: "CdEmpresa",
      label: "CdEmpresa",
      name: "LogIntegracao_id",
      typeField: "int",
      size: 4,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "DHArquivo",
      label: "DHArquivo",
      name: "DHArquivo",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "IdEquipamento",
      label: "IdEquipamento",
      name: "IdEquipamento",
      typeField: "string",
      size: 15,
      allowNull: false,
    },
    {
      field: "EnderecoEmail",
      label: "EnderecoEmail",
      name: "EnderecoEmail",
      typeField: "string",
      size: 50,
      allowNull: false,
    },
    {
      field: "QtdeArquivos",
      label: "QtdeArquivos",
      name: "QtdeArquivos",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "Mensagem",
      label: "Mensagem",
      name: "Mensagem",
      typeField: "string",
      size: 1024,
      allowNull: false,
    },
  ],
};
