import { TTableDef } from "../../../../types/model";

export const LotesOrdemProducao: TTableDef = {
  database: "plano",
  table: "LotesOrdemProducao",
  fields: [
    {
      field: "NumFormula",
      label: "NumFormula",
      name: "NumFormula",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "CdProduto",
      label: "CdProduto",
      name: "CdProduto",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "CdLote",
      label: "CdLote",
      name: "CdLote",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "QtdeLote",
      label: "QtdeLote",
      name: "QtdeLote",
      typeField: "int",
      size: 9,
      scale: 4,
      allowNull: false,
    },
    {
      field: "CdFase",
      label: "CdFase",
      name: "CdFase",
      typeField: "int",
      size: 4,
    },
    {
      field: "DtFabricacao",
      label: "DtFabricacao",
      name: "DtFabricacao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
  ],
};
