import { TTableDef } from "@mono/types/model";

export const MedicoEnderecos: TTableDef = {
  database: "plano",
  table: "MedicoEnderecos",
  fields: [
    {
      field: "Crm",
      label: "Crm",
      name: "Crm",
      typeField: "string",
      size: 16,
      allowNull: false,
    },
    {
      field: "Sequencia",
      label: "Sequencia",
      name: "Sequencia",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NmClinica",
      label: "NmClinica",
      name: "NmClinica",
      typeField: "string",
      size: 50,
      allowNull: false,
    },
    {
      field: "Endereco",
      label: "Endereco",
      name: "Endereco",
      typeField: "string",
      size: 50,
      allowNull: false,
    },
    {
      field: "NumEndereco",
      label: "NumEndereco",
      name: "NumEndereco",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "CompEndereco",
      label: "CompEndereco",
      name: "CompEndereco",
      typeField: "string",
      size: 10,
      allowNull: false,
    },
    {
      field: "Bairro",
      label: "Bairro",
      name: "Bairro",
      typeField: "string",
      size: 30,
      allowNull: false,
    },
    {
      field: "Cidade",
      label: "Cidade",
      name: "Cidade",
      typeField: "string",
      size: 30,
      allowNull: false,
    },
    {
      field: "Uf",
      label: "Uf",
      name: "Uf",
      typeField: "string",
      size: 2,
      allowNull: false,
    },
    {
      field: "Cep",
      label: "Cep",
      name: "Cep",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "Telefone",
      label: "Telefone",
      name: "Telefone",
      typeField: "string",
      size: 20,
      allowNull: false,
    },
    {
      field: "Email",
      label: "Email",
      name: "Email",
      typeField: "string",
      size: 50,
      allowNull: false,
    },
    {
      field: "DtUltAlteracao",
      label: "DtUltAlteracao",
      name: "DtUltAlteracao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
  ],
};
