import { TTable } from "../../../../types/model";

export const MestreRAT: TTable = {
  database: "plano",
  table: "MestreRAT",
  fields: [
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "NumeroRAT",
      label: "NumeroRAT",
      name: "NumeroRAT",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "CTN",
      label: "CTN",
      name: "CTN",
      typeField: "string",
      size: 20,
    },
    {
      field: "DtPreventiva",
      label: "DtPreventiva",
      name: "DtPreventiva",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "FgSituacao",
      label: "FgSituacao",
      name: "FgSituacao",
      typeField: "string",
      size: 1,
    },
    {
      field: "NumeroOS",
      label: "NumeroOS",
      name: "NumeroOS",
      typeField: "string",
      size: 20,
    },
    {
      field: "CdCliente",
      label: "CdCliente",
      name: "CdCliente",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "NmContato",
      label: "NmContato",
      name: "NmContato",
      typeField: "string",
      size: 30,
    },
    {
      field: "CdEquipamento",
      label: "CdEquipamento",
      name: "CdEquipamento",
      typeField: "int",
      size: 4,
    },
    {
      field: "NumSerie",
      label: "NumSerie",
      name: "NumSerie",
      typeField: "string",
      size: 20,
    },
    {
      field: "DtChamado",
      label: "DtChamado",
      name: "DtChamado",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "HrChamado",
      label: "HrChamado",
      name: "HrChamado",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DtResposta",
      label: "DtResposta",
      name: "DtResposta",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "HrResposta",
      label: "HrResposta",
      name: "HrResposta",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DtSolucao",
      label: "DtSolucao",
      name: "DtSolucao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "HrSolucao",
      label: "HrSolucao",
      name: "HrSolucao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "Defeito",
      label: "Defeito",
      name: "Defeito",
      typeField: "string",
      size: 100,
    },
    {
      field: "CdAtividade",
      label: "CdAtividade",
      name: "CdAtividade",
      typeField: "int",
      size: 4,
    },
    {
      field: "CdDefeito",
      label: "CdDefeito",
      name: "CdDefeito",
      typeField: "int",
      size: 4,
    },
    {
      field: "CdCausa",
      label: "CdCausa",
      name: "CdCausa",
      typeField: "int",
      size: 4,
    },
    {
      field: "CdSolucao",
      label: "CdSolucao",
      name: "CdSolucao",
      typeField: "int",
      size: 4,
    },
    {
      field: "FgPrioridade",
      label: "FgPrioridade",
      name: "FgPrioridade",
      typeField: "string",
      size: 1,
    },
    {
      field: "CdFase",
      label: "CdFase",
      name: "CdFase",
      typeField: "int",
      size: 2,
    },
    {
      field: "NumIntervencoes",
      label: "NumIntervencoes",
      name: "NumIntervencoes",
      typeField: "int",
      size: 2,
    },
    {
      field: "DtUltIntervencao",
      label: "DtUltIntervencao",
      name: "DtUltIntervencao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "CdAtendente",
      label: "CdAtendente",
      name: "CdAtendente",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "CdRespAtendimento",
      label: "CdRespAtendimento",
      name: "CdRespAtendimento",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "DtPrevRetorno",
      label: "DtPrevRetorno",
      name: "DtPrevRetorno",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "FgClassificacao",
      label: "FgClassificacao",
      name: "FgClassificacao",
      typeField: "string",
      size: 1,
    },
    {
      field: "TempoPrevisto",
      label: "TempoPrevisto",
      name: "TempoPrevisto",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "NumHrDeslocamento",
      label: "NumHrDeslocamento",
      name: "NumHrDeslocamento",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "NumHrFaturada",
      label: "NumHrFaturada",
      name: "NumHrFaturada",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "NumHrAbonada",
      label: "NumHrAbonada",
      name: "NumHrAbonada",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Funcao",
      label: "Funcao",
      name: "Funcao",
      typeField: "string",
      size: 128,
    },
    {
      field: "FgAtendimentoInterno",
      label: "FgAtendimentoInterno",
      name: "FgAtendimentoInterno",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgGeraSolicitacao",
      label: "FgGeraSolicitacao",
      name: "FgGeraSolicitacao",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgReleaseNotes",
      label: "FgReleaseNotes",
      name: "FgReleaseNotes",
      typeField: "string",
      size: 1,
    },
    {
      field: "Versao",
      label: "Versao",
      name: "Versao",
      typeField: "string",
      size: 16,
    },
    {
      field: "VlOrcamento",
      label: "VlOrcamento",
      name: "VlOrcamento",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "CdFormaPagto",
      label: "CdFormaPagto",
      name: "CdFormaPagto",
      typeField: "int",
      size: 2,
    },
    {
      field: "FgImprimeValoresRat",
      label: "FgImprimeValoresRat",
      name: "FgImprimeValoresRat",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgControleDesenvolvimento",
      label: "FgControleDesenvolvimento",
      name: "FgControleDesenvolvimento",
      typeField: "string",
      size: 1,
    },
    {
      field: "Ambiente",
      label: "Ambiente",
      name: "Ambiente",
      typeField: "string",
      size: 1,
    },
  ],
};
