import { TTableDef } from "../../../../types/model";

export const MestreLancTransporte: TTableDef = {
  database: "plano",
  table: "MestreLancTransporte",
  fields: [
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumDoc",
      label: "NumDoc",
      name: "NumDoc",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "Serie",
      label: "Serie",
      name: "Serie",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "Modelo",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "CdFornecedor",
      label: "CdFornecedor",
      name: "CdFornecedor",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "DtEmissao",
      label: "DtEmissao",
      name: "DtEmissao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "DtAquisicao",
      label: "DtAquisicao",
      name: "DtAquisicao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "Nop",
      label: "Nop",
      name: "Nop",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TipoFrete",
      label: "TipoFrete",
      name: "TipoFrete",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "VlDocumento",
      label: "VlDocumento",
      name: "VlDocumento",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlDesconto",
      label: "VlDesconto",
      name: "VlDesconto",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlServico",
      label: "VlServico",
      name: "VlServico",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "ICMSBasCalc",
      label: "ICMSBasCalc",
      name: "ICMSBasCalc",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlICMS",
      label: "VlICMS",
      name: "VlICMS",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlNaoTributado",
      label: "VlNaoTributado",
      name: "VlNaoTributado",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "IndicadorNatFrete",
      label: "IndicadorNatFrete",
      name: "IndicadorNatFrete",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumChaveNFE",
      label: "NumChaveNFE",
      name: "NumChaveNFE",
      typeField: "string",
      size: 44,
      allowNull: false,
    },
    {
      field: "SituacaoDoc",
      label: "SituacaoDoc",
      name: "SituacaoDoc",
      typeField: "int",
      size: 4,
    },
    {
      field: "ObsGerais",
      label: "ObsGerais",
      name: "ObsGerais",
      typeField: "string",
      size: 1024,
    },
  ],
};
