import { TTableDef } from "@mono/types/model";

export const MestreNotaServicoSubstituido: TTableDef = {
  database: "plano",
  table: "MestreNotaServicoSubstituido",
  fields: [
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "NumNota",
      label: "NumNota",
      name: "NumNota",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "Serie",
      label: "Serie",
      name: "Serie",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "Modelo",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "NumeroSubstituido",
      label: "NumeroSubstituido",
      name: "NumeroSubstituido",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "SerieSubstituido",
      label: "SerieSubstituido",
      name: "SerieSubstituido",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "TipoSubstituido",
      label: "TipoSubstituido",
      name: "TipoSubstituido",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
  ],
};
