import { TTableDef } from "../../../../types/model";

export const MestreProducaoSacolas: TTableDef = {
  database: "plano",
  table: "MestreProducaoSacolas",
  fields: [
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "NumProducao",
      label: "NumProducao",
      name: "NumProducao",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "DtProducao",
      label: "DtProducao",
      name: "DtProducao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "CdCliente",
      label: "CdCliente",
      name: "CdCliente",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "CdVendedor",
      label: "CdVendedor",
      name: "CdVendedor",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "CdSacola",
      label: "CdSacola",
      name: "CdSacola",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "DtEntrega",
      label: "DtEntrega",
      name: "DtEntrega",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "Qtde",
      label: "Qtde",
      name: "Qtde",
      typeField: "int",
      size: 9,
      scale: 4,
      allowNull: false,
    },
    {
      field: "CdUnidade",
      label: "CdUnidade",
      name: "CdUnidade",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "Largura",
      label: "Largura",
      name: "Largura",
      typeField: "int",
      size: 9,
      scale: 2,
      allowNull: false,
    },
    {
      field: "Comprimento",
      label: "Comprimento",
      name: "Comprimento",
      typeField: "int",
      size: 9,
      scale: 2,
      allowNull: false,
    },
    {
      field: "Espessura",
      label: "Espessura",
      name: "Espessura",
      typeField: "int",
      size: 9,
      scale: 2,
      allowNull: false,
    },
    {
      field: "LarguraExtrusao",
      label: "LarguraExtrusao",
      name: "LarguraExtrusao",
      typeField: "int",
      size: 9,
      scale: 2,
      allowNull: false,
    },
    {
      field: "PesoSacola",
      label: "PesoSacola",
      name: "PesoSacola",
      typeField: "int",
      size: 9,
      scale: 4,
      allowNull: false,
    },
    {
      field: "PesoTotal",
      label: "PesoTotal",
      name: "PesoTotal",
      typeField: "int",
      size: 9,
      scale: 4,
      allowNull: false,
    },
    {
      field: "Oxi",
      label: "Oxi",
      name: "Oxi",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "Tratamento",
      label: "Tratamento",
      name: "Tratamento",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "GramaMetro",
      label: "GramaMetro",
      name: "GramaMetro",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "Variacao",
      label: "Variacao",
      name: "Variacao",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "Observacao",
      label: "Observacao",
      name: "Observacao",
      typeField: "string",
      size: 512,
      allowNull: false,
    },
    {
      field: "Material",
      label: "Material",
      name: "Material",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "Ping",
      label: "Ping",
      name: "Ping",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "Modelo",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "Sanfona",
      label: "Sanfona",
      name: "Sanfona",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "CoresImpressao",
      label: "CoresImpressao",
      name: "CoresImpressao",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "Marca",
      label: "Marca",
      name: "Marca",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "EmbalagemPara",
      label: "EmbalagemPara",
      name: "EmbalagemPara",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "CdFase",
      label: "CdFase",
      name: "CdFase",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "NumBobinas",
      label: "NumBobinas",
      name: "NumBobinas",
      typeField: "int",
      size: 9,
    },
    {
      field: "Diametro",
      label: "Diametro",
      name: "Diametro",
      typeField: "int",
      size: 9,
    },
  ],
};
