import { TTableDef } from "@mono/types/model";

export const ModeloEtiqueta: TTableDef = {
  database: "plano",
  table: "ModeloEtiqueta",
  fields: [
    {
      field: "Ajuste",
      label: "Ajuste",
      name: "Ajuste",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "AjusteDuplo",
      label: "AjusteDuplo",
      name: "AjusteDuplo",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "AltCodigo",
      label: "AltCodigo",
      name: "AltCodigo",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Altura",
      label: "Altura",
      name: "Altura",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Espaco1",
      label: "Espaco1",
      name: "Espaco1",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Espaco2",
      label: "Espaco2",
      name: "Espaco2",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Espaco3",
      label: "Espaco3",
      name: "Espaco3",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Espaco4",
      label: "Espaco4",
      name: "Espaco4",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Espaco5",
      label: "Espaco5",
      name: "Espaco5",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "EspacoCodigo",
      label: "EspacoCodigo",
      name: "EspacoCodigo",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "EspacoDescricao",
      label: "EspacoDescricao",
      name: "EspacoDescricao",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "EspacoPreco",
      label: "EspacoPreco",
      name: "EspacoPreco",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Largura",
      label: "Largura",
      name: "Largura",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "LinhaInicial",
      label: "LinhaInicial",
      name: "LinhaInicial",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Linhas",
      label: "Linhas",
      name: "Linhas",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "NomeEtiqueta",
      label: "NomeEtiqueta",
      name: "ModeloEtiqueta_id",
      typeField: "string",
      size: 50,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "QtdeEtiquetas",
      label: "QtdeEtiquetas",
      name: "QtdeEtiquetas",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "TamFonteCodigo",
      label: "TamFonteCodigo",
      name: "TamFonteCodigo",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "TamFonteDescricao",
      label: "TamFonteDescricao",
      name: "TamFonteDescricao",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "TamFontePreco",
      label: "TamFontePreco",
      name: "TamFontePreco",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "TamLinhaCodigo",
      label: "TamLinhaCodigo",
      name: "TamLinhaCodigo",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "TamLinhaDescricao",
      label: "TamLinhaDescricao",
      name: "TamLinhaDescricao",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "TamLinhaPreco",
      label: "TamLinhaPreco",
      name: "TamLinhaPreco",
      typeField: "float",
      size: 8,
      scale: 4,
    },
  ],
};
