import { TTableDef } from "@mono/types/model";

export const MovCreditoFornecedor: TTableDef = {
  database: "plano",
  table: "MovCreditoFornecedor",
  fields: [
    {
      field: "CdFornecedor",
      label: "CdFornecedor",
      name: "CdFornecedor",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "Sequencia",
      label: "Sequencia",
      name: "Sequencia",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumDocOrigem",
      label: "NumDocOrigem",
      name: "NumDocOrigem",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "NumDocDestino",
      label: "NumDocDestino",
      name: "NumDocDestino",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "VlCredito",
      label: "VlCredito",
      name: "VlCredito",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlDebito",
      label: "VlDebito",
      name: "VlDebito",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "Observacao",
      label: "Observacao",
      name: "Observacao",
      typeField: "string",
      size: 1024,
    },
  ],
};
