import { TTableDef } from "@mono/types/model";

export const NFe: TTableDef = {
  database: "plano",
  table: "NFe",
  fields: [
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "float",
      size: 9,
      allowNull: false,
    },
    {
      field: "NumNota",
      label: "NumNota",
      name: "NumNota",
      typeField: "float",
      size: 9,
      allowNull: false,
    },
    {
      field: "Serie",
      label: "Serie",
      name: "Serie",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "DtSolicitacao",
      label: "DtSolicitacao",
      name: "DtSolicitacao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DtAutorizacao",
      label: "DtAutorizacao",
      name: "DtAutorizacao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "Situacao",
      label: "Situacao",
      name: "Situacao",
      typeField: "string",
      size: 600,
    },
    {
      field: "fgDanfe",
      label: "fgDanfe",
      name: "fgDanfe",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "AutorExpedida",
      label: "AutorExpedida",
      name: "AutorExpedida",
      typeField: "string",
      size: 100,
    },
    {
      field: "ChaveNFe",
      label: "ChaveNFe",
      name: "ChaveNFe",
      typeField: "string",
      size: 600,
    },
    {
      field: "ReciboNFe",
      label: "ReciboNFe",
      name: "ReciboNFe",
      typeField: "string",
      size: 600,
    },
  ],
};
