import { TEntity } from "../../../../types";

export const NotaEntradaRecuperacaoSTItem: TEntity = {
  database: "plano",
  table: "NotaEntradaRecuperacaoSTItem",
  fields: [
    {
      field: "CdEmpresa",
      label: "CdEmpresa",
      name: "CdEmpresa",
      type: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      type: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "NumNota",
      label: "NumNota",
      name: "NumNota",
      type: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Serie",
      label: "Serie",
      name: "Serie",
      type: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "Modelo",
      type: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "CdFornecedor",
      label: "CdFornecedor",
      name: "CdFornecedor",
      type: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "Sequencia",
      label: "Sequencia",
      name: "Sequencia",
      type: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "CdProduto",
      label: "CdProduto",
      name: "CdProduto",
      type: "string",
      size: 16,
      allowNull: false,
    },
    {
      field: "Quantidade",
      label: "Quantidade",
      name: "Quantidade",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlBaseCalculoST",
      label: "VlBaseCalculoST",
      name: "VlBaseCalculoST",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "QuantidadeUtilizada",
      label: "QuantidadeUtilizada",
      name: "QuantidadeUtilizada",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlICMSSTRecolhido",
      label: "VlICMSSTRecolhido",
      name: "VlICMSSTRecolhido",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlICMSSTRecuperado",
      label: "VlICMSSTRecuperado",
      name: "VlICMSSTRecuperado",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
  ],
};
