import { TTable } from "../../../../types/model";

export const NotaEntradaXMLDescProduto: TTable = {
  database: "plano",
  table: "NotaEntradaXMLDescProduto",
  fields: [
    {
      field: "CdEmpresa",
      label: "CdEmpresa",
      name: "CdEmpresa",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "NumeroNota",
      label: "NumeroNota",
      name: "NumeroNota",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "SerieNota",
      label: "SerieNota",
      name: "SerieNota",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "ModeloNota",
      label: "ModeloNota",
      name: "ModeloNota",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "CdFornecedor",
      label: "CdFornecedor",
      name: "CdFornecedor",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "Sequencia",
      label: "Sequencia",
      name: "Sequencia",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "DescricaoProdutoXML",
      label: "DescricaoProdutoXML",
      name: "DescricaoProdutoXML",
      typeField: "string",
      size: 120,
      allowNull: false,
    },
  ],
};
