import { TTableDef } from "@/types/model";

export const NotaDadosNFCe: TTableDef = {
  database: "plano",
  table: "NotaDadosNFCe",
  fields: [
    {
      field: "CdEmpresa",
      label: "CdEmpresa",
      name: "CdEmpresa",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "NumNota",
      label: "NumNota",
      name: "NumNota",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Serie",
      label: "Serie",
      name: "Serie",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "Modelo",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "CPFCNPJDestinatario",
      label: "CPFCNPJDestinatario",
      name: "CPFCNPJDestinatario",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "NomeDestinatario",
      label: "NomeDestinatario",
      name: "NomeDestinatario",
      typeField: "string",
      size: 70,
      allowNull: false,
    },
    {
      field: "EmailDestinatario",
      label: "EmailDestinatario",
      name: "EmailDestinatario",
      typeField: "string",
      size: 128,
      allowNull: false,
    },
    {
      field: "Endereco",
      label: "Endereco",
      name: "Endereco",
      typeField: "string",
      size: 60,
      allowNull: false,
    },
    {
      field: "NumEndereco",
      label: "NumEndereco",
      name: "NumEndereco",
      typeField: "string",
      size: 12,
      allowNull: false,
    },
    {
      field: "Complemento",
      label: "Complemento",
      name: "Complemento",
      typeField: "string",
      size: 60,
      allowNull: false,
    },
    {
      field: "Bairro",
      label: "Bairro",
      name: "Bairro",
      typeField: "string",
      size: 60,
      allowNull: false,
    },
    {
      field: "Cidade",
      label: "Cidade",
      name: "Cidade",
      typeField: "string",
      size: 60,
      allowNull: false,
    },
    {
      field: "CdCidade",
      label: "CdCidade",
      name: "CdCidade",
      typeField: "string",
      size: 7,
      allowNull: false,
    },
    {
      field: "Uf",
      label: "Uf",
      name: "Uf",
      typeField: "string",
      size: 2,
      allowNull: false,
    },
    {
      field: "Cep",
      label: "Cep",
      name: "Cep",
      typeField: "string",
      size: 8,
      allowNull: false,
    },
    {
      field: "Telefone",
      label: "Telefone",
      name: "Telefone",
      typeField: "string",
      size: 14,
      allowNull: false,
    },
  ],
};
