import { TTable } from "../../../../types/model";

export const ParametrosMediaImposto: TTable = {
  database: "plano",
  table: "ParametrosMediaImposto",
  fields: [
    {
      field: "TipoTabela",
      label: "TipoTabela",
      name: "TipoTabela",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "CodigoNCMNBS",
      label: "CodigoNCMNBS",
      name: "CodigoNCMNBS",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "CodigoEX",
      label: "CodigoEX",
      name: "CodigoEX",
      typeField: "string",
      size: 2,
      allowNull: false,
    },
    {
      field: "UF",
      label: "UF",
      name: "UF",
      typeField: "string",
      size: 2,
      allowNull: false,
    },
    {
      field: "PercFederalNacional",
      label: "PercFederalNacional",
      name: "PercFederalNacional",
      typeField: "int",
      size: 5,
      scale: 2,
      allowNull: false,
    },
    {
      field: "PercFederalImportado",
      label: "PercFederalImportado",
      name: "PercFederalImportado",
      typeField: "int",
      size: 5,
      scale: 2,
      allowNull: false,
    },
    {
      field: "PercEstadual",
      label: "PercEstadual",
      name: "PercEstadual",
      typeField: "int",
      size: 5,
      scale: 2,
      allowNull: false,
    },
    {
      field: "PercMunicipal",
      label: "PercMunicipal",
      name: "PercMunicipal",
      typeField: "int",
      size: 5,
      scale: 2,
      allowNull: false,
    },
    {
      field: "DtUltAlteracao",
      label: "DtUltAlteracao",
      name: "DtUltAlteracao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
  ],
};
