import { TTableDef } from "../../../../types/model";

export const ParametrosFiscais: TTableDef = {
  database: "plano",
  table: "ParametrosFiscais",
  fields: [
    {
      field: "IdParametro",
      label: "IdParametro",
      name: "ParametrosFiscais_id",
      typeField: "int",
      size: 2,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "Descricao",
      label: "Descricao",
      name: "Descricao",
      typeField: "string",
      size: 50,
      allowNull: false,
    },
    {
      field: "TipoMovimentacao",
      label: "TipoMovimentacao",
      name: "TipoMovimentacao",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "CriterioSubstituicao",
      label: "CriterioSubstituicao",
      name: "CriterioSubstituicao",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgDetalhaItem",
      label: "FgDetalhaItem",
      name: "FgDetalhaItem",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgAtualizaTabela",
      label: "FgAtualizaTabela",
      name: "FgAtualizaTabela",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgAtualizaAtacado",
      label: "FgAtualizaAtacado",
      name: "FgAtualizaAtacado",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgAtualizaCusto",
      label: "FgAtualizaCusto",
      name: "FgAtualizaCusto",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgAtualizaPreco",
      label: "FgAtualizaPreco",
      name: "FgAtualizaPreco",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgConferePreco",
      label: "FgConferePreco",
      name: "FgConferePreco",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgPedido",
      label: "FgPedido",
      name: "FgPedido",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgIntegraCP",
      label: "FgIntegraCP",
      name: "FgIntegraCP",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgIntegraCR",
      label: "FgIntegraCR",
      name: "FgIntegraCR",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "LimiteArredondamento",
      label: "LimiteArredondamento",
      name: "LimiteArredondamento",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
  ],
};
