import { TTableDef } from "@mono/types/model";

export const PedidoEnderecoEntrega: TTableDef = {
  database: "plano",
  table: "PedidoEnderecoEntrega",
  fields: [
    {
      field: "CdEmpresa",
      label: "CdEmpresa",
      name: "CdEmpresa",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "NumPedido",
      label: "NumPedido",
      name: "NumPedido",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "CdEnderecoEntrega",
      label: "CdEnderecoEntrega",
      name: "CdEnderecoEntrega",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Logradouro",
      label: "Logradouro",
      name: "Logradouro",
      typeField: "string",
      size: 80,
      allowNull: false,
    },
    {
      field: "Numero",
      label: "Numero",
      name: "Numero",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Complemento",
      label: "Complemento",
      name: "Complemento",
      typeField: "string",
      size: 32,
      allowNull: false,
    },
    {
      field: "Bairro",
      label: "Bairro",
      name: "Bairro",
      typeField: "string",
      size: 32,
      allowNull: false,
    },
    {
      field: "CdCidade",
      label: "CdCidade",
      name: "CdCidade",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Cidade",
      label: "Cidade",
      name: "Cidade",
      typeField: "string",
      size: 40,
      allowNull: false,
    },
    {
      field: "CEP",
      label: "CEP",
      name: "CEP",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "UF",
      label: "UF",
      name: "UF",
      typeField: "string",
      size: 2,
      allowNull: false,
    },
    {
      field: "Proximidades",
      label: "Proximidades",
      name: "Proximidades",
      typeField: "string",
      size: 80,
      allowNull: false,
    },
    {
      field: "ContatoEntrega",
      label: "ContatoEntrega",
      name: "ContatoEntrega",
      typeField: "string",
      size: 32,
      allowNull: false,
    },
  ],
};
