import { TTableDef } from "@mono/types/model";

export const PreventivaRAT: TTableDef = {
  database: "plano",
  table: "PreventivaRAT",
  fields: [
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "Item1",
      label: "Item1",
      name: "Item1",
      typeField: "string",
      size: 1,
    },
    {
      field: "Item10",
      label: "Item10",
      name: "Item10",
      typeField: "string",
      size: 1,
    },
    {
      field: "Item2",
      label: "Item2",
      name: "Item2",
      typeField: "string",
      size: 1,
    },
    {
      field: "Item3",
      label: "Item3",
      name: "Item3",
      typeField: "string",
      size: 1,
    },
    {
      field: "Item4",
      label: "Item4",
      name: "Item4",
      typeField: "string",
      size: 1,
    },
    {
      field: "Item5",
      label: "Item5",
      name: "Item5",
      typeField: "string",
      size: 1,
    },
    {
      field: "Item6",
      label: "Item6",
      name: "Item6",
      typeField: "string",
      size: 1,
    },
    {
      field: "Item7",
      label: "Item7",
      name: "Item7",
      typeField: "string",
      size: 1,
    },
    {
      field: "Item8",
      label: "Item8",
      name: "Item8",
      typeField: "string",
      size: 1,
    },
    {
      field: "Item9",
      label: "Item9",
      name: "Item9",
      typeField: "string",
      size: 1,
    },
    {
      field: "NumeroRAT",
      label: "NumeroRAT",
      name: "NumeroRAT",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
  ],
};
