import { TTableDef } from "@/types/model";

export const ProducaoLinhaFluxo: TTableDef = {
  database: "plano",
  table: "ProducaoLinhaFluxo",
  fields: [
    {
      field: "CdLinhaProducao",
      label: "CdLinhaProducao",
      name: "CdLinhaProducao",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Sequencia",
      label: "Sequencia",
      name: "Sequencia",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "CdOperacao",
      label: "CdOperacao",
      name: "CdOperacao",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "FgCondicional",
      label: "FgCondicional",
      name: "FgCondicional",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgAmostragem",
      label: "FgAmostragem",
      name: "FgAmostragem",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgRetrabalho",
      label: "FgRetrabalho",
      name: "FgRetrabalho",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgEtiquetaInterna",
      label: "FgEtiquetaInterna",
      name: "FgEtiquetaInterna",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgEsterilizacaoInterna",
      label: "FgEsterilizacaoInterna",
      name: "FgEsterilizacaoInterna",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgEsterilizacaoExterna",
      label: "FgEsterilizacaoExterna",
      name: "FgEsterilizacaoExterna",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgContinuidade",
      label: "FgContinuidade",
      name: "FgContinuidade",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgEtiquetaExterna",
      label: "FgEtiquetaExterna",
      name: "FgEtiquetaExterna",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
  ],
};
