import { TTableDef } from "@mono/types/model";

export const ProdutosIndisponiveis: TTableDef = {
  database: "plano",
  table: "ProdutosIndisponiveis",
  fields: [
    {
      field: "CdProduto",
      label: "CdProduto",
      name: "CdProduto",
      typeField: "string",
      size: 16,
      allowNull: false,
    },
    {
      field: "NumLote",
      label: "NumLote",
      name: "NumLote",
      typeField: "string",
      size: 16,
      allowNull: false,
    },
    {
      field: "Quantidade",
      label: "Quantidade",
      name: "Quantidade",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "FgStatus",
      label: "FgStatus",
      name: "FgStatus",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "FgMotivo",
      label: "FgMotivo",
      name: "FgMotivo",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "Observacao",
      label: "Observacao",
      name: "Observacao",
      typeField: "string",
      size: 256,
      allowNull: false,
    },
    {
      field: "DtLcto",
      label: "DtLcto",
      name: "DtLcto",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
  ],
};
