import { TTableDef } from "@mono/types/model";

export const ProgramaAmiVida: TTableDef = {
  database: "plano",
  table: "ProgramaAmiVida",
  fields: [
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "CdProduto",
      label: "CdProduto",
      name: "CdProduto",
      typeField: "string",
      size: 15,
      allowNull: false,
    },
    {
      field: "Campanha",
      label: "Campanha",
      name: "Campanha",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "UnidadesCaixa",
      label: "UnidadesCaixa",
      name: "UnidadesCaixa",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "DtInicioCampanha",
      label: "DtInicioCampanha",
      name: "DtInicioCampanha",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "DtFinalCampanha",
      label: "DtFinalCampanha",
      name: "DtFinalCampanha",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "FgParticipacao",
      label: "FgParticipacao",
      name: "FgParticipacao",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "DtUltAlteracao",
      label: "DtUltAlteracao",
      name: "DtUltAlteracao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
  ],
};
