import { TTable } from "../../../../types/model";

export const Series: TTable = {
  database: "plano",
  table: "Series",
  fields: [
    {
      field: "CdSerie",
      label: "CdSerie",
      name: "CdSerie",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "MensagemCupom",
      label: "MensagemCupom",
      name: "MensagemCupom",
      typeField: "string",
      size: 256,
    },
    {
      field: "MensagemReducao",
      label: "MensagemReducao",
      name: "MensagemReducao",
      typeField: "string",
      size: 256,
    },
    {
      field: "MensagemSubstituicao",
      label: "MensagemSubstituicao",
      name: "MensagemSubstituicao",
      typeField: "string",
      size: 256,
    },
    {
      field: "Descricao",
      label: "Descricao",
      name: "Descricao",
      typeField: "string",
      size: 256,
    },
    {
      field: "Observacao1",
      label: "Observacao1",
      name: "Observacao1",
      typeField: "string",
      size: 256,
    },
    {
      field: "Observacao2",
      label: "Observacao2",
      name: "Observacao2",
      typeField: "string",
      size: 256,
    },
    {
      field: "Observacao3",
      label: "Observacao3",
      name: "Observacao3",
      typeField: "string",
      size: 256,
    },
    {
      field: "Observacao4",
      label: "Observacao4",
      name: "Observacao4",
      typeField: "string",
      size: 256,
    },
    {
      field: "Produtos",
      label: "Produtos",
      name: "Produtos",
      typeField: "string",
      size: 256,
    },
    {
      field: "Servicos",
      label: "Servicos",
      name: "Servicos",
      typeField: "string",
      size: 256,
    },
    {
      field: "MensagemCorpo",
      label: "MensagemCorpo",
      name: "MensagemCorpo",
      typeField: "string",
      size: 512,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "Modelo",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "FgAtivo",
      label: "FgAtivo",
      name: "FgAtivo",
      typeField: "string",
      size: 1,
    },
    {
      field: "MensagemInstitucionalNFCe",
      label: "MensagemInstitucionalNFCe",
      name: "MensagemInstitucionalNFCe",
      typeField: "string",
      size: 512,
    },
    {
      field: "FgCabecalho",
      label: "FgCabecalho",
      name: "FgCabecalho",
      typeField: "string",
      size: 1,
    },
  ],
};
