import { TTableDef } from "@mono/types/model";

export const SpedReceitaBruta: TTableDef = {
  database: "plano",
  table: "SpedReceitaBruta",
  fields: [
    {
      field: "CNPJCentralizador",
      label: "CNPJCentralizador",
      name: "CNPJCentralizador",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "PeriodoApuracao",
      label: "PeriodoApuracao",
      name: "PeriodoApuracao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "VlTributadoInterno",
      label: "VlTributadoInterno",
      name: "VlTributadoInterno",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlNaoTributadoIterno",
      label: "VlNaoTributadoIterno",
      name: "VlNaoTributadoIterno",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlExportacao",
      label: "VlExportacao",
      name: "VlExportacao",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlReceitaCumulativa",
      label: "VlReceitaCumulativa",
      name: "VlReceitaCumulativa",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "VlReceitaBruta",
      label: "VlReceitaBruta",
      name: "VlReceitaBruta",
      typeField: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
  ],
};
