import { TTableDef } from "../../../../types/model";

export const Sugestao: TTableDef = {
  database: "plano",
  table: "Sugestao",
  fields: [
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumPedido",
      label: "NumPedido",
      name: "NumPedido",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "CdEmitente",
      label: "CdEmitente",
      name: "CdEmitente",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "CdVendedor",
      label: "CdVendedor",
      name: "CdVendedor",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "DtEntrega",
      label: "DtEntrega",
      name: "DtEntrega",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "LocalEntrega",
      label: "LocalEntrega",
      name: "LocalEntrega",
      typeField: "string",
      size: 1024,
    },
    {
      field: "NmFavorecido",
      label: "NmFavorecido",
      name: "NmFavorecido",
      typeField: "string",
      size: 40,
    },
    {
      field: "Obs",
      label: "Obs",
      name: "Obs",
      typeField: "string",
      size: 1024,
    },
    {
      field: "Posicao",
      label: "Posicao",
      name: "Posicao",
      typeField: "string",
      size: 1,
    },
    {
      field: "Proximidades",
      label: "Proximidades",
      name: "Proximidades",
      typeField: "string",
      size: 40,
    },
    {
      field: "VlPago",
      label: "VlPago",
      name: "VlPago",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Tipo",
      label: "Tipo",
      name: "Tipo",
      typeField: "string",
      size: 1,
    },
    {
      field: "DtEmissao",
      label: "DtEmissao",
      name: "DtEmissao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "Horario",
      label: "Horario",
      name: "Horario",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "VlTotal",
      label: "VlTotal",
      name: "VlTotal",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "FgSituacao",
      label: "FgSituacao",
      name: "FgSituacao",
      typeField: "string",
      size: 1,
    },
  ],
};
