import { TTableDef } from "../../../../types/model";

export const TabBal: TTableDef = {
  database: "plano",
  table: "TabBal",
  fields: [
    {
      field: "CdEmpresa",
      label: "CdEmpresa",
      name: "CdEmpresa",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "CdProduto",
      label: "CdProduto",
      name: "CdProduto",
      typeField: "string",
      size: 15,
      allowNull: false,
    },
    {
      field: "Contagem1",
      label: "Contagem1",
      name: "Contagem1",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Contagem2",
      label: "Contagem2",
      name: "Contagem2",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "EndPrateleiraAtual",
      label: "EndPrateleiraAtual",
      name: "EndPrateleiraAtual",
      typeField: "string",
      size: 15,
    },
    {
      field: "EndPrateleiraNovo",
      label: "EndPrateleiraNovo",
      name: "EndPrateleiraNovo",
      typeField: "string",
      size: 15,
    },
    {
      field: "DtContagem",
      label: "DtContagem",
      name: "DtContagem",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "IdReduzido",
      label: "IdReduzido",
      name: "IdReduzido",
      typeField: "int",
      size: 4,
    },
    {
      field: "StatusContagem",
      label: "StatusContagem",
      name: "StatusContagem",
      typeField: "int",
      size: 4,
    },
    {
      field: "NumBalanco",
      label: "NumBalanco",
      name: "NumBalanco",
      typeField: "int",
      size: 2,
    },
  ],
};
