import { TTableDef } from "@/types/model";

export const TabBan: TTableDef = {
  database: "plano",
  table: "TabBan",
  fields: [
    {
      field: "CdBanco",
      label: "CdBanco",
      name: "TabBan_id",
      typeField: "int",
      size: 2,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "NmBanco",
      label: "NmBanco",
      name: "NmBanco",
      typeField: "string",
      size: 50,
    },
    {
      field: "IdEmpresa",
      label: "IdEmpresa",
      name: "IdEmpresa",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "SiglaEmpresa",
      label: "SiglaEmpresa",
      name: "SiglaEmpresa",
      typeField: "string",
      size: 30,
    },
    {
      field: "FgTipoProducao",
      label: "FgTipoProducao",
      name: "FgTipoProducao",
      typeField: "string",
      size: 1,
    },
    {
      field: "NmCedente",
      label: "NmCedente",
      name: "NmCedente",
      typeField: "string",
      size: 40,
    },
    {
      field: "NumeroContratoCaucao",
      label: "NumeroContratoCaucao",
      name: "NumeroContratoCaucao",
      typeField: "string",
      size: 10,
    },
    {
      field: "NumeroConvenio",
      label: "NumeroConvenio",
      name: "NumeroConvenio",
      typeField: "string",
      size: 10,
    },
    {
      field: "FgSacador",
      label: "FgSacador",
      name: "FgSacador",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgValorMulta",
      label: "FgValorMulta",
      name: "FgValorMulta",
      typeField: "string",
      size: 1,
    },
    {
      field: "PercMulta",
      label: "PercMulta",
      name: "PercMulta",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "FgAtivo",
      label: "FgAtivo",
      name: "FgAtivo",
      typeField: "string",
      size: 1,
      allowNull: false,
    },
    {
      field: "LogoMarcaBanco",
      label: "LogoMarcaBanco",
      name: "LogoMarcaBanco",
      typeField: "string",
      size: 128,
    },
  ],
};
