import { TTableDef } from "@mono/types/model";

export const TabDep: TTableDef = {
  database: "plano",
  table: "TabDep",
  fields: [
    {
      field: "CdDepartamento",
      label: "CdDepartamento",
      name: "TabDep_id",
      typeField: "int",
      size: 2,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "NmDepartamento",
      label: "NmDepartamento",
      name: "NmDepartamento",
      typeField: "string",
      size: 30,
    },
    {
      field: "PercLucro",
      label: "PercLucro",
      name: "PercLucro",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "FgEstoque",
      label: "FgEstoque",
      name: "FgEstoque",
      typeField: "string",
      size: 1,
    },
    {
      field: "FgListaPreco",
      label: "FgListaPreco",
      name: "FgListaPreco",
      typeField: "string",
      size: 1,
    },
    {
      field: "DtUltAlteracao",
      label: "DtUltAlteracao",
      name: "DtUltAlteracao",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "PercDescMaxGerente",
      label: "PercDescMaxGerente",
      name: "PercDescMaxGerente",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "PercDescMaxVendedor",
      label: "PercDescMaxVendedor",
      name: "PercDescMaxVendedor",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "PontosMilhagem",
      label: "PontosMilhagem",
      name: "PontosMilhagem",
      typeField: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "SeqGrade",
      label: "SeqGrade",
      name: "SeqGrade",
      typeField: "int",
      size: 5,
    },
  ],
};
