import { TTableDef } from "@/types/model";

export const TabMovCCartao: TTableDef = {
  database: "plano",
  table: "TabMovCCartao",
  fields: [
    {
      field: "CdEmpresa",
      label: "CdEmpresa",
      name: "CdEmpresa",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "CdFilial",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "Usuario",
      label: "Usuario",
      name: "Usuario",
      typeField: "string",
      size: 16,
      allowNull: false,
    },
    {
      field: "DtBase",
      label: "DtBase",
      name: "DtBase",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "Sequencia",
      label: "Sequencia",
      name: "Sequencia",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "NumNota",
      label: "NumNota",
      name: "NumNota",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "Serie",
      label: "Serie",
      name: "Serie",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "Modelo",
      typeField: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "Bandeira",
      label: "Bandeira",
      name: "Bandeira",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "CNPJCredenciadora",
      label: "CNPJCredenciadora",
      name: "CNPJCredenciadora",
      typeField: "int",
      size: 9,
      allowNull: false,
    },
    {
      field: "TipoIntegracao",
      label: "TipoIntegracao",
      name: "TipoIntegracao",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "NumAutorizacao",
      label: "NumAutorizacao",
      name: "NumAutorizacao",
      typeField: "string",
      size: 20,
      allowNull: false,
    },
    {
      field: "CdCredenciadora",
      label: "CdCredenciadora",
      name: "CdCredenciadora",
      typeField: "int",
      size: 5,
    },
  ],
};
