import { TTableDef } from "../../../../types/model";

export const TempCombo: TTableDef = {
  database: "plano",
  table: "TempCombo",
  fields: [
    {
      field: "Estacao",
      label: "Estacao",
      name: "Estacao",
      typeField: "string",
      size: 64,
      allowNull: false,
    },
    {
      field: "Origem",
      label: "Origem",
      name: "Origem",
      typeField: "string",
      size: 4,
      allowNull: false,
    },
    {
      field: "Sequencia",
      label: "Sequencia",
      name: "Sequencia",
      typeField: "int",
      size: 5,
      allowNull: false,
    },
    {
      field: "CdCombo",
      label: "CdCombo",
      name: "CdCombo",
      typeField: "string",
      size: 18,
      allowNull: false,
    },
    {
      field: "CdProduto",
      label: "CdProduto",
      name: "CdProduto",
      typeField: "string",
      size: 18,
      allowNull: false,
    },
    {
      field: "QtdeMinima",
      label: "QtdeMinima",
      name: "QtdeMinima",
      typeField: "int",
      size: 5,
      scale: 5,
      allowNull: false,
    },
    {
      field: "QtdeMaxima",
      label: "QtdeMaxima",
      name: "QtdeMaxima",
      typeField: "int",
      size: 5,
      scale: 5,
      allowNull: false,
    },
    {
      field: "VlUnidadeCombo",
      label: "VlUnidadeCombo",
      name: "VlUnidadeCombo",
      typeField: "int",
      size: 9,
      scale: 5,
      allowNull: false,
    },
    {
      field: "QtdeVendida",
      label: "QtdeVendida",
      name: "QtdeVendida",
      typeField: "int",
      size: 5,
      scale: 5,
      allowNull: false,
    },
    {
      field: "VlUnidadeVenda",
      label: "VlUnidadeVenda",
      name: "VlUnidadeVenda",
      typeField: "int",
      size: 9,
      scale: 5,
      allowNull: false,
    },
    {
      field: "QtdeUtilizada",
      label: "QtdeUtilizada",
      name: "QtdeUtilizada",
      typeField: "int",
      size: 5,
      scale: 5,
      allowNull: false,
    },
    {
      field: "QtdeCombo",
      label: "QtdeCombo",
      name: "QtdeCombo",
      typeField: "int",
      size: 5,
      scale: 5,
      allowNull: false,
    },
  ],
};
