import { TTableDef } from "../../../../types/model";

export const TempoProducao: TTableDef = {
  database: "plano",
  table: "TempoProducao",
  fields: [
    {
      field: "NumItens",
      label: "NumItens",
      name: "TempoProducao_id",
      typeField: "int",
      size: 2,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "NumCapsulas",
      label: "NumCapsulas",
      name: "NumCapsulas",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TempoLaboratorio",
      label: "TempoLaboratorio",
      name: "TempoLaboratorio",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TempoTelemarketing",
      label: "TempoTelemarketing",
      name: "TempoTelemarketing",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TempoBalcao",
      label: "TempoBalcao",
      name: "TempoBalcao",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "TempoControleQualidade",
      label: "TempoControleQualidade",
      name: "TempoControleQualidade",
      typeField: "int",
      size: 2,
      allowNull: false,
    },
    {
      field: "DtUltAlteracao",
      label: "DtUltAlteracao",
      name: "DtUltAlteracao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
  ],
};
