import { TTableDef } from "@/types/model";

export const TipoVenda: TTableDef = {
  database: "plano",
  table: "TipoVenda",
  fields: [
    {
      field: "CdTipoVenda",
      label: "CdTipoVenda",
      name: "TipoVenda_id",
      typeField: "int",

      primaryKey: true,
      allowNull: false,
    },
    {
      field: "Descricao",
      label: "Descricao",
      name: "Descricao",
      typeField: "string",
    },
    {
      field: "Dinheiro",
      label: "Dinheiro",
      name: "Dinheiro",
      typeField: "string",
    },
    {
      field: "Cheque",
      label: "Cheque",
      name: "Cheque",
      typeField: "string",
    },
    {
      field: "Cartao",
      label: "Cartao",
      name: "Cartao",
      typeField: "string",
    },
    {
      field: "PreDatado",
      label: "PreDatado",
      name: "PreDatado",
      typeField: "string",
    },
    {
      field: "Debito",
      label: "Debito",
      name: "Debito",
      typeField: "string",
    },
    {
      field: "Acrescimo",
      label: "Acrescimo",
      name: "Acrescimo",
      typeField: "string",
    },
    {
      field: "Faturamento",
      label: "Faturamento",
      name: "Faturamento",
      typeField: "string",
    },
    {
      field: "Percentual",
      label: "Percentual",
      name: "Percentual",
      typeField: "float",

      scale: 4,
    },
    {
      field: "PercVenda",
      label: "PercVenda",
      name: "PercVenda",
      typeField: "string",
    },
    {
      field: "Ticket",
      label: "Ticket",
      name: "Ticket",
      typeField: "string",
    },
    {
      field: "TrocoCheque",
      label: "TrocoCheque",
      name: "TrocoCheque",
      typeField: "string",
    },
    {
      field: "TrocoTicket",
      label: "TrocoTicket",
      name: "TrocoTicket",
      typeField: "string",
    },
    {
      field: "Desconto",
      label: "Desconto",
      name: "Desconto",
      typeField: "string",
    },
    {
      field: "ExibeDevolucao",
      label: "ExibeDevolucao",
      name: "ExibeDevolucao",
      typeField: "string",
    },
    {
      field: "TextoCliente",
      label: "TextoCliente",
      name: "TextoCliente",
      typeField: "string",
    },
    {
      field: "ComprovanteCre",
      label: "ComprovanteCre",
      name: "ComprovanteCre",
      typeField: "string",
    },
    {
      field: "FgRecalculaDesconto",
      label: "FgRecalculaDesconto",
      name: "FgRecalculaDesconto",
      typeField: "string",
    },
    {
      field: "TipoPreco",
      label: "TipoPreco",
      name: "TipoPreco",
      typeField: "string",
    },
    {
      field: "FgEstatistica",
      label: "FgEstatistica",
      name: "FgEstatistica",
      typeField: "string",
    },
    {
      field: "ReembolsoPostal",
      label: "ReembolsoPostal",
      name: "ReembolsoPostal",
      typeField: "string",
    },
    {
      field: "FgAceitaEmissaoCupom",
      label: "FgAceitaEmissaoCupom",
      name: "FgAceitaEmissaoCupom",
      typeField: "string",
    },
    {
      field: "TipoOperacao",
      label: "TipoOperacao",
      name: "TipoOperacao",
      typeField: "string",

      allowNull: false,
    },
    {
      field: "UtilizacaoCreditoCliente",
      label: "UtilizacaoCreditoCliente",
      name: "UtilizacaoCreditoCliente",
      typeField: "string",
    },
    {
      field: "Financiamento",
      label: "Financiamento",
      name: "Financiamento",
      typeField: "string",
    },
    {
      field: "DepositoBancario",
      label: "DepositoBancario",
      name: "DepositoBancario",
      typeField: "string",
    },
    {
      field: "Bonificacao",
      label: "Bonificacao",
      name: "Bonificacao",
      typeField: "string",
    },
    {
      field: "FgReceberNoLocal",
      label: "FgReceberNoLocal",
      name: "FgReceberNoLocal",
      typeField: "string",
    },
    {
      field: "FgAtivo",
      label: "FgAtivo",
      name: "FgAtivo",
      typeField: "string",
    },
    {
      field: "FgImprimirCarne",
      label: "FgImprimirCarne",
      name: "FgImprimirCarne",
      typeField: "string",
    },
  ],
};
