@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}

### LIST
GET {{host}}/api/trpc/agendaTelefone.list
?input={"order":[["agenda_telefone_id","asc"]]}

### READ
GET {{host}}/api/trpc/agendaTelefone.read
?input={"id":{"agenda_telefone_id":"1"}}

### CREATE
POST {{host}}/api/trpc/agendaTelefone.create
Content-Type: application/json

{"agenda_telefone_id":"1", "nome":"Fulano"}
