import { TTableDef } from "../../../../types/model";

export const tbl_OP_Botao: TTableDef = {
  database: "oftalmo",
  table: "tbl_OP_Botao",
  fields: [
    {
      field: "kOPBotao",
      label: "kOPBotao",
      name: "tbl_OP_Botao_id",
      typeField: "string",
      size: 8,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "Lote",
      label: "Lote",
      name: "Lote",
      typeField: "string",
      size: 50,
    },
    {
      field: "NomeUsuario",
      label: "NomeUsuario",
      name: "NomeUsuario",
      typeField: "string",
      size: 50,
    },
    {
      field: "DataEmissao",
      label: "DataEmissao",
      name: "DataEmissao",
      typeField: "date",
      size: 4,
    },
    {
      field: "Regulador",
      label: "Regulador",
      name: "Regulador",
      typeField: "string",
      size: 50,
    },
    {
      field: "DataRegulagem",
      label: "DataRegulagem",
      name: "DataRegulagem",
      typeField: "date",
      size: 4,
    },
    {
      field: "Travado",
      label: "Travado",
      name: "Travado",
      typeField: "int",
      size: 1,
      allowNull: false,
      defaultValue: "0",
    },
    {
      field: "IdAuxiliar",
      label: "IdAuxiliar",
      name: "IdAuxiliar",
      typeField: "int",
      size: 4,
      autoIncrement: true,
      allowNull: false,
    },
  ],
};
