import { TTableDef } from "../../../../types/model";

export const tEsterilizacaoInterna: TTableDef = {
  database: "oftalmo",
  table: "tEsterilizacaoInterna",
  fields: [
    {
      field: "kLoteEstInt",
      label: "kLoteEstInt",
      name: "tEsterilizacaoInterna_id",
      typeField: "int",
      size: 4,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "Data",
      label: "Data",
      name: "Data",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "Resultado",
      label: "Resultado",
      name: "Resultado",
      typeField: "string",
      size: 1,
    },
    {
      field: "UsuarioResultado",
      label: "UsuarioResultado",
      name: "UsuarioResultado",
      typeField: "string",
      size: 50,
    },
    {
      field: "Obs",
      label: "Obs",
      name: "Obs",
      typeField: "string",
      size: 4000,
    },
    {
      field: "Fechado",
      label: "Fechado",
      name: "Fechado",
      typeField: "int",
      size: 1,
      defaultValue: "0",
    },
    {
      field: "UsuarioFechamento",
      label: "UsuarioFechamento",
      name: "UsuarioFechamento",
      typeField: "string",
      size: 50,
    },
    {
      field: "DataFechamento",
      label: "DataFechamento",
      name: "DataFechamento",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DataHoraAutoclave",
      label: "DataHoraAutoclave",
      name: "DataHoraAutoclave",
      typeField: "date",
      size: 4,
    },
  ],
};
