import { TTableDef } from "@/types/model";

export const tManutencaoPreventiva: TTableDef = {
  database: "oftalmo",
  table: "tManutencaoPreventiva",
  fields: [
    {
      field: "kManutencaoPreventiva",
      label: "kManutencaoPreventiva",
      name: "tManutencaoPreventiva_id",
      typeField: "int",
      size: 4,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "fkMaquina",
      label: "fkMaquina",
      name: "fkMaquina",
      typeField: "string",
      size: 30,
      allowNull: false,
    },
    {
      field: "DataManutencao",
      label: "DataManutencao",
      name: "DataManutencao",
      typeField: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "DataHoraInicio",
      label: "DataHoraInicio",
      name: "DataHoraInicio",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "DataHoraFinal",
      label: "DataHoraFinal",
      name: "DataHoraFinal",
      typeField: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "MaterialUtilizadoItemProblema",
      label: "MaterialUtilizadoItemProblema",
      name: "MaterialUtilizadoItemProblema",
      typeField: "string",
      size: 16,
    },
    {
      field: "Observacao",
      label: "Observacao",
      name: "Observacao",
      typeField: "string",
      size: 16,
    },
    {
      field: "ResponsavelManutencao",
      label: "ResponsavelManutencao",
      name: "ResponsavelManutencao",
      typeField: "string",
      size: 150,
    },
    {
      field: "MotivoNaoConclusaoNoPrazo",
      label: "MotivoNaoConclusaoNoPrazo",
      name: "MotivoNaoConclusaoNoPrazo",
      typeField: "string",
      size: 16,
    },
    {
      field: "UsuarioConclusao",
      label: "UsuarioConclusao",
      name: "UsuarioConclusao",
      typeField: "string",
      size: 50,
    },
    {
      field: "LiberadoPor",
      label: "LiberadoPor",
      name: "LiberadoPor",
      typeField: "string",
      size: 150,
    },
  ],
};
