import { TTableDef } from "@/types/model";

export const tOcorrencia: TTableDef = {
  database: "oftalmo",
  table: "tOcorrencia",
  fields: [
    {
      field: "kOcorrencia",
      label: "kOcorrencia",
      name: "tOcorrencia_id",
      typeField: "int",
      size: 4,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "TipoOcorrencia",
      label: "TipoOcorrencia",
      name: "TipoOcorrencia",
      typeField: "string",
      size: 50,
      allowNull: false,
    },
    {
      field: "OrigemOcorrencia",
      label: "OrigemOcorrencia",
      name: "OrigemOcorrencia",
      typeField: "string",
      size: 50,
      allowNull: false,
    },
    {
      field: "Descricao",
      label: "Descricao",
      name: "Descricao",
      typeField: "string",
      size: 16,
    },
    {
      field: "DataDescricao",
      label: "DataDescricao",
      name: "DataDescricao",
      typeField: "date",
      size: 4,
    },
    {
      field: "UsuarioDescricao",
      label: "UsuarioDescricao",
      name: "UsuarioDescricao",
      typeField: "string",
      size: 30,
    },
    {
      field: "Analise",
      label: "Analise",
      name: "Analise",
      typeField: "string",
      size: 16,
    },
    {
      field: "DataAnalise",
      label: "DataAnalise",
      name: "DataAnalise",
      typeField: "date",
      size: 4,
    },
    {
      field: "UsuarioAnalise",
      label: "UsuarioAnalise",
      name: "UsuarioAnalise",
      typeField: "string",
      size: 30,
    },
    {
      field: "Solucao",
      label: "Solucao",
      name: "Solucao",
      typeField: "string",
      size: 16,
    },
    {
      field: "DataSolucao",
      label: "DataSolucao",
      name: "DataSolucao",
      typeField: "date",
      size: 4,
    },
    {
      field: "UsuarioSolucao",
      label: "UsuarioSolucao",
      name: "UsuarioSolucao",
      typeField: "string",
      size: 30,
    },
    {
      field: "PrazoImplemSolucao",
      label: "PrazoImplemSolucao",
      name: "PrazoImplemSolucao",
      typeField: "date",
      size: 4,
    },
    {
      field: "DataImplemSolucao",
      label: "DataImplemSolucao",
      name: "DataImplemSolucao",
      typeField: "date",
      size: 4,
    },
    {
      field: "UsuarioImplemSolucao",
      label: "UsuarioImplemSolucao",
      name: "UsuarioImplemSolucao",
      typeField: "string",
      size: 30,
    },
    {
      field: "AcaoPreventiva",
      label: "AcaoPreventiva",
      name: "AcaoPreventiva",
      typeField: "string",
      size: 16,
    },
    {
      field: "DataAcao",
      label: "DataAcao",
      name: "DataAcao",
      typeField: "date",
      size: 4,
    },
    {
      field: "UsuarioAcao",
      label: "UsuarioAcao",
      name: "UsuarioAcao",
      typeField: "string",
      size: 30,
    },
    {
      field: "PrazoImplemAcao",
      label: "PrazoImplemAcao",
      name: "PrazoImplemAcao",
      typeField: "date",
      size: 4,
    },
    {
      field: "DataImplemAcao",
      label: "DataImplemAcao",
      name: "DataImplemAcao",
      typeField: "date",
      size: 4,
    },
    {
      field: "UsuarioImplemAcao",
      label: "UsuarioImplemAcao",
      name: "UsuarioImplemAcao",
      typeField: "string",
      size: 30,
    },
    {
      field: "Verificacao",
      label: "Verificacao",
      name: "Verificacao",
      typeField: "string",
      size: 16,
    },
    {
      field: "DataVerificacao",
      label: "DataVerificacao",
      name: "DataVerificacao",
      typeField: "date",
      size: 4,
    },
    {
      field: "UsuarioVerificacao",
      label: "UsuarioVerificacao",
      name: "UsuarioVerificacao",
      typeField: "string",
      size: 50,
    },
  ],
};
