import { TTable } from "../../../../types/model";

export const tOperacaoLinhaDeProducao: TTable = {
  database: "oftalmo",
  table: "tOperacaoLinhaDeProducao",
  fields: [
    {
      field: "kOperacaoLP",
      label: "kOperacaoLP",
      name: "tOperacaoLinhaDeProducao_id",
      typeField: "int",
      size: 4,
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "fkLinhaDeProducao",
      label: "fkLinhaDeProducao",
      name: "fkLinhaDeProducao",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "fkOperacao",
      label: "fkOperacao",
      name: "fkOperacao",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "Condicional",
      label: "Condicional",
      name: "Condicional",
      typeField: "int",
      size: 1,
      allowNull: false,
      defaultValue: "0",
    },
    {
      field: "NextOLP",
      label: "NextOLP",
      name: "NextOLP",
      typeField: "int",
      size: 4,
    },
    {
      field: "NextOLPRet",
      label: "NextOLPRet",
      name: "NextOLPRet",
      typeField: "int",
      size: 4,
    },
    {
      field: "Ordem",
      label: "Ordem",
      name: "Ordem",
      typeField: "int",
      size: 4,
      allowNull: false,
    },
    {
      field: "MarcoA",
      label: "MarcoA",
      name: "MarcoA",
      typeField: "int",
      size: 1,
      allowNull: false,
      defaultValue: "0",
    },
    {
      field: "CheckOrdem",
      label: "CheckOrdem",
      name: "CheckOrdem",
      typeField: "string",
      size: 10,
    },
    {
      field: "CheckOrdemRet",
      label: "CheckOrdemRet",
      name: "CheckOrdemRet",
      typeField: "int",
      size: 4,
    },
    {
      field: "CheckOrdemIsNotNeedClosed",
      label: "CheckOrdemIsNotNeedClosed",
      name: "CheckOrdemIsNotNeedClosed",
      typeField: "int",
      size: 1,
    },
    {
      field: "CheckQtd",
      label: "CheckQtd",
      name: "CheckQtd",
      typeField: "int",
      size: 4,
    },
    {
      field: "CheckQtdRet",
      label: "CheckQtdRet",
      name: "CheckQtdRet",
      typeField: "int",
      size: 4,
    },
    {
      field: "CheckAmostragem",
      label: "CheckAmostragem",
      name: "CheckAmostragem",
      typeField: "int",
      size: 4,
    },
  ],
};
