### Analitico
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"vendaAnalitico",
  "params":{
    "inicio":"2020-01-01",
    "fim":"2020-01-10"
  }
}
### Diario
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"vendaDiario",
  "params":{
    "inicio":"2020-01-01",
    "fim":"2020-01-31",
    "uf": ["MG"]
  }
}

### Mensal
POST http://localhost:3000/api/rpc
Content-Type: application/json

{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"vendaMensal",
  "params":{
    "inicio":"2021-01-01",
    "fim":"2021-03-31",
    "id": ["189"],
    "sql": false
  }
}
