@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}


### Venda Mensal
POST http://localhost:3000/api/knex/sql/oftalmo

### Venda diaria
GET {{host}}/api/trpc/nfSaida.vendaDiario?input={"fim":"2020-01-01","inicio":"2020-02-01","uf":["MG"]}
