import { TTable } from "../types";

export const vendedor: TTable = {
  database: "plano",
  table: "CadVen",
  fields: [
    {
      field: "CdVendedor",
      label: "CdVendedor",
      name: "vendedor_id",
      type: "float",
      size: 8,
      scale: 4,
      primaryKey: true,
      allowNull: false,
    },
    {
      field: "NmVendedor",
      label: "NmVendedor",
      name: "vendedor",
      type: "string",
      size: 70,
      allowNull: false,
    },
    {
      field: "Endereco",
      label: "Endereco",
      name: "endereco",
      type: "string",
      size: 70,
      allowNull: false,
    },
    {
      field: "Cidade",
      label: "Cidade",
      name: "cidade",
      type: "string",
      size: 30,
    },
    {
      field: "Uf",
      label: "Uf",
      name: "uf",
      type: "string",
      size: 2,
    },
    {
      field: "CPF",
      label: "CPF",
      name: "cpf",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Identidade",
      label: "Identidade",
      name: "identidade",
      type: "string",
      size: 18,
      allowNull: false,
    },
    {
      field: "Telefone",
      label: "Telefone",
      name: "telefone",
      type: "string",
      size: 20,
    },
    {
      field: "FgControle",
      label: "FgControle",
      name: "eh_controle",
      type: "string",
      size: 1,
    },
    {
      field: "Meta",
      label: "Meta",
      name: "meta",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Venda",
      label: "Venda",
      name: "venda",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "ComissaoAV",
      label: "ComissaoAV",
      name: "ComissaoAV",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "ComissaoPZ",
      label: "ComissaoPZ",
      name: "ComissaoPZ",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "DtUltAlteracao",
      label: "DtUltAlteracao",
      name: "DtUltAlteracao",
      type: "datetime",
      size: 8,
      scale: 3,
    },
    {
      field: "Cargo",
      label: "Cargo",
      name: "cargo",
      type: "string",
      size: 30,
    },
    {
      field: "PercLimiteComissao",
      label: "PercLimiteComissao",
      name: "PercLimiteComissao",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "FgAtivo",
      label: "FgAtivo",
      name: "eh_ativo",
      type: "string",
      size: 1,
    },
    {
      field: "Bairro",
      label: "Bairro",
      name: "bairro",
      type: "string",
      size: 32,
    },
    {
      field: "TelefoneAdicional",
      label: "TelefoneAdicional",
      name: "TelefoneAdicional",
      type: "string",
      size: 32,
    },
    {
      field: "Email",
      label: "Email",
      name: "email",
      type: "string",
      size: 128,
    },
    {
      field: "PercComissaoVarejoVista",
      label: "PercComissaoVarejoVista",
      name: "PercComissaoVarejoVista",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "PercComissaoAtacadoVista",
      label: "PercComissaoAtacadoVista",
      name: "PercComissaoAtacadoVista",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "PercComissaoVarejoPrazo",
      label: "PercComissaoVarejoPrazo",
      name: "PercComissaoVarejoPrazo",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "PercComissaoAtacadoPrazo",
      label: "PercComissaoAtacadoPrazo",
      name: "PercComissaoAtacadoPrazo",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "Cep",
      label: "Cep",
      name: "cep",
      type: "float",
      size: 8,
      scale: 4,
    },
    {
      field: "NmFantasia",
      label: "NmFantasia",
      name: "NmFantasia",
      type: "string",
      size: 64,
    },
    {
      field: "FgFuncionarioOS",
      label: "FgFuncionarioOS",
      name: "FgFuncionarioOS",
      type: "string",
      size: 1,
    },
    {
      field: "FgTecnicoOS",
      label: "FgTecnicoOS",
      name: "FgTecnicoOS",
      type: "string",
      size: 1,
    },
  ],
};
