import { TEntity } from "@er/types/*";

export const nf_entrada_log: TEntity = {
  database: "plano",
  table: "NfLogConferencia",
  fields: [
    {
      field: "CdFilial",
      label: "CdFilial",
      name: "filial_id",
      primaryKey: true,
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "NumNota",
      label: "NumNota",
      name: "nota_id",
      primaryKey: true,
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "Serie",
      label: "Serie",
      name: "serie_id",
      primaryKey: true,
      type: "string",
      size: 3,
      allowNull: false,
    },
    {
      field: "CdFornecedor",
      label: "CdFornecedor",
      name: "fornecedor_id",
      type: "float",
      size: 8,
      scale: 4,
      allowNull: false,
    },
    {
      field: "Data",
      label: "Data",
      name: "Data",
      type: "datetime",
      size: 8,
      scale: 3,
      allowNull: false,
    },
    {
      field: "Usuario",
      label: "Usuario",
      name: "usuario",
      type: "string",
      size: 32,
      allowNull: false,
    },
    {
      field: "Operacao",
      label: "Operacao",
      name: "operacao",
      type: "string",
      size: 1024,
      allowNull: false,
    },
    {
      field: "Modelo",
      label: "Modelo",
      name: "modelo",
      type: "string",
      size: 3,
      allowNull: false,
    },
  ],
};
