export default {
  femaleName: [
    "Alessandra",
    "Alice",
    "Aline",
    "Alícia",
    "Ana Clara",
    "Ana Júlia",
    "Ana Laura",
    "Ana Luiza",
    "Antonella",
    "Beatriz",
    "Bruna",
    "Carla",
    "Cecília",
    "Clara",
    "Célia",
    "Dalila",
    "Eduarda",
    "Elisa",
    "Eloá",
    "Emanuelly",
    "Esther",
    "Fabrícia",
    "Felícia",
    "Giovanna",
    "Helena",
    "Heloísa",
    "Isabel",
    "Isabela",
    "Isabella",
    "Isabelly",
    "Isis",
    "Janaína",
    "Joana",
    "Júlia",
    "Karla",
    "Lara",
    "Larissa",
    "Laura",
    "Lavínia",
    "Liz",
    "Lorena",
    "Lorraine",
    "Luiza",
    "Lívia",
    "Maitê",
    "Manuela",
    "Marcela",
    "Margarida",
    "Maria",
    "Maria Alice",
    "Maria Cecília",
    "Maria Clara",
    "Maria Eduarda",
    "Maria Helena",
    "Maria Júlia",
    "Maria Luiza",
    "Mariana",
    "Marina",
    "Marli",
    "Meire",
    "Melissa",
    "Morgana",
    "Márcia",
    "Mércia",
    "Natália",
    "Núbia",
    "Ofélia",
    "Paula",
    "Rafaela",
    "Rebeca",
    "Roberta",
    "Sara",
    "Sarah",
    "Sophia",
    "Suélen",
    "Sílvia",
    "Talita",
    "Valentina",
    "Vitória",
    "Yasmin",
  ],

  maleName: [
    "Alessandro",
    "Alexandre",
    "Anthony",
    "Antônio",
    "Arthur",
    "Benjamin",
    "Benício",
    "Bernardo",
    "Breno",
    "Bryan",
    "Caio",
    "Calebe",
    "Carlos",
    "Cauã",
    "César",
    "Daniel",
    "Danilo",
    "Davi",
    "Davi Lucca",
    "Deneval",
    "Eduardo",
    "Elísio",
    "Emanuel",
    "Enzo",
    "Enzo Gabriel",
    "Fabiano",
    "Fabrício",
    "Feliciano",
    "Felipe",
    "Frederico",
    "Fábio",
    "Félix",
    "Gabriel",
    "Gael",
    "Guilherme",
    "Gustavo",
    "Gúbio",
    "Heitor",
    "Henrique",
    "Hugo",
    "Hélio",
    "Isaac",
    "Joaquim",
    "João",
    "João Lucas",
    "João Miguel",
    "João Pedro",
    "Júlio",
    "Júlio César",
    "Kléber",
    "Ladislau",
    "Leonardo",
    "Lorenzo",
    "Lucas",
    "Lucca",
    "Marcelo",
    "Marcos",
    "Matheus",
    "Miguel",
    "Murilo",
    "Nataniel",
    "Nicolas",
    "Noah",
    "Norberto",
    "Pablo",
    "Paulo",
    "Pedro",
    "Pedro Henrique",
    "Pietro",
    "Rafael",
    "Raul",
    "Ricardo",
    "Roberto",
    "Salvador",
    "Samuel",
    "Silas",
    "Sirineu",
    "Tertuliano",
    "Théo",
    "Vicente",
    "Vitor",
    "Víctor",
    "Warley",
    "Washington",
    "Yago",
    "Yango",
    "Yuri",
    "Ígor",
  ],

  lastName: [
    "Silva",
    "Souza",
    "Carvalho",
    "Santos",
    "Reis",
    "Xavier",
    "Franco",
    "Braga",
    "Macedo",
    "Batista",
    "Barros",
    "Moraes",
    "Costa",
    "Pereira",
    "Carvalho",
    "Melo",
    "Saraiva",
    "Nogueira",
    "Oliveira",
    "Martins",
    "Moreira",
    "Albuquerque",
  ],

  prefixName: ["Sr.", "Sra.", "Srta.", "Dr.", "Dra."],

  suffixName: ["Jr.", "Neto", "Filho"],

  descriptor: [
    "Líder",
    "Senior",
    "Direto",
    "Corporativo",
    "Dinâmico",
    "Futuro",
    "Produto",
    "Nacional",
    "Regional",
    "Distrito",
    "Central",
    "Global",
    "Cliente",
    "Investidor",
    "Dinâmico",
    "International",
    "Legado",
    "Avançar",
    "Interno",
    "Humano",
    "Chefe",
    "Principal",
  ],
  level: [
    "Soluções",
    "Programa",
    "Marca",
    "Segurança",
    "Pesquisar",
    "Marketing",
    "Diretivas",
    "Implementation",
    "Implementação",
    "Funcionalidade",
    "Resposta",
    "Paradigma",
    "Táticas",
    "Identidade",
    "Mercados",
    "Grupo",
    "Divisão",
    "Aplicações",
    "Otimização",
    "Operações",
    "Infraestrutura",
    "Intranet",
    "Comunicações",
    "Web",
    "Branding",
    "Qualidade",
    "Assurance",
    "Mobilidade",
    "Contas",
    "Dados",
    "Criativo",
    "Configuration",
    "Prestação de contas",
    "Interações",
    "Fatores",
    "Usabilidade",
    "Métricas",
  ],
  job: [
    "Supervisor",
    "Associado",
    "Executivo",
    "Atentende",
    "Policial",
    "Gerente",
    "Engenheiro",
    "Especialista",
    "Diretor",
    "Coordenador",
    "Administrador",
    "Arquiteto",
    "Analista",
    "Designer",
    "Planejador",
    "Orquestrador",
    "Técnico",
    "Desenvolvedor",
    "Produtor",
    "Consultor",
    "Assistente",
    "Facilitador",
    "Agente",
    "Representante",
    "Estrategista",
  ],

  suffixCity: [" do Descoberto", " de Nossa Senhora", " do Norte", " do Sul"],

  country: [
    "Afeganistão",
    "Albânia",
    "Algéria",
    "Samoa",
    "Andorra",
    "Angola",
    "Anguila",
    "Antigua and Barbada",
    "Argentina",
    "Armênia",
    "Aruba",
    "Austrália",
    "Áustria",
    "Azerbaijão",
    "Bahamas",
    "Barém",
    "Bangladesh",
    "Barbados",
    "Bélgica",
    "Belize",
    "Benin",
    "Bermuda",
    "Butão",
    "Bolívia",
    "Bôsnia",
    "Botsuana",
    "Ilha Bouvet",
    "Brasil",
    "Arquipélago de Chagos",
    "Ilhas Virgens",
    "Brunei",
    "Bulgária",
    "Burkina Faso",
    "Burundi",
    "Camboja",
    "Camarões",
    "Canadá",
    "Cabo Verde",
    "Ilhas Caiman",
    "República da África Central",
    "Chade",
    "Chile",
    "China",
    "Ilha do Natal",
    "Ilhas Cocos",
    "Colômbia",
    "Comores",
    "Congo",
    "Ilhas Cook",
    "Costa Rica",
    "Costa do Marfim",
    "Croácia",
    "Cuba",
    "Chipre",
    "República Tcheca",
    "Dinamarca",
    "Jibuti",
    "Dominica",
    "República Dominicana",
    "Equador",
    "Egito",
    "El Salvador",
    "Guiné Equatorial",
    "Eritreia",
    "Estônia",
    "Etiópia",
    "Ilhas Faroe",
    "Malvinas",
    "Fiji",
    "Finlândia",
    "França",
    "Guiné Francesa",
    "Polinésia Francesa",
    "Gabão",
    "Gâmbia",
    "Georgia",
    "Alemanha",
    "Gana",
    "Gibraltar",
    "Grécia",
    "Groelândia",
    "Granada",
    "Guadalupe",
    "Guatemala",
    "Guernesey",
    "Guiné",
    "Guiné-Bissau",
    "Guiana",
    "Haiti",
    "Ilhas Heard e McDonald",
    "Vaticano",
    "Honduras",
    "Hong Kong",
    "Hungria",
    "Islândia",
    "Índia",
    "Indonésia",
    "Irã",
    "Iraque",
    "Irlanda",
    "Ilha de Man",
    "Israel",
    "Itália",
    "Jamaica",
    "Japão",
    "Jersey",
    "Jordânia",
    "Cazaquistão",
    "Quênia",
    "Quiribati",
    "Coreia do Norte",
    "Coreia do Sul",
    "Kuwait",
    "Quirguistão",
    "Laos",
    "Latvia",
    "Líbano",
    "Lesoto",
    "Libéria",
    "Líbia",
    "Liechtenstein",
    "Lituânia",
    "Luxemburgo",
    "Macao",
    "Macedônia",
    "Madagascar",
    "Malawi",
    "Malásia",
    "Maldives",
    "Mali",
    "Malta",
    "Ilhas Marshall",
    "Martinica",
    "Mauritânia",
    "Maurícia",
    "Maiote",
    "México",
    "Micronésia",
    "Moldávia",
    "Mônaco",
    "Mongólia",
    "Montenegro",
    "Montserrat",
    "Marrocos",
    "Moçambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Antilhas Holandesas",
    "Holanda",
    "Nova Caledonia",
    "Nova Zelândia",
    "Nicarágua",
    "Nigéria",
    "Niue",
    "Ilha Norfolk",
    "Marianas Setentrionais",
    "Noruega",
    "Omã",
    "Paquistão",
    "Palau",
    "Território da Palestina",
    "Panamá",
    "Papua-Nova Guiné",
    "Paraguai",
    "Peru",
    "Filipinas",
    "Polônia",
    "Portugal",
    "Porto Rico",
    "Qatar",
    "Romênia",
    "Rússia",
    "Ruanda",
    "São Bartolomeu",
    "Santa Helena",
    "Santa Lúcia",
    "São Martinho",
    "São Pedro e Miquelão",
    "São Vicente e Granadinas",
    "Samoa",
    "San Marino",
    "Sao Tomé e Príncipe",
    "Arábia Saudita",
    "Senegal",
    "Sérvia",
    "Seicheles",
    "Serra Leoa",
    "Singapura",
    "Eslováquia",
    "Eslovênia",
    "Ilhas Salomão",
    "Somália",
    "África do Sul",
    "Ilhas Geórgia do Sul e Sandwich do Sul",
    "Espanha",
    "Sri Lanka",
    "Sudão",
    "Suriname",
    "Ilhas Svalbard & Jan Mayen",
    "Suazilândia",
    "Suécia",
    "Suíça",
    "Síria",
    "Taiwan",
    "Tajiquistão",
    "Tanzânia",
    "Tailândia",
    "Timor-Leste",
    "Togo",
    "Toquelau",
    "Tonga",
    "Trinidad e Tobago",
    "Tunísia",
    "Turquia",
    "Turcomenistão",
    "Turcas e Caicos",
    "Tuvalu",
    "Uganda",
    "Ucrânia",
    "Emirados Árabes Unidos",
    "Reino Unido",
    "Estados Unidos da América",
    "Estados Unidos das Ilhas Virgens",
    "Uruguai",
    "Uzbequistão",
    "Vanuatu",
    "Venezuela",
    "Vietnã",
    "Wallis e Futuna",
    "Iêmen",
    "Zâmbia",
    "Zimbábue",
  ],

  addressDescription: ["Apto.", "Sobrado", "Casa", "Lote", "Quadra"],

  state: [
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Distrito Federal",
    "Espírito Santo",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Minas Gerais",
    "Pará",
    "Paraíba",
    "Paraná",
    "Pernambuco",
    "Piauí",
    "Rio de Janeiro",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Rondônia",
    "Roraima",
    "Santa Catarina",
    "São Paulo",
    "Sergipe",
    "Tocantins",
  ],

  uf: [
    "AC",
    "AL",
    "AP",
    "AM",
    "BA",
    "CE",
    "DF",
    "ES",
    "GO",
    "MA",
    "MT",
    "MS",
    "MG",
    "PA",
    "PB",
    "PR",
    "PE",
    "PI",
    "RJ",
    "RN",
    "RS",
    "RO",
    "RR",
    "SC",
    "SP",
    "SE",
    "TO",
  ],

  prefixStreet: [
    "Rua",
    "Avenida",
    "Travessa",
    "Alameda",
    "Marginal",
    "Rodovia",
  ],

  color: [
    "amarelo",
    "âmbar",
    "ametista",
    "azul",
    "azul celeste",
    "azul marinho",
    "azul petróleo",
    "açafrão",
    "bordô",
    "bronze",
    "caramelo",
    "castanho ",
    "cenoura",
    "cinza",
    "cobre",
    "coral",
    "dourado",
    "escarlate",
    "esmeralda",
    "ferrugem",
    "fuligem",
    "fúchsia",
    "grená",
    "índigo",
    "jade",
    "laranja",
    "lilás",
    "limão",
    "madeira",
    "magenta",
    "marrom",
    "ouro",
    "pele",
    "prata",
    "preto",
    "púrpura",
    "rosa",
    "roxo",
    "salmão",
    "turquesa",
    "verde",
    "verde lima",
    "verde-azulado",
    "vermelho",
    "violeta",
  ],

  department: [
    "Livros",
    "Filmes",
    "Música",
    "Jogos",
    "Eletrônicos",
    "Computadores",
    "Casa",
    "Jardim",
    "Ferramentas",
    "Mercearia",
    "Saúde",
    "Beleza",
    "Brinquedos",
    "Crianças",
    "Bebê",
    "Roupas",
    "Sapatos",
    "Jóias",
    "Esportes",
    "Turismo",
    "Automotivo",
    "Industrial",
  ],

  productAdjective: [
    "Pequeno",
    "Ergonômico",
    "Rústico",
    "Inteligente",
    "Lindo",
    "Incrível",
    "Fantástico",
    "Prático",
    "Lustroso",
    "Impressionante",
    "Genérico",
    "Feito à mão",
    "Licenciado",
    "Refinado",
    "Sem marca",
    "Gostoso",
  ],
  productMaterial: [
    "Aço",
    "Madeira",
    "Concreto",
    "Plástico",
    "Algodão",
    "Granito",
    "Borracha",
    "Metal",
    "Macio",
    "Fresco",
    "Congelado",
  ],
  product: [
    "Cadeira",
    "Carro",
    "Computador",
    "Teclado",
    "Mouse",
    "Bicicleta",
    "Bola",
    "Luvas",
    "Calças",
    "Camiseta",
    "Mesa",
    "Sapatos",
    "Chapéu",
    "Toalhas",
    "Sabonete",
    "Atum",
    "Frango",
    "Peixe",
    "Queijo",
    "Bacon",
    "Pizza",
    "Salada",
    "Salsicha",
    "Salgadinhos",
  ],

  companySuffix: ["S.A.", "LTDA", "EIRELI", "e Associados", "Comércio"],

  email: [
    "gmail.com",
    "yahoo.com",
    "hotmail.com",
    "live.com",
    "outlook.com",
    "bol.com.br",
  ],

  words: [
    "alias",
    "consequatur",
    "aut",
    "perferendis",
    "sit",
    "voluptatem",
    "accusantium",
    "doloremque",
    "aperiam",
    "eaque",
    "ipsa",
    "quae",
    "ab",
    "illo",
    "inventore",
    "veritatis",
    "et",
    "quasi",
    "architecto",
    "beatae",
    "vitae",
    "dicta",
    "sunt",
    "explicabo",
    "aspernatur",
    "aut",
    "odit",
    "aut",
    "fugit",
    "sed",
    "quia",
    "consequuntur",
    "magni",
    "dolores",
    "eos",
    "qui",
    "ratione",
    "voluptatem",
    "sequi",
    "nesciunt",
    "neque",
    "dolorem",
    "ipsum",
    "quia",
    "dolor",
    "sit",
    "amet",
    "consectetur",
    "adipisci",
    "velit",
    "sed",
    "quia",
    "non",
    "numquam",
    "eius",
    "modi",
    "tempora",
    "incidunt",
    "ut",
    "labore",
    "et",
    "dolore",
    "magnam",
    "aliquam",
    "quaerat",
    "voluptatem",
    "ut",
    "enim",
    "ad",
    "minima",
    "veniam",
    "quis",
    "nostrum",
    "exercitationem",
    "ullam",
    "corporis",
    "nemo",
    "enim",
    "ipsam",
    "voluptatem",
    "quia",
    "voluptas",
    "sit",
    "suscipit",
    "laboriosam",
    "nisi",
    "ut",
    "aliquid",
    "ex",
    "ea",
    "commodi",
    "consequatur",
    "quis",
    "autem",
    "vel",
    "eum",
    "iure",
    "reprehenderit",
    "qui",
    "in",
    "ea",
    "voluptate",
    "velit",
    "esse",
    "quam",
    "nihil",
    "molestiae",
    "et",
    "iusto",
    "odio",
    "dignissimos",
    "ducimus",
    "qui",
    "blanditiis",
    "praesentium",
    "laudantium",
    "totam",
    "rem",
    "voluptatum",
    "deleniti",
    "atque",
    "corrupti",
    "quos",
    "dolores",
    "et",
    "quas",
    "molestias",
    "excepturi",
    "sint",
    "occaecati",
    "cupiditate",
    "non",
    "provident",
    "sed",
    "ut",
    "perspiciatis",
    "unde",
    "omnis",
    "iste",
    "natus",
    "error",
    "similique",
    "sunt",
    "in",
    "culpa",
    "qui",
    "officia",
    "deserunt",
    "mollitia",
    "animi",
    "id",
    "est",
    "laborum",
    "et",
    "dolorum",
    "fuga",
    "et",
    "harum",
    "quidem",
    "rerum",
    "facilis",
    "est",
    "et",
    "expedita",
    "distinctio",
    "nam",
    "libero",
    "tempore",
    "cum",
    "soluta",
    "nobis",
    "est",
    "eligendi",
    "optio",
    "cumque",
    "nihil",
    "impedit",
    "quo",
    "porro",
    "quisquam",
    "est",
    "qui",
    "minus",
    "id",
    "quod",
    "maxime",
    "placeat",
    "facere",
    "possimus",
    "omnis",
    "voluptas",
    "assumenda",
    "est",
    "omnis",
    "dolor",
    "repellendus",
    "temporibus",
    "autem",
    "quibusdam",
    "et",
    "aut",
    "consequatur",
    "vel",
    "illum",
    "qui",
    "dolorem",
    "eum",
    "fugiat",
    "quo",
    "voluptas",
    "nulla",
    "pariatur",
    "at",
    "vero",
    "eos",
    "et",
    "accusamus",
    "officiis",
    "debitis",
    "aut",
    "rerum",
    "necessitatibus",
    "saepe",
    "eveniet",
    "ut",
    "et",
    "voluptates",
    "repudiandae",
    "sint",
    "et",
    "molestiae",
    "non",
    "recusandae",
    "itaque",
    "earum",
    "rerum",
    "hic",
    "tenetur",
    "a",
    "sapiente",
    "delectus",
    "ut",
    "aut",
    "reiciendis",
    "voluptatibus",
    "maiores",
    "doloribus",
    "asperiores",
    "repellat",
  ],
};
