### diaria
POST http://localhost:3000/api/knex/sql/oftalmo
Content-Type: application/json

{
  "from":{"raw":        "NatOpe INNER JOIN (CategPro INNER JOIN (CadPro INNER JOIN (MestreNota INNER JOIN ItemNota ON (MestreNota.Serie = ItemNota.Serie) AND (MestreNota.NumNota = ItemNota.NumNota) AND (MestreNota.CdFilial = ItemNota.CdFilial)) ON CadPro.CdProduto = ItemNota.CdProduto) ON CategPro.CdCategoria = CadPro.CdCategoria) ON (ItemNota.Nop = NatOpe.Nop) AND (NatOpe.Nop = MestreNota.Nop)"
},
  "select":[{ "raw":           "CONVERT(CHAR(10),[mestrenota].[DtEmissao],120) AS dia, CategPro.NmCategoria as categoria, Sum(ItemNota.Quantidade) AS quantidade"
 } ],
  "sum":[{ "quantidade": "QtdConforme" }],
  "where":[
    [ "MestreNota.CdFilial", 1],
    [ "MestreNota.Tipo","<>","C"],
    [ "MestreNota.NotadeComplemento","N"],
    ["NatOpe.Nop", 5151]
    ],
  "whereBetween": [["MestreNota.DtEmissao", ["inicio", "fim"]]],
  "orderBy":[["MestreNota.DtEmissao","desc"]],
  "groupBy":["MestreNota.DtEmissao", "CategPro.NmCategoria"]
}

### mensal
POST http://localhost:3000/api/knex/sql/oftalmo
Content-Type: application/json

{
  "from":[{"raw":
          "NatOpe INNER JOIN (CategPro INNER JOIN (CadPro INNER JOIN (MestreNota INNER JOIN ItemNota ON (MestreNota.Serie = ItemNota.Serie) AND (MestreNota.NumNota = ItemNota.NumNota) AND (MestreNota.CdFilial = ItemNota.CdFilial)) ON CadPro.CdProduto = ItemNota.CdProduto) ON CategPro.CdCategoria = CadPro.CdCategoria) ON (ItemNota.Nop = NatOpe.Nop) AND (NatOpe.Nop = MestreNota.Nop)"
  }],
  "select":[{"raw":
            "CONVERT(CHAR(7),[mestrenota].[DtEmissao],120) AS mes, CategPro.NmCategoria as categoria, Sum(ItemNota.Quantidade) AS quantidade"
  }],
  "orderByRaw":["CONVERT(CHAR(7),[mestrenota].[DtEmissao],120) desc"],
  "groupByRaw":["CONVERT(CHAR(7),[mestrenota].[DtEmissao],120), CategPro.NmCategoria"],
  "whereRaw":["CONVERT(CHAR(7),[mestrenota].[DtEmissao],120)>='${mes}'"],
  "where":[
    [ "MestreNota.CdFilial", 1],
    [ "MestreNota.Tipo","<>","C"],
    [ "MestreNota.NotadeComplemento","N"],
    ["NatOpe.Nop", 5151]
    ]
}

### modelo
POST http://localhost:3000/api/knex/sql/oftalmo
Content-Type: application/json

{
  "from":{"raw":
        "NatOpe INNER JOIN (CategPro INNER JOIN (CadPro INNER JOIN (MestreNota INNER JOIN ItemNota ON (MestreNota.Serie = ItemNota.Serie) AND (MestreNota.NumNota = ItemNota.NumNota) AND (MestreNota.CdFilial = ItemNota.CdFilial)) ON CadPro.CdProduto = ItemNota.CdProduto) ON CategPro.CdCategoria = CadPro.CdCategoria) ON (ItemNota.Nop = NatOpe.Nop) AND (NatOpe.Nop = MestreNota.Nop)"
  },
    "select":[{"raw":
          "CadPro.Descricao as modelo, Sum(ItemNota.Quantidade) AS quantidade"
  }],
  "orderBy":["CadPro.Descricao"],
  "groupBy":["CadPro.Descricao"],
  "where":[
    [ "MestreNota.CdFilial", 1],
    [ "MestreNota.Tipo","<>","C"],
    [ "MestreNota.NotadeComplemento","N"],
    ["NatOpe.Nop", 5151],
    [ "MestreNota.DtEmissao","dia"]
    ]
}