@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}

### Index
GET {{host}}/api/trpc/agendaTelefone.list
?input={"order":[["agenda_telefone_id","asc"]]}

### Index
GET {{host}}/api/trpc/agendaTelefone.read
?input={"id":{"agenda_telefone_id":"1"}}
