export type TgroupSubject = keyof typeof groupSubject.fields

export const groupSubject = {
  database: 'oftalmo',
  table: 'groupSubject',
  primary: ['idGroup', 'idSubject'],
  fields: {
    idGroup: {
      table: 'groupSubject',
      name: 'idGroup',
      data_type: 'varchar',
      max_length: 50,
      numeric_precision: null,
      numeric_scale: null,
      is_nullable: false,
      default_value: null,
      is_primary_key: false,
      is_unique: false,
      has_auto_increment: false,
      foreign_key_table: null,
      foreign_key_column: null,
      is_generated: false,
      generation_expression: null,
    },
    idSubject: {
      table: 'groupSubject',
      name: 'idSubject',
      data_type: 'varchar',
      max_length: 50,
      numeric_precision: null,
      numeric_scale: null,
      is_nullable: false,
      default_value: null,
      is_primary_key: false,
      is_unique: false,
      has_auto_increment: false,
      foreign_key_table: null,
      foreign_key_column: null,
      is_generated: false,
      generation_expression: null,
    },
  },
}
