export type Ttbl_OP_Raio = keyof typeof tbl_OP_Raio.fields

export const tbl_OP_Raio = {
  "database": "oftalmo",
  "table": "tbl_OP_Raio",
  "primary": [
    "kRaio"
  ],
  "fields": {
    "kRaio": {
      "table": "tbl_OP_Raio",
      "name": "kRaio",
      "data_type": "int",
      "max_length": 4,
      "numeric_precision": 10,
      "numeric_scale": null,
      "is_nullable": false,
      "default_value": null,
      "is_primary_key": true,
      "is_unique": true,
      "has_auto_increment": true,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "Dioptria": {
      "table": "tbl_OP_Raio",
      "name": "Dioptria",
      "data_type": "real",
      "max_length": 4,
      "numeric_precision": 24,
      "numeric_scale": null,
      "is_nullable": true,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "Raio1": {
      "table": "tbl_OP_Raio",
      "name": "Raio1",
      "data_type": "real",
      "max_length": 4,
      "numeric_precision": 24,
      "numeric_scale": null,
      "is_nullable": true,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "Raio2": {
      "table": "tbl_OP_Raio",
      "name": "Raio2",
      "data_type": "real",
      "max_length": 4,
      "numeric_precision": 24,
      "numeric_scale": null,
      "is_nullable": true,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "Espessura": {
      "table": "tbl_OP_Raio",
      "name": "Espessura",
      "data_type": "real",
      "max_length": 4,
      "numeric_precision": 24,
      "numeric_scale": null,
      "is_nullable": true,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "Diametro": {
      "table": "tbl_OP_Raio",
      "name": "Diametro",
      "data_type": "real",
      "max_length": 4,
      "numeric_precision": 24,
      "numeric_scale": null,
      "is_nullable": true,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    },
    "Tipo": {
      "table": "tbl_OP_Raio",
      "name": "Tipo",
      "data_type": "char",
      "max_length": 1,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_nullable": true,
      "default_value": null,
      "is_primary_key": false,
      "is_unique": false,
      "has_auto_increment": false,
      "foreign_key_table": null,
      "foreign_key_column": null,
      "is_generated": false,
      "generation_expression": null
    }
  }
}
  