import { connections } from "@/config/connections";

import { CidadeModel } from "@/models/cidade/cidade-model";
import { ClienteModel } from "@/models/cliente/cliente-model";
import { DiamanteModel } from "@/models/diamante/diamante-model";
import { EmpregadoModel } from "@/models/empregado/empregado-model";
import { EstoqueModel } from "@/models/estoque/estoque-model";
import { FornecedorModel } from "@/models/fornecedor/fornecedor-model";
import { MaquinaModel } from "@/models/maquina/maquina-model";
import { NfCfopModel } from "@/models/nf-cfop/nf-cfop-model";
import { NfEntradaControleModel } from "@/models/nf-entrada-controle/nf-entrada-controle-model";
import { NfEntradaItemModel } from "@/models/nf-entrada-item/nf-entrada-item-model";
import { NfEntradaLogModel } from "@/models/nf-entrada-log/nf-entrada-log-model";
import { NfEntradaModel } from "@/models/nf-entrada/nf-entrada-model";
import { NfSaidaFvModel } from "@/models/nf-saida-fv/nf-saida-fv-model";
import { NfSaidaItemModel } from "@/models/nf-saida-item/nf-saida-item-model";
import { NfSaidaModel } from "@/models/nf-saida/nf-saida-model";
import { OperacaoProducaoModel } from "@/models/operacao-producao/operacao-producao-model";
import { PagarModel } from "@/models/pagar/pagar-model";
import { PedidoItemModel } from "@/models/pedido-item/pedido-item-model";
import { PedidoModel } from "@/models/pedido/pedido-model";
import { ProdutoCategoriaModel } from "@/models/produto-categoria/produto-categoria-model";
import { ProdutoControleModel } from "@/models/produto-controle/produto-controle-model";
import { ProdutoEstatisticaModel } from "@/models/produto-estatistica/produto-estatistica-model";
import { ProdutoModel } from "@/models/produto/produto-model";
import { ReceberModel } from "@/models/receber/receber-model";
import { UsuarioModel } from "@/models/usuario/usuario-model";
import { VendedorMetaModel } from "@/models/vendedor-meta/vendedor-meta-model";
import { VendedorModel } from "@/models/vendedor/vendedor-model";
import { AgendaTelefoneModel } from "./agenda-telefone/agenda-telefone-model";
import { EsterilizacaoExternaModel } from "./esterilizacao-externa/esterilizacao-externa-model";
import { EsterilizacaoInternaModel } from "./esterilizacao-interna/esterilizacao-interna-model";
import { EtiquetaExternaModel } from "./etiqueta-externa/etiqueta-externa-model";
import { EtiquetaInternaModel } from "./etiqueta-interna/etiqueta-interna-model";
import { GroupSubjectModel } from "./group-subject/group-subject-model";
import { OrdemProducaoOperacaoModel } from "./ordem-producao-operacao/ordem-producao-operacao-model";
import { OrdemProducaoModel } from "./ordem-producao/ordem-producao-model";
import { ProdutoItemModel } from "./produto-item/produto-item-model";
import { ProdutoPlanoModel } from "./produto-plano/produto-plano-model";

export type TModels = {
  agendaTelefone: AgendaTelefoneModel;
  cidade: CidadeModel;
  cliente: ClienteModel;
  diamante: DiamanteModel;
  empregado: EmpregadoModel;
  esterilizacaoExterna: EsterilizacaoExternaModel;
  esterilizacaoInterna: EsterilizacaoInternaModel;
  estoque: EstoqueModel;
  etiquetaExterna: EtiquetaExternaModel;
  etiquetaInterna: EtiquetaInternaModel;
  fornecedor: FornecedorModel;
  nfSaida: NfSaidaModel;
  nfSaidaFv: NfSaidaFvModel;
  ordemProducao: OrdemProducaoModel;
  ordemProducaoOperacao: OrdemProducaoOperacaoModel;
  produtoItem: ProdutoItemModel;
  produtoPlano: ProdutoPlanoModel;
  usuario: UsuarioModel;
  groupSubject: GroupSubjectModel;
  maquina: MaquinaModel;
  nfCfop: NfCfopModel;
  nfEntrada: NfEntradaModel;
  nfEntradaControle: NfEntradaControleModel;
  nfEntradaLog: NfEntradaLogModel;
  nfEntradaItem: NfEntradaItemModel;
  nfSaidaItem: NfSaidaItemModel;
  operacaoProducao: OperacaoProducaoModel;
  pagar: PagarModel;
  pedido: PedidoModel;
  pedidoItem: PedidoItemModel;
  produto: ProdutoModel;
  produtoCategoria: ProdutoCategoriaModel;
  produtoControle: ProdutoControleModel;
  produtoEstatistica: ProdutoEstatisticaModel;
  vendedor: VendedorModel;
  vendedorMeta: VendedorMetaModel;
  receber: ReceberModel;
};

export const models = {} as TModels;

export const modelsRegister = (args: any) => {
  new AgendaTelefoneModel(args);
  new CidadeModel(args);
  new ClienteModel(args);
  new DiamanteModel(args);
  new EmpregadoModel(args);
  new EsterilizacaoExternaModel(args);
  new EsterilizacaoInternaModel(args);
  new EstoqueModel(args);
  new FornecedorModel(args);
  new EtiquetaExternaModel(args);
  new EtiquetaInternaModel(args);
  new NfSaidaFvModel(args);
  new NfSaidaModel(args);
  new OrdemProducaoModel(args);
  new OrdemProducaoOperacaoModel(args);
  new ProdutoItemModel(args);
  new ProdutoPlanoModel(args);
  new UsuarioModel(args);
  new GroupSubjectModel(args);
  new MaquinaModel(args);
  new NfCfopModel(args);
  new NfEntradaModel(args);
  new NfEntradaControleModel(args);
  new NfEntradaLogModel(args);
  new NfEntradaItemModel(args);
  new NfSaidaItemModel(args);
  new OperacaoProducaoModel(args);
  new PagarModel(args);
  new PedidoModel(args);
  new PedidoItemModel(args);
  new ProdutoModel(args);
  new ProdutoCategoriaModel(args);
  new ProdutoControleModel(args);
  new ProdutoEstatisticaModel(args);
  new VendedorModel(args);
  new VendedorMetaModel(args);
  new ReceberModel(args);
};

const args = {
  connections,
  models,
};

modelsRegister(args);
